- .config/configstore/update-notifier-nodemon.json
- models/user.coffee
- package.json
- sh/compile-jade.sh
- sh/rebuild-client.sh
- sh/start.sh
- sh/uglify.sh
- sh/watchers.sh
- watch.json
We're able to use watchers everywhere, which not only speeds up the build substantially but also makes the 'dev' and 'production' environments share the same build pipeline.
play with it at https://glitch.com/~curvy-harbor
> Use watchers to drastically speed up the community site build. case 3280332

- public/styles/pages/error.styl
- src/templates/pages/error.jade
This should fix up the starfield not extending to the entire width of the page (https://our.manuscript.com/f/cases/3294539/full-screen-the-black-stars-on-our-404-page).
It also updates a couple gomix.com links to glitch.com and removes the beta tag
> errorpage: 404 page's stars should extend to the max width (case 3294539)

- src/presenters/includes/description-field.jsx
- src/presenters/includes/markdown.jsx
empty markdown now renders as `<span></span>` which breaks the `:empty` check used to show the placeholder. Now it will render completely blank
> Nova chance: Show placeholder on empty description fields

- src/presenters/pop-overs/create-team-pop.jsx
- src/utils/assets.js
Fixes the following errors:
``` 
103:9  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
103:9  error  Non-interactive elements should not be assigned mouse or keyboard event listeners               jsx-a11y/no-noninteractive-element-interactions```
> create-team-pop.jsx: element with onClick should be an interactable

- src/presenters/current-user.jsx
I was putting the user object that gets shared with the editor through the model, but it's the community site specific cached user that gets used everywhere and needs to be run through the model func.
> Nova Chance: Fix a regression when adding a project to a team

- src/presenters/includes/team-users.jsx
- src/presenters/pop-overs/popover-nested.jsx
- src/presenters/pop-overs/team-user-info-and-remove-pop.jsx
- src/presenters/pop-overs/team-user-info-pop.jsx
- src/presenters/pop-overs/team-user-remove-pop.jsx
- styles/pop-overs.styl
Pretty much some separate code to handle the 'show an alt menu in place when you click the button'. I also added a popover component that renders a title with a back button. Through the magic of contexts you don't have to give it a function, it'll grab it from the closest menu.
I also split the team user info pop back into two files since it's gotten pretty large. The only differences are at the bottom of teamuserinfo where it uses NestedPopover and in teamuserremove where it uses NestedPopoverTitle.
Once either this or exopose-create-team gets merged I'll incorporate it into that menu.
> Nova chance: Standardize NestedPopover

- src/presenters/current-user.jsx
We already get an anon user from any page with an embed on it (the homepage and all ~project pages). I'm standardizing it so it happens on every page instead. Creating the anon user doesn't block rendering, so everything will still need to handle the 'no user object at all' condition.
> Nova chance: Always create an anon user for visitors

- server/api.js
- server/proxy.js
- server/redirects.js
- src/presenters/pages/join-team.jsx
- src/presenters/pages/team-or-user.jsx
The api is going to start giving 404s when teams don't exist rather than returning `null`.
I also did some cleanup around the proxy so we can use Pirijian's new teams page. Proxied sites can exist at their root url now, but they'll have to be careful not to use any base relative urls.
> Superb guide: Handle 404s when getting users/teams, proxy the teams page

- src/presenters/includes/team-analytics-project-details.jsx
- src/presenters/includes/team-analytics.jsx
- src/presenters/pages/team.jsx
https://www.notion.so/glitch/bug-teams-page-crasher-click-add-project-in-analytics-when-no-projects-4e95f5a8dcbe405da6c576215091cbee
> Superb-guide: Fix the the extra add project buttons on team pages

- src/presenters/current-user.jsx
The change to auto create anon users broke an assumption on page load such that we don't report the current user to sentry and analytics unless you sign in or out on that page load.
It used to only report the user when the user changed, but now you start with the user loaded and generally don't change it.
> Profuse-tea: Fix currentUser identification

- src/presenters/includes/expander.jsx
- styles/includes/expander.styl
https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=44f17f21280442dca6c6a39949f4448b
before:
before (on hover):
after:
after (on hover):
> Ordinary emu -- touch up 'show more' button styling on readme files

- src/presenters/includes/project-result-item.jsx
- src/presenters/includes/team-users.jsx
- src/presenters/pages/router.jsx
- src/presenters/pop-overs/team-user-info-pop.jsx
- styles/pop-overs.styl
- styles/tooltips.styl
1. Some just barely supported browsers don't support the `scrollTo` object syntax
2. Hide the remove from team button if you're the only member of the team
3. The analytics project switcher would show user names when you hovered over projects
> Profuse tea: A couple small bug fixes

- package.json
- shrinkwrap.yaml
Also updated webpack just a little. This fixes the uglify-js vs uglify-es confusion in pnpm and the compilation issue in production due to uglify-js in the latest version of uglifyjs-webpack-plugin not supporting es6
> Profuse-tea: Roll back uglifyjs-webpack-plugin to match the one bundled with webpack

- src/presenters/includes/expander.jsx
- src/presenters/pages/project.jsx
https://superb-guide.glitch.me/~three-js
I got inspired for this based on the only show x projects pr. Readmes used to check their height on load and if they were short enough they'd snap to the expanded state.
That had the side effect of sometimes expanding readmes that were too large, because they images that didn't load until after the height check. The new solution is to track the scrollHeight and show the fade/button if the readme is actually being cut off.
There is no way to actually listen for scrollHeight changes, so instead I'm just watching for onLoad events and updating whenever one comes in. (capturing because onLoad doesn't bubble)
> Superb guide: Don't auto expand readmes

- src/client.jsx
- src/presenters/includes/error-boundary.jsx
- src/presenters/layout.jsx
- src/presenters/pop-overs/add-team-user-pop.jsx
- src/presenters/pop-overs/create-team-pop.jsx
- src/presenters/question-item.jsx
- src/presenters/questions.jsx
- When adding a user to a team, don't consider the string to be an email domain unless it contains a . (`@greg` is not a domain, but `@gre.g` is)
- The create team pop didn't handle 404 errors from the api, now it does
- Added an `ErrorBoundary` component, which catches errors during rendering (not in event handlers or async stuff, only during rendering) and replaces its children with the standard 'something went wrong' text. It's used on the questions list (since it has had issue with bad data in the past) the page within `Layout`, and around the entire react tree. This should be enough such that users are never left with a completely blank page, and in most cases will still have a functional header
> Profuse tea: stricter email identification, more 404 handling, error boundaries

- src/presenters/includes/avatar.jsx
- src/presenters/includes/team-analytics-project-details.jsx
- styles/includes/team-analytics.styl
https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=78db6cf11f8a43859bd17bc800cebde0&p=4be850f96ef14972a33f2a6c3780d31b
in the team analytics project details, if you hover over the first project in any row after the first, the tooltip will appear over the last project in the previous row. Not sure why this is happening, but adding `display: inline-block` fixes it. I also did some cleanup around project avatars within that file.
> Profuse tea: Fix an odd hover bug in the remix list

- src/presenters/pages/project.jsx
Allow project page embeds to request permissions. This isn't enough on its own, because the embed has an iframe in it to load the preview, which will also need the same permission set.
https://www.notion.so/glitch/Embeds-iframe-element-needs-allow-attribute-so-getusermedia-geolocation-and-other-web-apis-in-apps-work-130ffb626a2d4c50b8987f444be1cbc4
> Quixotic rocket: Allow project page embed to request permissions

- server/api.js
- server/constants.js
- server/routes.js
- sh/webpack.sh
- src/models/project.js
- src/presenters/includes/project-result-item.jsx
- src/presenters/includes/team-analytics-activity.jsx
- src/presenters/includes/team-analytics-project-details.jsx
- src/presenters/includes/team-analytics.jsx
- src/presenters/pages/project.jsx
- src/presenters/pop-overs/new-project-pop.jsx
- views/index.ejs
This PR allows the Platform team (and anyone else in the company, actually!) to let the community site or any of its remixes use the _development_ API that they are running in their devbox. Of course this only applies to them, the real community site at glitch.com is not affected at all :)
The goal of the PR is to make it easier to collaborate between the Platform team and the Community team: API changes can be tested directly against the community site _before being pushed to production_, and bugfixes can be done _in real time_.
As described in [this notion case](https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=92d2d65272d74da7bc59d3397af57275), API is switched on the frontend based on the hostname on which the community site is served. …
> Maple harmonica - switch between API backends based on hostname

- src/presenters/pop-overs/team-analytics-project-pop.jsx
- styles/pop-overs.styl
- styles/results-list.styl
https://pop-over-fixes.glitch.me
1. Changes analytics pop-over on teams page to use wide-pop styling
2. Enables wide-pop to fit nicely on mobile
./styles/pop-overs.styl:867163/104
./styles/results-list.styl:867163/4
./src/presenters/pop-overs/team-analytics-project-pop.jsx:867163/9
> Pop-over fixes

- src/presenters/current-user.jsx
- src/presenters/pages/category.jsx
- src/presenters/pages/index.jsx
- src/presenters/pages/project.jsx
- src/presenters/pages/search.jsx
- src/presenters/pop-overs/user-options-pop.jsx
If currentUser would be null, instead act like we're an anon user. The two differences between this and a real anon is the id (`0`) and the avatar color (`#aaa`). The user pop is visible while signed out now, but it is disabled.
There's probably a lot of potential cleanup, I just hit the main 'do not render if there is no user' spots.
> Nova chance: Ensure that there is always a currentUser object

- package.json
- src/presenters/random-categories.jsx
The category project counts were getting stored in an array in the order that the requests came back, so they get jumbled relative to the categories they belong to. This stores them in a map of category id to count so the order they come back doesn't matter.
> Superb guide: Fix homepage categories having wrong project counts

- styles/includes/notifications.styl
- styles/pages/user-and-team-page.styl
- styles/tooltips.styl
- styles/users.styl
https://leather-windscreen.glitch.me
Fixed styling regression to adding users to team pages https://www.notion.so/glitch/Notification-styling-regression-30de76cc38614956bda1bf44c5399e66
Summary of changes
* Fixed padding of inline notification
* Adjusted margins around Add Button when new user is added
* Darkened opacity of newly added user (to improve legibility)
On Production:
On leather-windscreen:
> Styling Fixes to Team Page

- src/presenters/pages/team.jsx
- src/presenters/team-editor.jsx
Future work: move api calls to where they're used and expose an 'onProjectDeleted' event for the user page to listen to and act on.
> Profuse Tea: Fix the delete project button on the teams page

- src/presenters/pop-overs/new-project-pop.jsx
- styles/results-list.styl
This PR fixes https://glitch.manuscript.com/f/cases/3309594/css-bottom-of-new-project-list-has-a-border
Note that there is a similar rule already implemented here:
https://glitch.com/edit/#!/ribbon-pipe?path=styles/pop-overs.styl:55:9
which removes bottom borders from some popovers, but the pop-over-section class which implements the styling is only currently used in NestedPopover components, not single-level popovers like this one.
I considered just using that class here, but in the new projects popover, the top-level element in the results list is actually a tracked link, and it seemed weird to add the class to that element. Additionally the pop-over-section class also adds extra padding which looks bad on this popover. Seems like these popovers could be a good candidate for later …
> Removed the bottom border from the last element in the new projects popover

- styles/overlays.styl
using `transform:translateX(50%)` causes blurriness when the screen is an odd number of pixels in width (definitely in chromeOS, possibly also in other OS/browsers). Changed the pupdate so that it is centered in the screen without using this CSS.
https://gifted-suede.glitch.me/ (to check it out, go to the avatar menu and click the "new stuff" button)
https://glitch.manuscript.com/f/cases/3326591/pupdate-blurry-overlays-in-chromeos
giving to Sheridan because we were just talking CSS in coffeetime :)
> Gifted Suede: update the pupdate to not use CSS transforms

- FAQ.md
- src/presenters/collection-editor.jsx
- src/presenters/includes/dev-toggles.jsx
- src/presenters/pages/team.jsx
- src/presenters/pop-overs/add-collection-project-pop.jsx
- src/presenters/pop-overs/project-options-pop.jsx
Missing the ability to undelete collections and the preview collections on team pages, but I don't think they should block enabling this for people.
> Superb guide: Remove the dev toggle for team collections

- src/presenters/pop-overs/sign-in-pop.jsx
https://astonishing-orchestra.glitch.me/
Now if you request a sign-in email, there's a button on the success state to take you to the sign-in code pop!
As noticed/requested by cori, https://glitch.manuscript.com/f/cases/3327667/sign-in-pop-text-after-email-has-been-sent-could-be-clearer
also fixed the fact that the notification banners would disappear (as you can see in the screenshot above)
> Astonishing orchestra

- .gitignore
- package.json
- server/routes.js
- server/webpack.js
- shrinkwrap.yaml
- webpack.config.js
I had switched from including the content hash in the webpack config filename to adding it  while rendering the template because the webpack-dev-middleware tries to write the file to disk with the querystring still intact. Lazy loaded js is linked by webpack, so c3 lost its cache buster.
I've got a 'real' fix out, which is for the dev middleware to clip the querystring off of filenames when writing to disk (like webpack normally does) https://github.com/webpack/webpack-dev-middleware/pull/361
In the meantime, I switched back to cache busting in the webpack config and disabled writing to disk in dev mode. That has the side effect that when you switch a server from dev to prod mode, it will show an outdated site until the next prod build finishes.
I also cut the cache time down from a month …
> Profuse tea: Fix issues with cache busting

- src/curated/featured-embed.js
- webpack.config.js
Test on https://glitch.com/edit/#!/quick-rutabaga
Modified the development source map to be a less intensive process, which means we no longer see the Out of Memory errors on community site remixes.
> Enable community site remixes to build without Performance Boost

- server/proxy.js
https://glitch.com/about/sitemap.xml
https://quixotic-rocket.glitch.me/about/sitemap.xml
I split the proxy in two rather than making the check in the decorator because the presence of a decorator forces the proxy to download the full page in memory rather than streaming it to the response.
@garethx
> Quixotic rocket: Rewrite urls in proxied sitemaps

- server/server.js
Over in server/proxy.js I deployed a bit of code that alters any sitemap.xml that gets proxied, rewriting urls to match the request. It works for glitch.me urls, but when you request https://glitch.com/culture/sitemap.xml req.hostname gets proxied as community.glitch.me. This change tells express to respect `X-Forwarded-Host`, which I expect to be set to glitch.com. https://expressjs.com/en/api.html#req.hostname
> Quixotic rocket: Hopeful fix for proxied sitemaps

- src/curated/featured-embed.js
- src/presenters/includes/markdown.jsx
- src/presenters/pages/project.jsx
from case 3327802 https://glitch.manuscript.com/f/cases/3327802/
this was a fun one. if a project's readme only contains a number, it breaks the markdown component which requires a string and therefore breaks the whole project page. the project page's readme call is the only one that gets the data from an api call and not a prop, so i'm casting the data as a string now.
bug in action: https://glitch.com/~wide-lan
fixed: https://puddle-slip.glitch.me/~wide-lan
> Puddle slip - fixes bug where readmes that are just numbers breaks the project page

- src/presenters/includes/add-project-to-collection.jsx
- src/presenters/includes/add-team-project.jsx
- src/presenters/includes/delete-team.jsx
- src/presenters/includes/edit-collection-color.jsx
- src/presenters/overlays/new-stuff.jsx
- src/presenters/pop-overs/collection-options-pop.jsx
- src/presenters/pop-overs/delete-team-pop.jsx
- src/presenters/pop-overs/featured-project-options-pop.jsx
- src/presenters/pop-overs/project-options-pop.jsx
Removed every `opens-pop-over` except for the one in `add-collection-project.jsx` since it's covered by superb-guide. I also removed any redundant button classes I saw along the way.
> Profuse tea: Remove a bunch of unused classes

- server/server.js
- src/utils/sentry.js
Bleh, sorry I missed this in review.
We should try to share this config between the client and server, but they use separate npm packages and env variables. What do you think of just a function taking `Sentry` and `PROJECT_DOMAIN`?
> Flip the logic on shouldsenderror checks, ignore server errors too

- src/utils/assets.js
getDominantColor returns null if it finds any transparency in the image. That upsets the api which wants empty colors to be specified as an empty string.
I also did some very minor cleanup to make it more obvious what's happening
> Change getDominantColor to match the api

- src/presenters/includes/embed.jsx
- webpack.config.js
- Only build/send CSS Source Maps in non-production builds to help with production build time and bundle size
- `allowvr=yes` on the embed iframes - Fixes an issue with some chromium browsers when displaying vr content https://github.com/aframevr/aframe/issues/1979 
https://glitch.com/~absorbing-thing
> Tiny fixes 

- src/curated/collections.js
- src/curated/featured.js
- styles/collections.styl
This is a tiny change to link colors in collection headers. See it in action on my Glitch collection:
**Before** [glitch.com/@taravancil](https://glitch.com/taravancil)
**After** [successful-stoat.glitch.me/@taravancil](https://successful-stoat.glitch.me/@taravancil)
> Update link color in collection headers

- src/curated/collections.js
- src/curated/featured.js
- src/presenters/includes/team-users.jsx
- src/presenters/pop-overs/team-user-info-pop.jsx
**Case** [3327689](https://glitch.manuscript.com/f/cases/3327689/Trying-to-remove-myself-as-the-only-admin-from-a-team-needs-a-clearer-error-message)
**Remix** https://team-admin-bugfixes.glitch.me
This fixes when you're the only admin on a team and try to remove yourself or demote your admin status. Instead of updating the error message when an admin tries to do something they shouldn't, I decided to hide those controls entirely so they can't do forbidden things!
Most of these changes are Prettier changes, the meaningful changes are on the following lines:
- [`userIsTheOnlyAdmin`](https://github.com/FogCreek/Glitch-Community/compare/team-admin-bugfixes?expand=1#diff-5efa2e8a59389e5b21ef386d07506282R32)
- [`38`-`41`: `canChangeUserAdminStatus`](https://github.com/FogCreek/Glitch-Community/ …
> Team admin bugfixes

- src/presenters/collection-editor.jsx
- src/presenters/error-handlers.jsx
- src/presenters/includes/uploader.jsx
- src/presenters/notifications.jsx
- src/presenters/pages/search.jsx
- src/presenters/project-editor.jsx
- src/presenters/team-editor.jsx
- src/presenters/user-editor.jsx
`useCurrentUser()` `useNotifications()` `useErrorHandlers()` and `useUploader()` are all equivalent to the their `<BlahConsumer>` versions but don't require tons of nesting to use (you can't use hooks in class components though, so there is still one layer of wrapping to gather them up)
I also cleaned up some props that are marked as optional but aren't.
> Superb guide: use hooks to make editors way more readable

- shrinkwrap.yaml
- src/presenters/pop-overs/add-project-to-collection-pop.jsx
- src/presenters/pop-overs/project-options-pop.jsx
Changes are in https://glitch.com/edit/#!/excellent-root?path=src/presenters/pop-overs/add-project-to-collection-pop.jsx:169:89
I check to see any instances where there is no corresponding user team for a collection\ (an indication that the team has been deleted) and prevent the collection from being displayed in the pop-over.
to replicate the bug on production - create a team, add a collection to that team, and then delete said team.  then, if you try to add a project to a collection, you get an error.
then go to https://excellent-root.glitch.me/ and check that the add-to-collection pop works for you.
(note, isaac is working on fixing the API endpoint to remove collections from deleted teams from the get collections response)
> Bug fix for displaying collections from soft-deleted teams

- shared/sentryHelpers.js
- src/presenters/current-user.js
- src/presenters/includes/local-storage.js
This should fix the main cause of invalid cached user errors. It happens because when you log in with a second glitch.com window open the other window tries to reload the no longer valid anon user. While the reload request is in progress it gets updated props with the signed in user. The request fails because the anon user was merged, and the user fix gets applied to the updated signed in user, showing as a correction from the anon user to the signed in user.
> Superb guide: Refactors to the current user manager

- src/presenters/current-user.js
- src/presenters/includes/local-storage.js
- src/presenters/pages/login.js
We send the load user request on page load, even if you're on the signin page. Based on the remaining events, it looks like the anon user's load request sometimes gets queued after the sign in. When it goes through the anon user doesn't exist. That triggers a user fix even though the anon user isn't relevant any more.
Before we try to fix the user, check if the user was changed. If they changed try loading the new user instead of doing a fix.
> Superb guide: Probably fix the remaining cachedUser errors

- src/presenters/user-editor.js
available at https://undeleted-project-goes-first.glitch.me/
The goal of this PR is to make it obvious to the person who has undeleted a project that it is back in their projects list. 
Currently when someone undeletes a project it is added to the end of their projects list and is not visible on the page if they have more than 12 projects. This could cause concern that the project has not been undeleted. By putting it to the top of the list it is clear to the person that it is safely back.
Gifs showing behaviour.
Current:
https://cl.ly/16de2cc116d0
New:
https://cl.ly/c1c0dec365b3
One potential issue is that on refresh the project will go back to its previous place in the list (based on last updated?). This may be confusing in a different way ("where did my project that was on the top …
> Put undeleted project to top of projects list 

- src/presenters/pages/user.js
- src/presenters/pop-overs/add-project-to-collection-pop.js
- src/presenters/user-editor.js
https://dented-supernova.glitch.me/
Currently, when the user undeletes a project, the undeleted project is shown as their most recent project.  However, upon refreshing the page, the undeleted project is no longer seen at the top of the list as user projects on the profile page are not automatically sorted by when they are last updated.
To test:
* open https://dented-supernova.glitch.me/ and try undeleting one of your projects.  Then refresh the page and check that the undeleted project still appears at the top of the list.
Manuscript case: https://glitch.manuscript.com/f/cases/3327976
> Dented supernova - handle sorting of undeleted projects + sorting of user projects by updatedAt on profile pages

- src/presenters/collection-editor.js
- src/presenters/collections-list.js
The API orders projects in a collection by the order they're added. Make the optimistic update match this.
Fixes https://glitch.manuscript.com/f/cases/3327898/
> Tree odometer: put new collection items at beginning of collection

- src/components/text/heading.js
- src/components/text/heading.styl
- src/presenters/pages/user.js
- stories/index.js
Adding a Heading component and using it in the user profile presenter.
Areas to check:
- Storybook
- User profiles
Quick links:
- [Olivia's profile with changes](https://kiwi-poinsettia.glitch.me/@oliviacpu)
- [Olivia's profile on production](https://glitch.com/@oliviacpu)
~💁 I decoupled presentation from the tag being used, but for now it can be used as a 1:1 replacement for h1-h4 by just using `tagName`. There's a comment where things are set to default for now.~
I'm going to continue to replace the rest of the header components in small PRs after this is merged to keep the potential for conflicts low.
> Text / Heading

- src/presenters/collections-list.js
- src/presenters/deleted-projects.js
- src/presenters/entity-page-featured-project.js
- src/presenters/featured-collections.js
- src/presenters/featured-embed.js
- src/presenters/more-ideas.js
- src/presenters/pages/category.js
- src/presenters/pages/collection.js
- src/presenters/pages/error.js
- src/presenters/pages/index.js
- src/presenters/pages/project.js
- src/presenters/pages/search.js
- src/presenters/pages/team.js
- src/presenters/projects-list.js
- src/presenters/questions.js
- src/presenters/recent-projects.js
Using the new `Heading` component.
I went ahead and did them all because it wasn't as large of a change as I thought.
The one place where a `className` was removed was the Category page, and there is a slight difference in spacing between this remix and production.
- [Building Blocks category on production](https://glitch.com/building-blocks)
- [Building Blocks category on this remix](https://indigo-closet.glitch.me/building-blocks)
> Text / Heading - Replacement

- src/components/buttons/button.styl
- src/components/constants.styl
- src/components/text/heading.js
- src/components/text/heading.styl
- src/components/text/markdown.styl
- src/components/tooltips/tooltip.styl
I think the tooltip component was build according to a bad implementation I'd done in the early days of CSS modules, and it was importing in the globals.styl file from the styles directory. This meant a bunch of styles that shouldn't have been available to the other components were available, so components looked fine in storybook when in fact they weren't self-composed.
Fixed a bunch of things but please let me know if you can see anything I missed! Everything is looking good at http://lumpy-organ.glitch.me/storybook
> Fixes to component styles

- shared/api.js
- src/presenters/includes/included-in-collections.js
We don't need to fetch the projects, users, etc of collections that won't even make it out of this function
> Better settee: sample collections _before_ fetching all of their data

- src/presenters/includes/embed.js
This won't work for dev builds, but we don't do any sort of babel stuff so the whole site breaks anyways.
Instead of checking if URLSearchParams exists, check if we're using the polyfilled version by checking if it is polyfilled and has a junk name value.
> Nova chance: Updated embed support check to account for polyfills

- server/api.js
- server/routes.js
- views/index.ejs
**remix** [~metadata-fixes](https://metadata-fixes.glitch.me)
**cases** [use property in meta tags](https://glitch.manuscript.com/f/cases/3327855/Replace-use-of-name-with-property-in-meta-tags), [add metadata to collections](https://glitch.manuscript.com/f/cases/3327645/Add-Meta-Data-to-Team-and-User-Collections)
This includes a few metadata fixes that improve our collection and team social cards
Uses the collection name and description (if it exists) instead of the default glitch.com metadata
Uses the team avatar for the card image, falls back to the default card image
> Metadata fixes

- src/presenters/note.js
- src/presenters/pages/collection.js
- src/presenters/project-item.js
Forgot to test out authoring a note as a team, turns out we tried to render an author without a user :( Tested it out by making a team and then creating a note.
Also fixes a bug where we were throwing an error in the console about hideNote not being defined.
Can test out my remix here: https://shaded-fold.glitch.me
> Shaded fold - bug fix for team notes

- src/presenters/pages/collection.js
- styles/pages/collection.styl
- styles/users.styl
Removed grid css to fix styling issues on collection pages.
Also removed project heading with counter to make the layout a bit more readable with annotations.
Testable links:
https://romantic-barracuda.glitch.me/@scientiffic/glitch-things
vs 
https://glitch.com/@scientiffic/glitch-things
> Romantic barracuda: Bug Fixes to Collection Grid Styling

- src/presenters/pop-overs/team-user-info-pop.js
- src/presenters/pop-overs/team-user-remove-pop.js
See https://glitch.manuscript.com/f/cases/3327687/
When removing a user from a team, there's a second popover that asks if you want to (also) remove them from the team's projects, or just the team itself. This is unnecessary and somewhat confusing if they aren't a member of any projects.
This PR moves much of the logic for removing team members from the `remove` popover and into the `info` popover, so that the remove one doesn't even need to be rendered in this particular case.
NB this is an excellent example of how putting our logic nearest to the UI that uses it makes refactoring kind of complicated.
> Wooded moose: improve flow when removing member from team

- server/constants.js
- server/routes.js
Our use of embeds makes it difficult (impossible?) to deploy a meaningful CSP. Gotta roll back the policies for `image-src`, `style-src`, and `font-src`
> CSP rollback

- src/presenters/pages/category.js
- src/presenters/pages/collection.js
- src/presenters/pages/project.js
- src/presenters/pages/questions.js
- src/presenters/pages/search.js
- src/presenters/pages/secret.js
- src/presenters/pages/team.js
- src/presenters/pages/user.js
[pictured: an amazing slug]
The infinite recursion errors we're getting are coming from react-helmet's use of [deep equality comparison on circular structures](https://github.com/nfl/react-helmet/issues/441). This is supposedly fixed in the current beta, but I think that using a title prop instead of children will also fix this (since its now comparing strings, not react elements).
> Amazing slug: use title prop for helmet

- server/routes.js
Hoping to reduce occurrences of this bug: https://glitch.manuscript.com/f/cases/edit/3328085/Improve-edge-caching-understanding-and-processes
This PR adds a 1s cache header to all non-static routes (it's placed after the static routes for this reason). This reduces the likelihood that a user will get a version of the page from cloudfront with old build URLs that don't exist on that app any more.
How to test:
- Go to https://wakeful-galleon.glitch.me/, and observe a 1s response header on the page
- Check that JS bundles still have the old caching on them (e.g. react.js)
> Added a 1-second cache header to all community site routes

- src/presenters/includes/embed.js
- src/presenters/pages/router.js
the check for native URLSearchParams doesn't need to be in component state, as it never changes and can be done well before the component renders.
> Efficacious seer: remove state from Embed component

- src/presenters/footer.js
Currently, the icons in the footer are given a `role` of `img`, but have no label. This was causing some failures when running a Lighthouse accessibility audit, and giving the landing page a score of 69/100. 
Since the icons are purely decorative and don't add context, I opted to hide them from AT using `aria-hidden`. After this change, the landing page gets a 81/100 score on accessibility running a Lighthouse audit.
> Outrageous shingle: Fix accessibility issues in footer links

- package.json
- shrinkwrap.yaml
- src/presenters/includes/embed.js
Use `new Function()` to test the features we care about without transpilation getting in the way.
Embeds now work on latest ff/chrome/edge, and get hidden in chrome 41
> Nova chance: new embed support check that should be more reliable

- src/components/tooltips/tooltip-container.js
- src/presenters/includes/avatar.js
Currently where there is a user avatar with a tooltip, there is an invalid `aria-labelledby` value if a user's name has one or more spaces. The name is being used as the `id` value, which is then passed down to `aria-labelledby`. Having a space in that value is invalid. 
To solve this, I replaced spaces in the name at the site of the `id` prop with an underscore. I'm not sure if there is a better solution, but this seems to be the most simple and solved the issue.
> Stupendous fisher 1: Fix aria-labelledby errors in avatar tooltip container

- src/presenters/includes/team-analytics.js
Bug: https://glitch.manuscript.com/f/cases/3328184/Analytics-by-project-are-broken-in-production
currentProjectDomain had been renamed to currentProjectsDomain, so we were never updating the project whose analytics the user wanted to pull.
Verify at https://wax-snowstorm.glitch.me/@glitch
> Fixed a bug that was breaking team analytics

- src/presenters/pages/search.js
- src/presenters/project-item.js
- src/presenters/projects-list.js
- src/state/search.js
- styles/pages/search.styl
- styles/projects.styl
Currently, we limit search results to 20 items per type.
Instead, when showing all search result types, limit 20 items per type, but show all results when showing only a single type.
---
Indicate that there are more results than are visible in the filter badge. (Using an imprecise number here signals to the user that they should refine their search, and allows us to make a smaller initial search request.)
---
Add a "show all" button to the bottom of the results for a type that sets the search filter.
> Superficial park: show all items of type when filter applied

- src/presenters/collection-item.js
- styles/collections.styl
* Remix link: https://cedar-deal.glitch.me/@modernserf
* Manuscript link: https://glitch.manuscript.com/f/cases/3328181/
* make long project names in collections ellipsify when they're too big to fit on one line
- Look at collections with projects that have long project names as they appear on other pages, e.g. 
+ user page: https://cedar-deal.glitch.me/@modernserf
+ project page (included in collections) https://cedar-deal.glitch.me/~community-site-test-runner-staging
* is truncating the project title the desired effect, or should collection items have variable sizes? They have a fixed height defined in their CSS, but a lot of the other item components have variable height.
> Cedar deal: fix collection UI overflow

- shared/sentryHelpers.js
- src/components/inputs/text-input.js
- src/presenters/featured-collections.js
- src/presenters/pop-overs/create-team-pop.js
- src/utils/sentry.js
* Remix link: https://lightning-badger.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3327972/Sentry-exclude-errors-from-browser-extensions
* Specs/Notion docs: n/a
* Adds `glitch.com` to `whitelistUrls` in Sentry initialization to prevent external errors from being reported
* In`https://glitch.com/edit/#!/lightning-badger?path=shared/sentryHelpers.js:16:0` modify the condition so that errors will be reported when not on production, and then cause an error.
Configuration.
> Lightning badger: Limit reported Sentry errors to Glitch.com

- src/presenters/pages/router.js
- src/presenters/pages/search.js
- src/state/search.js
* Remix link: https://stingy-print.glitch.me/search
* Manuscript link: https://glitch.manuscript.com/f/cases/3328201/
* activeFilter is now a query param, so you can link to a category of search results, and the search filter is persistent across page refreshes
* search: https://stingy-print.glitch.me/search?q=community
* apply a filter and refresh the page
* it should show the filtered search results
- Is this useful / worthwhile?
- Does this impact loading performance?
> Stingy print: store active search filter in query params

- src/presenters/pop-overs/sign-in-pop.js
* Remix link: https://iris-okapi.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3327691/
* Specs/Notion docs: https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=78db6cf11f8a43859bd17bc800cebde0&p=40dcbd076b574f1695d94094742608e5
* Previously the error would show after submitting that an invalid email was submitted. This checks for a valid email first and then displays an error below the text input.
* Try to enter an invalid email and see what happens on ~community and this remix.
I think this is just the quickest way to make the styles consistent. There are probably notes we could make as we componentize more things.
> Iris okapi: Update email sign in to have consistent error styles

- src/curated/featured.js
- src/presenters/pop-overs/sign-in-pop.js
- styles/pop-overs.styl
* Remix link https://torpid-existence.glitch.me/
* Manuscript link https://glitch.manuscript.com/f/cases/3328252/add-TOS-and-privacy-agreement-to-sign-up-pop-over
* Added terms of services and privacy statement to our sign-in-pop
* Click on the sign in pop
> Torpid existence - added TOS & privacy policy to sign in pop

- styles/includes/projects-collections-teams-users-container.styl
[manuscript case](https://glitch.manuscript.com/f/cases/3328275/Help-requests-are-getting-stretched-out-behind-the-featured-stuff)
[twist-tuba.glitch.me/questions](https://twisty-tuba.glitch.me/questions)
These changes also affect any lists that use one of `.projects-container`, `.users-container`, `.teams-container`, `.collections-container`. I've checked that adding the `align-items` property doesn't introduce any regressions, but it would be great to get some extra eyes on team/user pages, collections, and search results
> Fix alignment of help items on homepage and /questions

- src/components/user/users-list.js
fix bug where users list never loads for legacy project results
> Knowing apology: `and`, not `or`

- src/components/search/autocomplete.js
https://fertile-ruby.glitch.me
Autocomplete was breaking because CollectionLink was expecting the collections to have a fully populated user/team object, but search collection results have a `fullUrl` parameter instead.
* enable algolia flag in https://fertile-ruby.glitch.me/secret
* search for "react"
* search should contain react collections
* clicking a collection result should take you to that collection
> Fertile Ruby: fix algolia autocomplete

- src/components/blocks/search-result-cover-bar.styl
- src/components/collection/collection-item.styl
- src/components/project/project-item.styl
- src/components/search/search-results.js
- src/components/team/team-item.js
- src/components/team/team-item.styl
- src/components/user/user-item.styl
- src/components/user/users-list.js
- src/curated/collections.js
- src/curated/featured-embed.js
- src/state/search.js
* Remix link: https://bloom-velociraptor.glitch.me
* load team users in algolia search results
* fix overflow issues in team/user descriptions (allow overflow of tooltips, but break long words in descriptions)
* use consistent border radii for search result items
* incorporate fixes from #427
* enable algolia search at https://bloom-velociraptor.glitch.me/secret
* search https://bloom-velociraptor.glitch.me/search?q=community&activeFilter=all
* Does team user loading work correctly?
* Is this the right strategy for text overflow?
> Bloom velociraptor: updates for team search results

- server/routes.js
- src/curated/collections.js
- views/api-auth.ejs
* Remix link: https://hail-diploma.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328329/operations-has-an-error-RUNNING_ON-is-not-defined-in-api-auth-ejs
* Specs/Notion docs: n/a
* Load `RUNNING_ON` in `api-auth.ejs`.
* Everything should be the same as before.
* ~There's a note in the `api-auth.ejs` about potential security implications changing this setup. Is this a safe change?~
* ~Should the template reference the `currentEnv` variable instead?~
* ~Should I just reverse the check in the template (`"development" === RUNNING_ON`?)~
> hail-diploma: Change reference of environment

- webpack.config.js
* Clean Webpack Plugin changed to verbose (so we can see what files it's removing), and no longer removes the storybook folder or stats.json
> Imaginary tourmaline: Webpack stop deleting storybook files

- styles/pop-overs.styl
* https://loud-cockroach.glitch.me/
* https://glitch.manuscript.com/f/cases/3328349/New-Project-Pop-is-popping-up-off-the-screen
before 😭 
after 🎉 
during 🐞 https://twitter.com/dykediscourse/status/1092885295865970688
* open new project popover from the right rather than the left
* pretty sure this is used in only one place, you open the remix (and don't log in!) and click new project
felt too easy did I forget to double check anything?
> loud-cockroach: open new project popover from the right

- src/components/project/project-item.styl
* https://bead-walrus.glitch.me/
* https://glitch.manuscript.com/f/cases/3328320/
before 😭 notice how the user avatars on the project item below it are appearing above the pop over
after 🎉 
* moves the z-index of 1 to a lower level component (I believe we have it there mainly for the hover tooltips that tell users the names of each user avatar)
* I tried to map out everywhere we use project items and as best I can tell everything looks good but feel free to give it your own test!
* does this break anything I didn't know to test for? 
* honestly I'm still a little mystified why the original code doesn't work so if you see why I bet I would learn a thing about zindexes I didn't learn before. Here's my current understanding of what's happening:
```
header (parent) - zIndex of 1, position …
```
> Bead-Walrus: fix z-index for dropdowns

- src/components/profile/profile-list.js
* Remix link: https://dark-meteor.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328317/Cannot-read-property-getBoundingClientRect-of-null
* Don't try to get the component's width if it's not mounted.
* No idea, I didn't encounter this in development. My hypothesis is that this is happening when someone navigates while a ProfileList is resizing, but there's a very narrow window when that would happen and I couldn't get it to work in dev. Deploy and see if the sentry errors decrease?
> Dart Meteor: only set width if ref is mounted

- src/components/images/mask-image.js
- src/components/images/mask-image.styl
- src/presenters/featured-embed.js
- src/presenters/featured.js
- styles/includes/featured.styl
- styles/includes/zine-items.styl
* Remix link https://square-salamander.glitch.me
* Manuscript link https://glitch.manuscript.com/f/cases/3328364/
* use MaskImage component on home page
* tweaks for MaskImage component (add mask5 class, allow hyphenated class names, dont fit to height)
* remove old mask CSS
* visit https://square-salamander.glitch.me
* verify the masks look correct on featured embed and culture blog links
> Square salamander: use mask-image component on home page

- src/components/global.styl
- src/presenters/overlays/new-stuff.js
- styles/new-stuff.styl
- styles/overlays.styl
* https://somber-humor.glitch.me/
* https://glitch.manuscript.com/f/cases/3328343/New-stuff-pop-appears-on-the-left-on-Safari-from-homepage
before ☹️ 
after 💃  
* removes unused/broken class `overlay-narrow`
* updates `new-stuff-overlay` to have the correct width, removes `left`, `margin`, and `transform` properties as I don't think those added anything and added bugs in safari. 
* if you don't see the new stuff dog/cat thing you can either mess with your localstorage.userPrefs or you can update line 128 to be `newStuffReadId: 0,` here: https://glitch.com/edit/#!/somber-humor?path=src/presenters/overlays/new-stuff.js:128:6 (just remember to remove it 😄 )
anything I'm missing in removing some of this styling? seems legit to me?
> Somber humor: fix `New Stuff` dialog positioning

- src/components/containers/projects-list.js
- src/presenters/pop-overs/project-options-pop.js
* https://sweet-blinker.glitch.me
* https://glitch.manuscript.com/f/cases/3328335/
http://g.recordit.co/ENHzTG95uw.gif
* we used to overwrite `props.projects` to whatever the filteredProjects results were which was fine in the initial render, but then if we tried to filter again after a delete or a remove it was filtering with the existing filtered projects rather than the whole list. By using another variable `displayedProjects` we ensure that whenever we call filterProjects we are filtering from the full and current list.
* useEffect to re-filter anytime props.projects changes.  
* add some animation to the removeProject from team function
* on a team page: add a project, filter projects, and click "remove project" 
* on user page: create a throwaway project, filter projects, and click …
> Sweet blinker: Fix removing projects

- src/state/current-user.js
https://glitch.fogbugz.com/f/cases/3327984/Use-the-new-api-for-user-management
Gets rid of some calls to the old api and replaces them with equivalent rest api calls
Try signing in and out, and use different pages on the site to make sure they aren't broken from a new data layout or something
> Quixotic rocket: Use the rest api in current-user.js

- src/presenters/pages/login.js
* Remix link: https://frosted-aquarius.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/edit/3327833/Handle-case-where-Facebook-or-Github-login-fails-due-to-no-email-provided-by-Facebook-Github
When we get a `403` from the API after login we know that we didn't get an email back from the provider. This handles that case, suggests login with email instead, and no longer reports the error to Sentry.
I based this off of `nova-chance` because Greg has work on the same stuff that I didn't want to conflict with. It could go to `master` but it will have more changes in the diff.
Signing up with a Facebook account with no email address associated will reproduce this. I have one if you want to use it. :(
Always looking for any feedback.
> frosted-aquarius: Handle case where OAuth login fails due to no email provided

- src/models/project.js
- src/state/current-user.js
https://glitch.manuscript.com/f/cases/3328449/odd-behavior-on-the-community-site
Stop using orderKey=userLastAccess and do the sort locally. Old projects (seemingly before March 2019, so not that old) don't have userLastAccess set, so it ends up looping the requests once it tries to make a request with `?lastOrderValue=&`. This sorts locally, using the lastAccess field for projects without a userLastAccess field. (Projects with userLastAccess are always put before projects without it)
> Superb guide: Sort projects locally instead of using the api sort

- src/presenters/overlays/super-user-banner.js
- src/presenters/pop-overs/project-options-pop.js
* https://bronze-gibbon.glitch.me/
* https://glitch.manuscript.com/f/cases/3328450/n-permissions-is-undefined
* and somewhat related to https://glitch.manuscript.com/f/cases/3328449/
* don't start filtering through the permissions array if it doesn't exist. I had originally made the assumption that the permissions array existed always on every project, but this is not the case. I see this on the search page if you click on a project's dropdown arrow to add it to collection the site breaks 😭 because there is no permissions array there. I believe this is because of how we load projects on the search page vs the user page, I had made the assumption that these 2 pages had similarly shaped projects, but they do not have permissions here. Potentially you should be able to delete a project from …
> Bronze gibbon: Fix dropdown permissions on search page, and super user bug fix

- src/presenters/includes/dev-toggles.js
Turn algolia search flag on by default.
if all goes well, a future PR will remove the non-algolia search code.
> Strong duchess: enable algolia search for everyone

- src/components/search-form/autocomplete.js
- src/components/search-result-cover-bar/index.js
- src/models/user.js
- src/state/search.js
* Remix link: https://important-alfalfa.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328451/Lots-of-missing-cover-images-are-resulting-in-404s-on-search-results-pages
* look for hasCoverImage & hasAvatarImage in search results instead of relying on defaultSrc in images
* search for "react" using the search bar
* users, teams, & projects in autocomplete results should have custom avatar images
* there should be fewer network errors in the console than on production
* view the search results page
* users, teams, & projects in autocomplete results should have custom avatar images
* some users and teams should have custom cover image previews
* there should be fewer network errors in the console than on production
* note that images _may_ still 404 and show the default …
> Important alfalfa: avoid unnecessary 404s in search result images

- src/curated/featured.js
- src/presenters/pop-overs/sign-in-pop.js
* Remix link: https://hail-dungeon.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328424/move-TOS-Privacy-notice-in-sign-in-pop-over-to-above-buttons
* Moved TOS & Privacy statement message to above sign in buttons based on nkasi's request (to help ensure users see it before they log in)
> Hail dungeon: Moved TOS & Privacy Statement in Sign-in-Pop

- src/components/buttons/segmented-buttons.styl
- src/components/inputs/text-input.styl
- src/presenters/pop-overs/add-project-to-collection-pop.js
* Remix link: https://lemon-molecule.glitch.me/~lemon-molecule
* Manuscript link: https://glitch.manuscript.com/f/cases/edit/3328498/Use-segmented-buttons-to-segment-collections-team-collections-in-add-project-to-collection-pop
* by default, load user collections and load team collections on demand using segmented buttons in `add-project-to-collection-pop` 
Log in and try testing these cases:
* if user has no collections and isn't part of any teams, they should see the default message without any segmented buttons:
* if user isn't part of any teams, they should not see the segmented button toggles:
* if user is part of team(s) but none of the teams have any collections, show segmented buttons + default hint text:
* if user is part of teams that have collections, those collections should …
> Lemon molecule: Add User / Team Toggle to Add project to collection pop

- src/components/animation-container/index.js
- src/components/collection/collection-item.js
- src/components/deleted-projects/index.js
- src/components/project/project-item.js
- src/presenters/pop-overs/collection-options-pop.js
- src/presenters/pop-overs/project-options-pop.js
* Remix link https://faceted-vase.glitch.me
* Manuscript link https://glitch.manuscript.com/f/cases/3328456/
see also discussion in #496
* Manage animations on project & collection items on those items, rather than in the popups that trigger them
* Redesign AnimationContainer to manage its own state & ensure that it's only reacting to its own animation events
* log into https://faceted-vase.glitch.me
* pinning a project should animate with a slide-up
* unpinning a project should animate with a slide-down
* deleting a collection should animate with a slide down
* undeleting a project should animate with a slide-up
> Faceted vase: use AnimationContainer for project & collection popup actions

- src/components/badges/badge.styl
- src/presenters/pop-overs/add-project-to-collection-pop.js
- styles/pop-overs.styl
* [wandering-save.glitch.me](https://wandering-save.glitch.me)
* [Manuscript](https://glitch.fogbugz.com/f/cases/3328305/Add-to-collection-pop-indicate-if-the-project-is-already-in-a-given-collection)
* Spec:
**Project in no collections**
**Project in one collection**
**Project in many collections**
This adds a section to `add-project-to-collection-pop` that lists which collections a project is already included in.
Add a project to a collection
> wandering-save: Show which collections a project is already in

- server/api.js
- server/routes.js
- src/presenters/featured-collections.js
- src/presenters/pages/collection.js
- src/presenters/pages/team-or-user.js
* Remix link: https://subsequent-atmosphere.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328525/Can-t-load-profile-page-for-users-with-in-login
* encode API calls using `by/login`, `by/url`, `by/fullUrl`
* refactor server-side calls to encode in api.js instead of routes.js
* (projects use punycode and cannot actually have non-url characters in their names, and are therefore unaffected by this)
* user with + in name should load: https://subsequent-atmosphere.glitch.me/@justin+test3
* collection belonging to user with + in name should load: https://subsequent-atmosphere.glitch.me/@justin+test3/test-collection
- replace bare API calls with helper functions/resource manager that does all of this for us
> Subsequent atmosphere: encode `+` in API calls

- src/components/collection/collection-item.js
* [deep-liver.glitch.me](https://deep-liver.glitch.me)
* [Manuscript](https://glitch.fogbugz.com/f/cases/3328553/AnimationContainer-onAnimationEnd-is-sometimes-null-if-user-is-not-authorized): `AnimationContainer`'s `onAnimationEnd` is sometimes `null` if user is not authorized
This makes sure `onAnimationEnd` is never `null` in `collection-item.js` when a user is not authenticated
* Visit [a project page](https://deep-liver.glitch.me/~sponcron) while *not logged in*, you should not see any errors in the console
* To reproduce:
Visit [a project page](https://tourmaline-fox.glitch.me/~sponcron) on another remix while *not logged in*, you should see errors in the console (errors are suppressed in production builds so you won't see this on community.glitch.me)
- Is this approach sound?
Would …
> deep-liver: collection-item AnimationContainer fix for un-authed users

- src/presenters/pages/collection.js
- src/presenters/pages/team.js
- src/presenters/pages/user.js
- src/presenters/pop-overs/project-options-pop.js
- src/presenters/user-editor.js
Reverts FogCreek/Glitch-Community#508
something went wrong here, I guess related to a merge commit I think that was resolved incorrectly, I'm seeing issues on the search page, when I click addProjectToCollection
definitely this line at least was wrong, :
```
alternateContent={() => <AddProjectToCollectionPop {...props} togglePopover={props.togglePopover} focusFirstElement={focusFirstElement} />}
```
```
alternateContent={() => <AddProjectToCollectionPop {...props} togglePopover={togglePopover} focusFirstElement={focusFirstElement} currentUser={currentUser} />}
````
but there's more I think too
> Revert "Coconut restaurant: Fixing up Project Options Popovers"

- src/presenters/pop-overs/add-collection-project-pop.js
* Remix link: https://darkened-tilapia.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328546/Cannot-read-property-domain-of-null-in-add-collection-project-pop
* check for presence of result when filtering in add-collection-project-pop
- switch this to using the search API when componentizing this file https://glitch.manuscript.com/f/cases/3328551/Componentize-AddCollectionProjectPop
> Darkened tilapia: check for presence of result in filter

- src/components/header/new-project-pop.js
- src/curated/featured-embed.js
* Remix link https://abaft-side.glitch.me/
* specify that starter projects are being fetched from the production API, so that they can be used on glitch.development (which ordinarily fetches from the dev API)
> Abaft side: specify production api

- src/presenters/includes/team-users.js
* Remix link: https://sideways-sound.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328530/400-error-when-visiting-a-team-page-for-which-current-user-is-only-member
* don't try to fetch users corresponding to a team's invites if there aren't any
* visit https://sideways-sound.glitch.me/@false-troop
* there should be no network error for /users/by/id 
* visit https://glitch.com/@false-troop
* there will be a network error for /users/by/id
* maybe invited team users should be at `/team/by/url/invitedMembers`?
> Sideways sound: don't fetch team invitees if there aren't any

- src/components/banners/super-user.js
* https://workable-salad.glitch.me/
* https://glitch.fogbugz.com/f/cases/3328589/Support-user-toggle-should-display-expires_at-in-the-user-s-timezone
* should show expiration of super user banner in local time
* I downloaded a browser extension that let me mess around with my local time, I got different times that all sounded approximately right to me, I think that is probs the best way. Although you might glean more from [reading the docs on Date objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), I gave it a good effort, but its highly possible I misunderstood something.
apologies I think I made this way more confusing than it needed to be lol! time/timezones always get me, so feel free to let me know if I'm still confused, but …
> Workable salad: fix timestamp in super user banner

- src/components/containers/projects-list.js
- src/components/data-loader/index.js
- src/components/project/project-item.js
- src/components/related-projects/index.js
- src/components/related-projects/styles.styl
- src/presenters/pages/project.js
- styles/pages/project.styl
* Remix link: https://quilted-day.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328586/
* componentize RelatedProjects styles
* use v1 API for fetching projects
* add `fetchMembers` to ProjectItem to allow projects to get their own users/teams
* fix setState leak in DataLoader (see https://twitter.com/ryanflorence/status/1129487337375690752)
* visit https://quilted-day.glitch.me/~community
* there should be a set of related projects from a glitch team
* there should be a set of related projects from someone who has edited community
> Quilted day: componentize RelatedProjects

- src/components/images/image.js
- src/presenters/pages/error.js
* [Remix link](https://cassey-community.glitch.me/)
* [Manuscript link](https://glitch.manuscript.com/f/cases/3328607/All-images-using-Image-component-are-screenreader-invisible)
- no visual changes
* If an image has role = presentation, the alt will be ignored and the image won't be discoverable for screenreaders. See discussion [here](https://fogcreek.slack.com/archives/CB4EHAJ2J/p15584710221992000)
* Can test this by navigating to an image in voiceover; a full accessibility audit is underway though so you can also just trust. :) There shouldn't be any visual changes corresponding to this PR.
> cassey-community: remove role=presentation from Image component

- src/components/fields/optimistic-markdown-input.js
- src/components/fields/optimistic-text-input.js
- src/components/fields/optimistic-wrapping-text-input.js
- src/components/fields/use-optimistic-text.js
- src/components/fields/use-optimistic-value.js
https://glitch.fogbugz.com/f/cases/3328616/Don-t-trim-whitespace-from-the-field-in-useOptimisticText
- useOptimisticText tracks the input value and sends a trimmed copy to the api. If the value sent to the api hasn't changed, then it returns the untrimmed input value.
- I swapped the return order of useOptimisticValue and useOptimisticText, from [value,error,set] to [value,set,error] to be more like useState
Try using the three different types of fields: text inputs, wrapping text inputs (collection name), and markdown areas. They should all still set the values correctly, not cut off whitespace while you are typing, and (excluding markdown) show an error message when empty.
> Profuse tea: Fix text fields trimming the value while you're typing

- src/components/banners/super-user.js
- src/components/banners/super-user.styl
- src/components/buttons/checkbox-button.js
- src/components/buttons/checkbox-button.styl
- src/components/header/index.js
- src/curated/collections.js
- src/presenters/pop-overs/add-project-to-collection-pop.js
- src/presenters/pop-overs/user-options-pop.js
- src/state/current-user.js
- styles/pop-overs.styl
* https://relieved-fox.glitch.me/
* https://glitch.manuscript.com/f/cases/3328257/
* move super user helpers to current user so they are available anywhere we need them for the future
* remove "blue super user banner" which used to only show if your local storage was set a certain way. It was meant to allow super users to toggle their super powers more easily without altering the ui (with the option to hide for live streams). The issue with this approach was that it was tricky to remember how to set up when moving between remixes/devices.
* create a super user checkbox in user-options-pop. This is a permanent button for anyone with the power to turn super user features on/off. It will not show to users who don't have the ability to turn super user powers on/off. 
* try turning your super …
> Relieved fox: remove blue support banner and move it into user-options-pop

- shared/sentryHelpers.js
- Filter `password` out of user objects before sending them to sentry
- Fix a bug where xToken fields got renamed to `\w+Token`
- Preserve whitespace in the json
Copy the filterSecrets function into a js console and run it against some different objects (such as `localStorage['community-cachedUser']`)
> Quixotic-rocket: Filter passwords from sentry logs

- src/components/inputs/text-input.js
* https://glossy-wednesday.glitch.me/
* https://glitch.manuscript.com/f/cases/3328488/
http://g.recordit.co/pQsCdng8tG.gif
* stop spellcheck on email and password inputs. this is annoying because you'd think giving an input a type of email or password would fix this issue, but at least on safari on email inputs it's a no go. I tried passing  autoCapitalization=false (and also "off" and also "none" lol) but it turns out those are already done for you with type=email (as you'd expect!) unfortunately if your email contains your name it runs the spellchecker, which then autocorrects if you have a `.` right after your name (ex: `firstname.lastname@email.com` Fun fact, I also tried just turning off the autocorrect, but that doesn't seem to help.
* try typing in the input field to sign in with …
> Glossy wednesday: fix spellcheck issue on safari on email input

- package.json
- shrinkwrap.yaml
- src/components/containers/grid.js
- src/components/containers/grid.styl
- src/components/containers/projects-list.js
- src/components/containers/projects-list.styl
- src/presenters/collection-editor.js
- src/presenters/pages/collection.js
https://glitch.manuscript.com/f/cases/3328236/API-Reorder-projects-in-collections
- You can drag around projects in collections you have permissions on
- Tab to focus a whole project item, then space, arrow keys to reorder using keyboard
- Try reordering projects in a collection, both with and without a featured project
- Make sure other people's collection pages act as expected
- Make sure other grids of stuff still work in general 🤷‍♂ 
- Projects with notes seem to animate to the wrong position. I can't figure out how to fix it
- I didn't make any changes to project order outside of the collection page. Should previews always show the first three projects, rather than the most recent?
- Draggable project items have their `tabIndex` set to `0`. What should …
> Superb guide: Reorder projects in collections

- src/components/inputs/text-input.js
- src/components/sign-in-pop/index.js
- src/curated/collections.js
* [thundering-verse.glitch.me/](https://thundering-verse.glitch.me/)
The email login input used to show the validation error after the first `onChange`, which was a bit jarring. This updates that input to only show the validation error if the input is _not focused_ and the input is _not empty_.
Type in the email login input, you should only see the validation error if the input is blurred and the email is invalid.
Is this the right place to implement this? Or should this ultimately live in the `<TextInput>` component?
> thundering-verse: only show email login validation error if input is blurred

- src/components/animation-container/index.js
- src/presenters/includes/auth-description.js
- src/presenters/includes/uploader.js
* https://lumpy-wedge.glitch.me/
* https://glitch.manuscript.com/f/cases/3328077/
* added a new error message for when folks hit a firewall
* fixed bug where sometimes users would hit an error and yet still get a notification that their image uploaded, I think because even if you a throw an error in a catch it still proceeds to the finally case (interestingly though I can't figure out how to recreate this without hardcoding in an error so maybe this isn't actually happening in real life).
* capture file upload exceptions with sentry directly, rather than rely on a global catch.
* I added this code in the `try {}` not sure if we have a great way of forcing this particular error we're trying to protect around:
```
let fake = new Error("i'm bad")
fake.status_code = 0
throw fake
```
for …
> Lumpy wedge: improve image upload error handling

- src/components/search-form/index.js
- src/components/search-form/story.js
- src/presenters/pages/search.js
- src/state/dev-toggles.js
- src/state/search.js
* Remix link: https://frosted-hammer.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328648/
* remove algolia feature flag
* remove legacy search
* visit https://frosted-hammer.glitch.me/
* search autocomplete should work
* the search page should include collections
- is there any reason we need to keep legacy search around? eg. as part of our case study with Algolia?
> Frosted hammer: remove legacy search

- src/components/project/embed.js
- src/curated/collections.js
- src/presenters/pages/category.js
* [lavish-laborer.glitch.me](https://lavish-laborer.glitch.me)
* [Manuscript](https://glitch.fogbugz.com/f/cases/3328679/Missing-prop-type-on-Category-pages-like-games)
Make sure all `<Image>` components use an `alt` prop
Go to [/games](https://lavish-laborer.glitch.me/games). You should not see any errors in the console
> lavish-laborer: make sure all Image components use alt prop

- src/utils/sentry.js
* https://full-larch.glitch.me/
* https://glitch.manuscript.com/f/cases/3327840/
* [UC Browser](https://en.wikipedia.org/wiki/UC_Browser) is a very popular browser, which unfortunately behaves very differently from our supported browsers (and has some security issues apparently), until we're ready to support it, it doesn't make much sense to log out the errors to sentry. This pr will [hopefully detect](https://stackoverflow.com/questions/38089868/javascript-how-to-detect-if-the-user-is-using-uc-browser-mini) when a user is using this browser and [not send the bug to sentry by returning null](https://docs.sentry.io/error-reporting/configuration/filtering/?platform=browser). 
* Unfortunately I'm not able to download UC Browser as I've got a mac, I tried a bit with browserstack as it looks …
> Full larch: Do not alert sentry of UC Browser bugs

- src/components/inputs/markdown-input.js
- src/presenters/pages/user.js
* https://peach-countess.glitch.me
* https://glitch.manuscript.com/f/cases/3328640/
* show markdown fields as editable if when their value trimmed has a length of 0. 
* you can see the bug fixed in storybook ^
* you can also see this on the user profile for descriptions and for collection descriptions
- debating if we should trim on blur so it shows the placeholder text instead. what do y'all think? looks like we trim values when we display them, so it's not like we're letting users have weird spacing as descriptions? Then again it might be kind of annoying to have trims happen when you blur if you're not expecting it? Like if I type "blah blah " and then navigating away to copy some text to then paste in and the last space after the blah is removed it'll be "blah blahpastedText" instead …
> Peach countess: fix collapsing markdown inputs

- src/components/buttons/button.js
- src/components/deleted-projects/index.js
* https://halved-belief.glitch.me/
* https://glitch.manuscript.com/f/cases/3328582/
* currently when you look at your deleted projects it's fairly likely you'll see projects there you can't actually undelete despite seeing the button. As an example if I am invited to join a project I can't delete it because I'm not an admin. Similarly I can't undelete it, if I try I get a 401 error. This removes the button from rendering on those projects. 
* join a project as a non admin, have the admin delete it, notice you can see it under deleted projects on your user page but you can't undelete. (if you want me to invite you to a project and delete it for testing purposes slack me :)) 
- seem good?
> Halved belief: don't see undelete button if you can't undelete

- src/presenters/user-editor.js
This is handled at the API now, so it's not necessary to do in the client.
* https://glitch.manuscript.com/f/cases/3328503/
* Removes code that's unnecessary now
* Delete a project, then undelete it and see that it gets renamed to not include the -deleted suffix.
> Remove code that renames a project on undelete 

- src/components/collection/defaultAvatar.js
- src/components/link/index.js
- src/presenters/featured-collections.js
- src/presenters/includes/collection-avatar.js
* https://long-museum.glitch.me
* https://glitch.manuscript.com/f/cases/3328691/Link-text-for-collection-avatar-should-be-collection-name-not-url-slug
* Before when you navigated to the homepage and used a screenreader on featured collections it would read out the collection avatar as the href to the collection, which is hard to hear. I've added some text that is only accessible with a screenreader so that when you tab through it reads out the name of the collection
* I used chrome and voiceover and it seemed to work ok! Feel free to do your own better testing tho!
- anything I might be missing?
> Long museum: collection avatar a11y improvement

- src/components/search-results/index.js
- src/components/team/team-item.js
- src/state/search.js
* https://chain-cut.glitch.me/search?q=Computing%20Corner&activeFilter=all
* https://glitch.manuscript.com/f/cases/3328671/
* Previously when you went to https://glitch.com/search?q=computing-corner and clicked on the team with the pink default avatar it'd error out (it also through an error in the console about proptypes in remixes. This was because our search results are out of date with our database for some reason. We have a ticket to deal with the underlying issue: https://glitch.fogbugz.com/f/cases/3328672/Collection-project-count-is-wrong-in-search-results#BugEvent.21314743 but I figured it'd also be nice to ensure we don't display dead links. 
* I also put some error handling in our user fetching as I noticed we were setting .users to an error rather than an empty array. 
* look …
> Chain cut: handle teams without urls

- src/state/search.js
* https://oceanic-aquarius.glitch.me/
* go to https://oceanic-aquarius.glitch.me/ and try to use a popover search (like adding a project to a collection, or adding a person to a team) search for something see that it works as opposed to on prod where it doesnt 😭
> oceanic-aquarius: only filter teams for bad data if you're searching for teams

- src/components/collection/collection-item.js
- src/components/collection/collection-item.styl
* Remix link: https://coordinated-cauliflower.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328713/
* if no projects in collection, don't render "view all projects" button at all
* update css accordingly
* visit https://coordinated-cauliflower.glitch.me/~modernserf
* the collection linen-collection should only have one focusable element (the header)
* the collection flannel-collection should have a focusable header, project names, and view all projects link
> Coordinated cauliflower: collection item button

- src/components/collections-list/more-collections.js
- src/components/containers/grid.js
- src/components/containers/grid.styl
- src/components/containers/projects-list.styl
- src/presenters/collection-editor.js
- src/presenters/pages/collection.js
- src/presenters/pages/project.js
* https://superb-guide.glitch.me/
- Added a prompt to the bottom of collections with more than one project explaining how to reorder, not happy with the wording
- Reworked some css to get rid of an `!important` I added during a deploy yesterday
- The empty collection check was broken, so the prompts weren't visible, this brings them back
- Project page 'in collections' area shows the first three projects in the collection. user/team pages still don't because they use the old api to load collections
- Can you figure out how to reorder a collection without a mouse based on that prompt?
- Do the empty collection messages show up in the right situations?
- The reorder prompt is there to indicate how to do so to people not using a mouse, since there's no real way to discover it on your own. …
> Superb guide: collection reorder prompt + minor css cleanup + empty collection fixes

- src/components/recent-projects/index.js
* Remix link: https://lunar-front-1.glitch.me
* Manuscript link: https://glitch.manuscript.com/f/cases/3328727/
* add visually hidden "Your profile page" text to user avatar link
* make arrow in "Your projects" hidden to screen readers
* log into https://lunar-front-1.glitch.me
* check the link around the user avatar
Is this the text I should use for this link?
> Lunar front 1: add accessible label to user profile link in recent projects

- src/presenters/featured-embed.js
- styles/includes/featured.styl
* Remix link: https://chip-petalite.glitch.me/
* Manuscript link: https://glitch.manuscript.com/f/cases/3328728/
* make (purely decorative) linked image clickable but non-tabbable
* make the whole embed text a single link
> Chip petalite: consolidate links on featured embed

- src/components/team-users/team-user-info.js
* [automatic-hacksaw.glitch.me](https://automatic-hacksaw.glitch.me)
* [Manuscript: Out-of-place gray background when hovering team member avatars](https://glitch.fogbugz.com/f/cases/3328732/)
* [Meg's report that user avatars in team-user-info-pop no longer link to user pages](https://fogcreek.slack.com/archives/CB4EHAJ2J/p1560457647138800)
**Before**
* Uses a `<TransparentButton>` to get rid of hover background on avatar button
* Wrap `<UserAvatar>` in a `<UserLink>` 
* Hover a user avatar on a team listing. There should not be a background.
* Click the avatar to open the pop. Click the avatar inside the pop. It should take you to their user page.
> automatic-hacksaw: fix team-user-info avatar link and hover state

- server/webpack.js
- src/app.js
- webpack.config.js
- https://nova-chance.glitch.me/
- https://glitch.manuscript.com/f/cases/3328664/The-the-site-is-not-ready-yet-page-doesn-t-work
- Delete the stats.json file on webpack startup so the site knows that there isn't any build output ready
- Don't wipe the storybook build when webpack/the server gets restarted
- Bumped prod webpack memory from 384mb to 512mb, because it was crashing sometimes when I made a local change. This means that non perf-boosted projects are more likely to get limited, but only if they're running in dev mode.
Join the project via perf boost and run `refresh` in the console. It should show the not ready page, and storybook should stay built. Changing a js file should also keep storybook around.
Why was stats.json excluded from cleanup?
> Nova chance: Fix the project is still building page

- src/components/containers/projects-list.js
- src/curated/collections.js
- src/presenters/pages/user.js
* [sweet-ethernet.glitch.me](https://sweet-ethernet.glitch.me)
This removes `{...props}` from an `<article>` DOM element. I think this is leftover from refactoring, we shouldn't need to pass props to a native DOM element, and it was throwing a console error that you can see at [lavish-laborer.glitch.me/@glitch](https://lavish-laborer.glitch.me/@glitch)
Open [sweet-ethernet.glitch.me/@glitch](https://sweet-ethernet.glitch.me/@glitch), you shouldn't see any errors in the console
Does this unexpectedly break anything? Is there actually a good reason to pass `props` to DOM elements?
> sweet-ethernet: don't pass props to DOM elements

- webpack.config.js
stats.json only includes the assets from the last build by default, so if you do an incremental build then restart the project it'll lose some of the built js. This tells it to include unchanged output in stats.json
Test by waiting for a build to finish, making a old styles change (so it does a partial rebuild) then refresh in the console and browser. On other remixes it will fail to load if the site isn't cached, here it will load
> Nova-chance: Fix a bug with project restarts

- src/presenters/pages/router.js
- src/presenters/pages/signin.js
- src/presenters/pages/signin.styl
* Remix link: https://chestnut-cappelletti-1.glitch.me/
* Adds OAuth sign in page back to routes
* https://chestnut-cappelletti-1.glitch.me/signin should show the sign in popup.
This kind of reuses the VSCode auth page and the `sign-in-pop` to get it put back quickly and also to minimize conflicts with upcoming changes Greg and I made to sign in.
There was a note about previously supporting email sign in only, which is mainly because it feels weird to sign in with another OAuth provider from our OAuth screen? I think some of the work in our other PR will make it easier to have things that are modular like this if we want them to be.
Once that PR is merged I will probably revisit this to use some of the work we've done there.
> Chestnut cappelletti 1: Add OAuth page back

- package.json
- shrinkwrap.yaml
- src/polyfills.js
* https://sedate-pancreas-1.glitch.me/
* https://glitch.manuscript.com/f/cases/3328763/Teams-pages-won-t-load-in-Safari-desktop-or-mobile-Intersection-Observer-API-not-supported-in-safari-before-March-2019
* adds a polyfill for intersection observer, should resolve this issue from sentry: https://sentry.io/organizations/fog-creek-software/issues/1076155283/?project=1246508&referrer=slack
* use browserstack to open a version of safari that is older than 12.1 (which was released back in march)
* notice on glitch.com we show an error but on https://sedate-pancreas-1.glitch.me/ the site loads
> sedate-pancreas-1: add polyfill for intersection observer

- src/components/containers/cover-container.js
- src/components/containers/profile/team.js
- src/state/team.js
- src/state/user.js
- https://quixotic-rocket.glitch.me/
- https://glitch.manuscript.com/f/cases/3328758/On-anonymous-user-s-page-user-_cacheCover-is-not-provided-though-marked-as-required
Removes all references to _cacheCover and _cacheAvatar, which were used to cache bust images on profile pages. They were set to the current datetime on page load and updated whenever the image updated. Now it uses updatedAt, which means images can be cached across page loads.
- Try updating avatars and cover images for users and teams
> Quixotic-rocket: Replace _cacheCover with updatedAt

- src/components/collection/collection-item.styl
* Remix link: https://useful-bangle.glitch.me
* fix small collection item styes
* verify small collection items don't overlap on https://useful-bangle.glitch.me/search?q=react&activeFilter=collection (compare with production)
* verify that collection items in "more from glitch" fill the whole container on https://useful-bangle.glitch.me/@glitch/glitch-this-week-june-19-2019
> Useful bangle: fix small collection item styles

- src/components/collection/create-collection-pop.js
* https://quixotic-rocket.glitch.me/
* https://glitch.manuscript.com/f/cases/3328794/Creating-a-new-collection-on-a-team-page-redirects-to-a-broken-url
* Use `team.url` instead of `team.name`
* Go to a team page with a space in their name, and create a collection
> Quixotic-rocket: Fix create collection on team pages with a space in their name

- src/components/images/avatar.js
* [aromatic-mushroom.glitch.me](https://aromatic-mushroom.glitch.me)
Adds a size prop to the TeamAvatar component so we can also fetch higher-res avatars
Do we still have team avatars across the site?
> aromatic-mushroom: add size prop to TeamAvatar

- src/components/collection/collection-item.js
- src/components/collection/note.js
* https://regular-muscle.glitch.me
* https://glitch.manuscript.com/f/cases/3328797/user-avatars-not-rendering-on-notes
before and after
* make sure we load full users for collections and pass that to notes
* go to any notes with collections and ensure the user avatars load properly
- I see we have 2 CollectionCuratorLoaders and wasn't sure which to use, but this one seems to do the trick? Should I just pass CollectionCurator instead of the loader?
> Regular muscle: show user avatars on collection notes

- src/components/related-projects/index.js
- src/presenters/pages/project.js
* https://rambunctious-bathroom.glitch.me/~face-the-music
* https://sentry.io/organizations/fog-creek-software/issues/1087738883/?project=1246508&query=is%3Aunresolved
* we have a collection that doesn't seem to have a user or a team. I'm not sure how it got into this abandoned state, but imo there's no need to show when projects are included in abandoned collections, and currently in prod it's breaking certain project pages, for an example see ~face-the-music
* I also noticed that sometimes we had these More by links for users/teams that only have one project. I'm not sure it makes much sense to show those links in this case (but feel free to disagree! wasn't sure if this was an actual bug or as designed tbh) 
* compare https://rambunctious-bathroom.glitch.me/~face-the-music with …
> Rambunctious bathroom: bug fixes for project page

- src/components/buttons/button.styl
- src/components/project/featured-project.js
- src/components/project/project-embed.js
- src/presenters/pages/project.js
- stories/index.js
* https://profuse-tea.glitch.me
* https://glitch.manuscript.com/f/cases/3328757/Edit-Project-button-is-visible-for-featured-projects-even-if-you-aren-t-a-member-of-the-project
* Project embeds check if you are a project member rather than relying on collection/team level auth. This means if you feature someone else's project in your collection, you'll see a report button under it instead of an edit button, and the remix button will say 'remix your own' instead of 'remix this'
* I added `vertical-align: middle` to the button component. It was already applied by an old css `button, .button` selector, so this fixes alignment when there are button buttons next to link buttons.
* Try looking at a bunch of different collections and see if they all behave
* See if there are any obscure buttons …
> Profuse tea: Don't show 'edit project' on featured projects you are not a member of

- src/presenters/pages/project.js
- src/presenters/pages/project.styl
* Remix link: https://little-health.glitch.me
Before:
After:
* set input width to 100%
* log into https://little-health.glitch.me
* visit a project you own
* the public/private toggle should be inside the container
> Little health: fix input css

- src/components/images/emoji.js
- src/presenters/pages/index.js
- styles/globals.styl
* Remix link: https://prickly-swim.glitch.me/
* restore global button styles (e.g. font size, alignment) that were being implicitly depended on by some buttons
* fix play button on home page
* visit https://prickly-swim.glitch.me/
* verify the 'how it works' button renders correctly
* log in
* verify popover navigation menus render correctly
> Prickly swim: fix default button styles

- sh/merge.sh
- src/presenters/pages/home-v2/index.js
- src/presenters/pages/home-v2/styles.styl
* Remix link: https://brief-shrimp.glitch.me/
* fix spacing on popover sections
* add home CMS updates to merge.sh
* visit https://brief-shrimp.glitch.me/
* click on "report abuse" near the bottom of the page
* the popover should be styled correctly
> Brief shrimp: fix popover css

- src/presenters/pages/create.js
* [steadfast-ticket.glitch.me/create](https://steadfast-ticket.glitch.me/create)
* [GitHub issue](https://github.com/FogCreek/Glitch-Community-Work/issues/113)
Get rid of Visibility container, in this case it doesn't help much with initial load time anyway, and it was causing the page to jump.
Open /create. You shouldn't see starter content jumping around.
> steadfast-ticket: don't use VisibilityContainer on /create

- src/components/collections-list/more-collections.js
- src/components/create-team-pop/index.js
- https://quixotic-rocket.glitch.me/
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/42
- Use the new collection curator loader to make sure that we have a name for the collection owner
- Reuse create team validate debounce across renders so it doesn't hit the api every kesytroke
- Look at some collections owned by users and teams and make sure they both have correct titles
- Try typing into the create team pop and watch the network tab
> Quixotic rocket: Fix 'more collections by' display

- src/state/api.js
https://superb-guide.glitch.me
https://glitch.fogbugz.com/f/cases/3328590/The-domainChanged-endpoint-doesn-t-support-OPTIONS
The domainChanged endpoint supports OPTIONS requests, so we don't need to jump through a hoop to avoid sending it headers.
Try renaming a project and check for network errors
> Superb-guide: Remove a workaround that isn't needed any more

- src/components/sign-in-pop/index.js
- src/state/current-user.js
- Adds a little whitespace to the email sign in pop between the title and the emoji
- If a call to a useDebouncedAsync-ed function is blocked, it'll be flagged so the function gets called again when it finishes. This fixes an occasional issue where a user isn't fully loaded after using the console to write their token to localstorage
Run `localStorage.cachedUser = JSON.stringify({ persistentToken: "TOKEN" })` in the console and refresh the browser. On glitch.com it'll only partially load your user (evidenced by a missing resume coding button). This happens most consistently on pages without embeds. On profuse-tea it'll consistently load everything.
> Profuse tea: Fix a race condition in user loading

- src/components/project/embed.js
- src/curated/embed.js
* cassey-community.glitch.me
* FogCreek/Glitch-Community-Work#100
* Change order of params on `iframe` which more consistently causes all the parameters we're passing in to appear. 
* I have no idea why this works - order of params should not make a difference at all
* Changes so if we ever use curated/embed.js we are setting the accessible name correctly. I _think_ that file isn't being used for anything now, though. 
* Go to embeds on create page (homepage when logged in). Verify that they have the `title` attribute set. 
* Go to an embed on a project page. Verify that it looks normal and has the `title` attribute set.
WHY??
> Cassey-community: fix title on create page for embeds

- src/components/collection/collection-item-small.js
- src/components/collection/collection-item.js
- src/components/collection/collection-item.styl
- src/components/collection/container.js
- src/components/collection/container.styl
- src/components/collection/edit-collection-color-pop.js
- src/components/collection/note.js
- src/models/collection.js
- src/utils/color.js
- src/utils/constants.js
- src/utils/sentry.js
- https://superb-guide.glitch.me/@gregs-test-team-1/zany-playlist
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/135
- Export the current env from utils/constants.js, and use it in utils/sentry.js rather than the removed window._env
- Moved generic color checking functions from models/collection.js to utils/color.js
- Collection items now have a .dark class like collection pages, rather than using inline styles
- Code blocks in dark collections use a dark background so the white text is legible
- Check out the collection and make sure it is easy to read
- Force a sentry error and make sure beforeSend doesn't break
> Superb guide: Fix globals use in sentry, move collection color functions into utils/color

- src/components/popover/container.js
- src/components/popover/index.js
* https://github.com/FogCreek/Glitch-Community-Work/issues/148 (see issue for context on how this is useful for accessibility - basically, it's to prevent an unexpected change in context for users navigating with the keyboard
* adds a prop to popover container for a ref to the button that is used to open the popover; if that prop is passed in, it's used to set focus back to said button when the popover is closed
* open a popover basically anywhere on the site (both with keyboard and by clicking the button). Close it by clicking outside the popover; it should work normally. Close it by pressing the escape key; keyboard focus should return to the button you used to open the popover
Is the ref passing around as clear as it could be?
> Foregoing-spell: move focus back to popover-opening-button after a popover is closed with keyboard

- src/components/text/markdown.js
* [plastic-climb.glitch.me](https://plastic-climb.glitch.me)
Use `<span>` to wrap markdown content when `renderAsPlaintext` prop is used. The markdown component was [recently updated to wrap content in a `<div>`](https://github.com/FogCreek/Glitch-Community/commit/6ae6f63bd97a38f125442a2b5ccf20cccf091343#diff-3ce29a4a8845380d9e81b6e2533f5854), because `<p>`s and other things can't be descendants of `<span>`s.
But when we use the `renderAsPlaintext` prop, we often put that rendered markdown string in a `<p>`, and a `<div>` can't be a descendant of a `<p>`
- Visit [/create](https://plastic-climb.glitch.me/create) and open the console. You shouldn't see any errors in the console
- Test out markdown elsewhere, it should still work
- [Olivia's …
> plastic-climb: fix Markdown component HTML validation

- src/components/collection/collection-options-pop.js
- src/components/project/project-options-pop.js
* [issue](https://github.com/FogCreek/Glitch-Community-Work/issues/177) 
Before: 
After: 
* Added non-default labels (default is just 'options') to project options pop buttons and collection options pop buttons
* Check the accessible name of a project options dropdown arrow, make sure you see the project name as part of the label.
> Foregoing-spell: more descriptive labels for collection & project options dropdowns

- src/components/tooltips/tooltip-container.js
* https://cassey-community-2.glitch.me/
* https://github.com/FogCreek/Glitch-Community-Work/issues/150
* When a tooltip is showing, user can dismiss it without moving the mouse by pressing the escape key
* open a tooltip, dismiss it
* any unexpected consequences of this?
> Close tooltips with escape key

- src/state/notifications.js
- src/state/uploader.js
https://github.com/fogcreek/glitch-community-work/issues/181
- Don't try to spread an object parameter that is potentially not there
- Error notifications default to using the error styling (appear red not purple)
- Asset upload success notification is green rather than purple
Try forcing some errors (easiest way is to check the offline box in chrome's network tab)
I haven't been able to reproduce the sentry error, but `console.log(...undefined)` throws
Were either of those two color changes intentional?
> Superb-guide: Fix invalid attempt to spread... + some notification regressions

- src/components/link/index.js
- src/state/globals.js
Use withRouter to map urls relative to the current url and not just the origin
TODO in a separate pr: make our own `useRouter()` thing so we don't have to mess around with HOCs
> Quixotic rocket: Fix link components using hash/relative urls

- package.json
- server/routes.js
- server/server.js
* Issue-tracker link: n/a
* If the env variable RUNNING_LOCALLY is set, don't enforce HTTPS. This enables local development (on your machine vs on glitch.com) without code changes that could get accidentally committed
* Try going to a http version of foregoing-spell, you should get redirected to https
* Run `RUNNING_LOCALLY=true node server/server.js` in your local development environment if you have one. You should be able to go to localhost and see the site running. (Without setting the env variable, you'd get redirected to `https://localhost` and told that your connection wasn't secure, therefore you couldn't connect. 
* Any considerations for why we shouldn't do this that I'm overlooking?
* Any possible way this will break sitemaps?
> Only enforce https if not running locally (based on env variable that doesn't exist on glitch.com containers)

- src/utils/constants.js
Marked @GregWeil as reviewer since we've already discussed the root issue.
* Remix link: https://osmose-community.glitch.me/
* Issue-tracker link: None
* Specs/doc links: None
The backend development setup runs a proxy to the production instance of the
community site, and expects the community site to detect that it is running
under the glitch.development hostname and make API requests to
api.glitch.development. Prior to this fix, the RUNNING_ON environment varible
overrode this hostname detection and made requests to the production API even
when running under the glitch.development hostname.
This updates the existing logic so that the RUNNING_ON environment variable
doesn't override the hostname detection that the backend dev setup expects.
Testing that the site works as expected should …
> Prioritize the hostname for determining environment-specific constants.

- src/components/search-form/index.js
- src/presenters/pages/search.js
* [bodega-boys.glitch.me/search](https://bodega-boys.glitch.me/search)
* [#233: queries on /search aren't URL-encoded](https://github.com/FogCreek/Glitch-Community-Work/issues/233)
* URL-encode search queries in query strings on [/search](https://bodega-boys.glitch.me/search)
* Enter a search query with a special character like `&`, `+` or `/`, the character should be URL-encoded
* Refresh the page, things should still work
* Click a result type tab, things should still work
> bodega-boys: make sure search queries are URL-encoded

- FAQ.md
* [ninth-winter.glitch.me](https://ninth-winter.glitch.me)
* Document how to run the app locally
> ninth-winter: add documentation about running ~community locally

- src/state/collection.js
https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/246
Use `orderKey=projectOrder` when loading collection projects so they stay in the user defined order
Try reordering some projects in a collection, then refresh
> Superb-guide: Load collection projects in order

- src/state/team.js
https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/247
The remove from team button went missing, but now it is back!
Try removing a project from a team
> Nova-chance: Restore the remove project from team button

- src/models/collection.js
- src/presenters/pages/collection.js
https://nova-chance.glitch.me
https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/198
- getCollectionLink builds the url from the user/team name and url if possible, before using the fullUrl
- Don't use react-router's history to update the url, because it will trigger a data load and page rebuild
- Go to a collection and change the name. The window title, url, and text field should all update with whatever you typed in. The collection should also still load after a refresh
- Click links to collections from elsewhere around the site, they should all still work
> Nova chance: Prefer to build collection urls over fullUrl, fix collection page renaming

- src/components/images/avatar.js
- src/components/images/avatar.styl
- src/components/popover/styles.styl
- src/components/project/add-project-to-collection-pop.js
- src/components/project/popover.styl
- src/components/user-options-pop/index.js
- src/components/user-options-pop/styles.styl
- src/presenters/pages/team.js
https://quixotic-rocket.glitch.me/@glitch
- Split the emoji out of the title on team page pinned projects
- Fixed the size of the project avatar in the add project to collection pop
- Use TeamAvatars in the user options pop rather than Image
Look at both of those things and see that they are the same or better
Both `size` and `type` already have meaning for avatars, so I opted for a boolean `tiny` prop. Should avatars support every size they get rendered at?
> Quixotic rocket: Fix add to collection title styling, fix a proptypes warning

- FAQ.md
- server/server.js
- src/server.js
* [charming-memory.glitch.me](https://charming-memory.glitch.me)
* Open `http://localhost:123whatever` in the default browser when`RUNNING_LOCALLY` is set.
* Pull this branch
* Run the app locally ([instructions](https://github.com/FogCreek/Glitch-Community/blob/master/FAQ.md#can-i-run-this-app-locally))
* Running `npm start` should open the app in a new tab in your default browser
* Is this helpful or annoying?
* @oliviacpu is this going to cause problems on CircleCI?
> charming-memory: open the app in default browser if `RUNNING_LOCALLY` is set

- src/components/project/featured-project.styl
* [periodic-weeder.glitch.me](https://periodic-weeder.glitch.me)
* [#204](https://github.com/FogCreek/Glitch-Community-Work/issues/204)
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
View the [Material starter kits collection](https://periodic-weeder.glitch.me/@material/material-starter-kits). The note on the featured project should not overflow.
> periodic-weeder: Fix overflow of note on featured project

- src/components/collection/add-collection-project-pop.js
- src/components/collections-list/index.js
- src/components/containers/results-list.js
- src/components/pagination-controller/index.js
- src/components/popover/search.js
- src/state/team.js
https://nova-chance.glitch.me
- https://github.com/FogCreek/Glitch-Community-Work/issues/226
- https://github.com/FogCreek/Glitch-Community-Work/issues/230
- https://github.com/FogCreek/Glitch-Community-Work/issues/229
- Clear the project member cache when adding/removing projects from teams, so that the team avatar shows up correctly without needing a refresh
- Provide onSubmit in the add project to collection pop so that the proptypes warning goes away
- Fixed result item highlighting when using the arrow keys to navigate search results
- Fixed using the enter button to select a search result selected using the arrow keys
- Use the underlying function rather than the useCollectionProjects hook to preload the next page's projects so react doesn't get upset when you reach the last page
- …
> Nova chance: A few fixes for collection and team pages

- src/components/tooltips/tooltip.styl
* https://feline-bail.glitch.me/
* https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/297
before:
after:
* fix the "new stuff" arrows, I recently [made a change to tooltips](https://github.com/FogCreek/Glitch-Community/pull/798) to fix one bug but sadly created this one in the process. I think this should fix it. 
* sign in to the remix and see that the arrow part of the tooltip looks good, briefly check other tooltips to ensure they also look good.
> fix borked new stuff tooltip

- src/client.js
- src/components/header/index.js
- views/index.ejs
https://github.com/FogCreek/Glitch-Community-Work/issues/190
- If js is disabled prefer to show the server rendered page over the no js error page
- If running in google translate ( https://translate.google.com/translate?hl=&sl=auto&tl=fr&u=https%3A%2F%2Fsuperb-guide.glitch.me%2F ) only redirect out if not server rendered
- The new project/sign in buttons wait until you have an anon user (aka rendering in the browser)
Load up the site and check the homepage and a non ssr page
- In a modern/supported browser
- With js disabled (you can do it from dev tools > settings > advanced in ff)
- In google translate
- Are there any dangers to leaving the ssr content visible in these two cases? Anything interactive won't work but navigating around the site should be …
> Superb guide: Use the server rendered page instead of the fallback in some cases

- src/components/video/index.js
* [jolly-hardboard.glitch.me](https://jolly-hardboard.glitch.me/)
* [#293](https://github.com/FogCreek/Glitch-Community-Work/issues/293)
Updates `<Video>` component to set `playsinline` attribute if `autoPlay` prop is set.
Visit [/create](https://jolly-hardboard.glitch.me/create), the autoPlay videos should have the `playsinline` attribute
> jolly-hardboard: make autoplay videos work on iOS Safari

- server/proxy.js
- src/presenters/pages/home-v2/index.js
* Remix link: https://dramatic-haddock.glitch.me
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/301
* proxy `community-home-editor.glitch.me` as `/index/edit` 
* sign into https://dramatic-haddock.glitch.me
* visit https://dramatic-haddock.glitch.me/index/edit
* you should be able to use the community home editor without logging in again
* your edits should be reflected in https://dramatic-haddock.glitch.me/index/preview
> Dramatic haddock: proxy community home editor

- src/components/collection/collection-item.styl
- src/components/text/markdown.styl
* https://garrulous-season.glitch.me/@sarahzinger
* Ihttps://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/130
* change the styling of links to match what we have on the collections page to make it more clear to users that they are links.... although I'm wondering if we should add text underline even without hover? or just remove the linkified text altogether because putting links in links is a weird experience. 
* check out a collection description on a user page that has a link in it like "my collection" here: https://garrulous-season.glitch.me/@sarahzinger
whatcha think? it's a small fix, but now I'm doubting my own solution for it tbh.
> Garrulous season: styling links in collection descriptions

- src/components/search-results/index.js
- src/state/project-options.js
* Remix link: https://west-foam.glitch.me/search?q=react&activeFilter=project
* Issue-tracker link: https://sentry.io/organizations/fog-creek-software/issues/1146512614/?project=1246508&query=is%3Aunresolved&statsPeriod=14d
* get projects in a single request instead of multiples (no more 429 errors)
* use id instead of domain (I think original error is caused by search results returning projects that have been renamed, and therefore cannot be found under the previous name)
* don't mutate the project data
* use `createAPIHook` (has error handling built-in)
* log into west-foam.glitch.me
* enable My Stuff
* search for a project that's in your My Stuff collection
* that project should indicate that you have collected it
* depending on how big people's My Stuff collections are vs how much we …
> West foam: better handling of My Stuff on search results page

- views/index.ejs
* Remix link: https://kaput-aftermath.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/309
* change react root element id from "main" to "react-root"
* visit https://kaput-aftermath.glitch.me/
* pressing tab should focus a previously hidden button reading "Skip to Main Content"
* pressing space should move the page focus and scroll position to the page's content
* pressing tab again should select the first button or link on the page's main content, skipping the header
> Kaput aftermath: fix main element

- src/components/collection/collection-result-item.js
* Remix link: https://happy-cobra.glitch.me
* we decided during qa the description is needed after all
* go to https://happy-cobra.glitch.me/secret
* click my stuff
* login
* go to any project and try adding it to a collection, you should see the description.
> add back descriptions to my stuff in add to collection popover

- package.json
- server/constants.js
- shared/constants.js
- webpack.config.js
We are going to make it possible to work on the API locally (without a full dev backend) and point a community remix at it to test against. The other half of this work is in [this infra repo pull](https://github.com/FogCreek/Glitch/pull/1707).
* Remix link: https://far-cushion.glitch.me/
* Issue-tracker link: in infra ZenHub [here](https://app.zenhub.com/workspaces/glitch-infrastructure-5d2db407bc23971a08b9fe2a/issues/fogcreek/glitch/1655)
Here is viewing a project on a remix:
Here are the local server logs of it being loaded:
* Add a "local" value for the `RUNNING_ON` environment variable. It tells the server and client to use the API URL that will be generated by the SSH tunnel on the infrastructure project side.
* Default to the project name, if it's not there (maybe we are running …
> Community-side setup for targeting local API server instances (far-cushion)

- src/components/profile-list/index.js
* https://coordinated-tracker.glitch.me/
* FogCreek/Glitch-Community-Work#225
* Tooltips for user/team avatars should appear on focus
* this was broken because focus lands on the link but the tooltip target was the inner image. We need the tooltip wrapping the thing that receives focus, aka the link. So, we can't use the tooltip container built in to the Avatar component. 
* Glitch team avatars, for projects marked as 'show as glitch team', should link to the glitch team page and have a tooltip for consistency with the rest of the team links
* Tab around glitch.com looking at tooltips on user & team avatars 
* Hover/blur on user/team avatars; that should also still make the tooltip appear & disappear
* press the escape key when a tooltip is showing; that should still make the tooltip go …
> Coordinated-tracker: tooltips on user/team avatars should appear on focus

- src/components/buttons/bookmark-button.styl
- src/components/project/featured-project.js
* Remix link: https://slash-second.glitch.me 🔪 🕐 
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/329
* always show bookmark button on devices that don't have a hover (phones/ipads, etc) rather than based on screen width, realized in a11y testing that putting my phone on landscape mode makes the bookmark buttons undiscoverable lol. I'm curious if there's anywhere else we might want to consider doing this, couldn't think of any of the top of my head. 
* added a tracker around the bookmark button from the featured project embed, realized that got lost in the shuffle somehow. Added a modified origins so it'll show it's come from the user or collection page, but specifically from the featured project section and …
> Slash second: more my stuff bugs

- src/components/profile-list/index.js
- webpack.config.js
* [jazzy-packet.glitch.me](https://spiny-wire.glitch.me)
lol
🔢 Look! The line numbers aren't grayed out! You can set breakpoints again!
Use `eval-source-map` in dev mode instead of `cheap-module-source-map` because `cheap-module-source-map` is broken af when used with babel. I don't have time to fully understand why, but if you're interested to learn more, see [create-react-app/pull/4930](https://github.com/facebook/create-react-app/pull/4930) or [fusion-cli/pull/758](https://github.com/fusionjs/fusion-cli/pull/758) or [webpack/issues/8302](https://github.com/webpack/webpack/issues/8302)
Using `eval-source-map` will make initial builds slower, but not by much (2-3 min total), and should make rebuilds a bit faster.
* Open the debugger, use `CMD-p`/`Ctrl-p` to open a file like …
> jazzy-packet: fix source maps in development mode

- src/components/profile-list/index.js
- src/components/search-form/index.js
* Remix link: https://successful-geology.glitch.me/
* add a 500ms debounce before making algolia searches
* fix lint error
* visit https://successful-geology.glitch.me/
* throttle your bandwidth to "Fast 3G" in the "Network" tab of the inspector
* use the search autocomplete
* typing in the search box should have no noticeable latency
* the search results should update only after you have stopped typing
> Successful geology: debounce search results from search input

- src/components/project/project-options-pop.js
- src/state/team.js
https://github.com/FogCreek/Glitch-Community-Work/issues/330
- When leaving a project, do the thing in the onclick rather than in the popover render function
- Update teamPermissions when joining/leaving a team so that the join team button appears/goes away
- Try leaving a project on a team page, it should remove you from the user list without blanking out the whole page
- Try leaving and joining a team via email whitelist. The join team button should get replaced with an invite button (note that leaving teams is broken right now https://github.com/FogCreek/Glitch/issues/1733)
> Quixotic rocket: Fix leaving team projects, fix joining teams via email whitelist

- src/components/wistia-video/index.js
- src/presenters/pages/home-v2/banner.js
* arrow-ankylosaurus.glitch.me
* https://github.com/FogCreek/Glitch-Community-Work/issues/63
* When you click the button to 'watch video' on the homepage, a click on the spacebar should pause the video for consistency with other video players/how it would be if the video player was actually on screen the whole time.
* We're relying on Wistia's control to stay the same - or at least have a pause button with aria-label='Pause'
* If the player doesn't appear in time or the pause button can't be found, we fall back silently to the old behavior of focus going to the `body` element
* Start the video on the homepage by clicking the button; start the video on the homepage by tabbing to the button and pressing space
Is this an okay solution?
> Auto focus the pause button when wistia component appears on homepage

- src/state/current-user.js
https://quixotic-rocket.glitch.me
https://github.com/FogCreek/Glitch-Community-Work/issues/346
- Get rid of the attempted analytics destructure so identify gets called
- Small simplification to hasLogin cookie setting
Check the network panel for a request to api.segment.io/v1/i, there should be a request made on page load
> Quixotic-rocket: Fix the analytics identify call

- src/presenters/pages/project.js
* Remix link: https://honored-cantaloupe.glitch.me/
* hides the delete project button on the project page if the user is not an admin
* create a project with one account
* invite another account to that project
* that second person should now visit the project page
* they should not see a delete project button near the readme
> honored-cantaloupe: don't let nonadmins see delete project button from the project page

- src/components/inputs/text-input.styl
* Remix link: https://probable-castanet.glitch.me/
* If you try searching for something on the glitch site on an iphone (and potentially other devices as well?) it will zoom in to the input field (which makes sense) unfortunately when you hit enter, there's no zoom out behavior. There seem to be [2 main ways of handling this](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone) that I could find, one is to set the fontsize to 16px (as apparently that's the size iphones don't zoom for) and the other is to prevent zooming all together (which sounds terrible from an accessibility standpoint). I guess the 3rd option would be to just let it go and embrace the weird zoom behavior.
* get an iphone and type in the search field, notice it should not …
> Probable castanet: Use larger font on touch devices to prevent strange zoom behavior

- src/components/team-analytics/team-analytics-activity.js
- src/state/error-handlers.js
- src/state/project.js
- src/state/team.js
- src/state/uploader.js
- src/state/user.js
* acidic-tomate.glitch.me
* https://github.com/FogCreek/Glitch-Community-Work/issues/344
if the upload itself failed: 
If the upload succeeded but we can't process the image: 
* Only one error notification ever shows up on file upload failures. Before, you might have got an 'upload failed' notification followed immediately by a 'something went wrong, try refreshing?' notification because we kept acting as if the upload succeeded when it failed
* We don't let errors bubble up to sentry if they're just file upload errors - more than likely it's the user's problem, not ours
* removes a console.log that got left in when I was working on the team analytics section
* Try uploading [the image in this zip file](https://fogcreek.slack.com/archives/CJS8MABLZ/p1567098131017400?thread_ts=1567097911.01 …
> Acidic-tomate: standardize error handling on image upload failures

- views/index.ejs
* [repeated-snapper.glitch.me](https://repeated-snapper.glitch.me/)
* [#415](https://github.com/FogCreek/Glitch-Community-Work/issues/415)
Adds a `<meta>` tag for Norton SafeWeb verification. We can remove it once verification is complete.
This meta tag should be in the head:
```
<meta name="norton-safeweb-site-verification" content="p2ou8wp-rqphby6friirgu674v4mdl63bldktot1arf8x-02sknirce1ybskl3oca6c6845btybnr4r8pmf841sqg5yeyl759tq0br2n3f3dcxrv7f48bn0pnqopptmw" />
```
> repeated-snapper: add Norton SafeWeb verification

- src/components/search-results/index.js
- src/components/search-results/search-results.styl
* https://historical-salesman.glitch.me
* https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/422
* Updated styling on search results to better match previous (and not be so squished)
* Search for a thing, specifically one with lots of results
> Search results styling

- src/components/images/avatar.js
- src/components/project/project-actions.js
https://nova-chance.glitch.me
- https://github.com/FogCreek/Glitch-Community-Work/issues/396
- https://github.com/FogCreek/Glitch-Community-Work/issues/418
- Use cta styling on edit project buttons if you are a member
- Properly apply the background color styling to avatars
- Take a look at some project pages you are and are not a member of
- Look at some projects owned by anon users and verify their avatars show up
Avatar background colors are not supported by the shared components library as a prop, should they be?
> Nova chance: cta edit project button, fix anon user avatars

- src/curated/starter-kits.js
A missing comma was causing linting to fail on master
* Adds a trailing comma to `starter-kits.js`
* Tests should pass on CircleCI
> Add trailing comma: Fix lint failures

- src/components/images/avatar.styl
- src/components/search-results/index.js
- src/components/search-results/search-results.styl
- src/components/user-options-pop/styles.styl
* Remix link: https://vaulted-mirror.glitch.me/search?q=space
* Issue-tracker link: 
https://github.com/FogCreek/Glitch-Community-Work/issues/351
https://github.com/FogCreek/Glitch-Community-Work/issues/399
Original on left, changes on right
* Top search results that include projects will be vertically aligned to the top of the project-item-container
* Also changed the buttonWrap of the user-options-pop to account for long team names.
* Search for terms that give multiple top results ("space", "react") - the items should be vertically aligned
* Search for terms that give top results that don't include a project - there shouldn't be any extra margins applied (e.g. "scientiffic")
* Check that long names wrap well in the user options pop
Is there a better way to determine if the top results …
> User Options Pop Button Wrap & Top Search Result Vertical Alignment

- src/components/user-options-pop/index.js
* Remix link: https://shocking-panther.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/412
* replace support link with help center link in user menu
* log into https://shocking-panther.glitch.me/
* click on the user menu
* the second-to-last option should be "Help Center" and go to glitch.com/help
> Shocking panther: replace support link with help center link

- server/routes.js
- src/presenters/pages/router.js
* Remix link: https://fast-bottom.glitch.me
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/451
* added server-side and client-side redirects for redirecting `/~:domain/edit` url to `/edit/#!/:domain`
* added redirects for `/~:domain/console` to `/edit/console.html?:domain`
* visit https://fast-bottom.glitch.me/~community/edit
* it should redirect you to https://fast-bottom.glitch.me/edit/#!/community (which will show the message "Sorry, no editor for remixes!")
* visit https://fast-bottom.glitch.me/~community/console
* it should redirect you to https://fast-bottom.glitch.me/edit/console.html?community (which will also not load, but the URL is correct)
- do we actually need the client-side part? The …
> Fast bottom: redirect `/~:domain/edit` to editor, `/~:domain/console` to console

- package.json
https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/479
Apply `--max-old-space-size=4096` to the server process. I'm setting it using an env var rather than in the nodemon command because nesting strings in the shell gets really messy and unreliable
If the process doesn't run out of memory it is working?
This increases memory for the main server in all cases, but it's probably only needed when we're running webpack in the same process.
> Quixotic-rocket: Increased memory limit for node

- src/components/collection/container.js
* Remix link: https://functional-politician.glitch.me/hardware
Category collections should show the category avatar
Non-category collections should show the generated avatar
* Unintentionally removed the avatar from category collections (e.g., `/games`, `/art`, `/hardware`).  Added them back in here.
* Check that the avatar appears on category collections:
https://functional-politician.glitch.me/hardware
* Check that the generated avatars appear on non-category collections:
https://functional-politician.glitch.me/@scientiffic/microbit
> Show Category Avatar instead of generated avatar

- src/presenters/pages/user.js
* [spectacular-coyote.glitch.me](https://spectacular-coyote.glitch.me/~cowards)
* [#473](https://github.com/FogCreek/Glitch-Community-Work/issues/473)
A user with one pinned project does not see the onboarding banner on their profile
Check if the *current user* has any projects, not if the profile we're visiting has any *recent projects*
- Log in with an account that has one project
- Pin that project, refresh. You should not see the onboarding banner on your profile
- Delete that project, refresh. You *should* see the onboarding banner on your profile
Work as expected?
> spectacular-coyote: fix onboarding banner logic on profile pages

- src/models/collection.js
* Remix link: https://invented-catsup.glitch.me/
* Doing a bit of qa on My Stuff/Private Collections and noticed that when you create a new account, the mocked out My Stuff collection (that gets turned into a real one) was not showing as a private collection
* make a new account
* enable My Stuff
* go to your user page and look at the empty My Stuff Collection, it should have a 🔒 sign before you click on it.
> Invented Catsup: Fix small my stuff bug

- src/presenters/pages/create.js
* Remix link: https://romantic-broom.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/158
* wrapped large videos in a container that reserves space while video is loading, to prevent layout jumps
* visit https://romantic-broom.glitch.me/create with network throttled to 'low-end mobile'
* there should be empty containers where the large videos go
* when the videos load, the layout should not jump around
* should we do anything for smaller screens? it seems like those have fixed heights instead of aspect ratios
> Romantic broom: fixed ratio containers for large videos on create page

- src/components/team/team-item.js
- src/components/user-options-pop/index.js
- src/presenters/pages/create.js
- src/presenters/pages/home-v2/banner.js
- src/presenters/pages/team.js
* Remix link: https://warm-fossa.glitch.me
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/464
* replace internal `<Button as="a" href={href}>` links with `<Button as={Link} to={href}>`, `<Button as={TeamLink} team={team}>` etc.
* log into https://warm-fossa.glitch.me
* click on the user menu
* click on a team
* the page should navigate to that team's page without a full refresh
I think all the remaining cases of `<Button as="a">` are external or open in a new tab; did I miss any?
> Warm fossa: make internal button links use react-router

- server/render.js
https://fallacious-slice.glitch.me/ (nothing interesting there)
https://github.com/FogCreek/Glitch-Community-Work/issues/494
If the require call failed for any reason `isTranspiled` would never be set to true, and the site would never clear the require cache so it could try again. Now it tracks that we have an outdated require, and clears the require cache each time until it works.
1. Make a remix and type some gibberish into the top of something in src/
2. Load up the homepage and notice an error in the logs when trying to ssr
3. Remove the gibberish and reload the page
4. This remix will ssr, while ~community would continue showing the error that was fixed
> Fallacious slice: Fix ssr getting stuck after failing to load the client code

- src/state/current-user.js
- src/state/project-options.js
* Remix link: http://sour-maize.glitch.me
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/486
* update current user's "projects" array when leaving a project
* log into http://sour-maize.glitch.me
* click on the project options menu for one of your recent projects
* leave the project
* the project should be removed from your recent projects
Update the current user's cached projects/collections/etc when any other relevant action happens
> Sour maize: update recent projects when leaving a project

- src/components/containers/projects-list.js
- src/components/header/index.js
- src/components/project/project-item.js
- src/components/project/project-item.styl
- src/components/recent-projects/index.js
* [circular-passionfruit.glitch.me](https://circular-passionfruit.glitch.me/)
* [#453](https://github.com/FogCreek/glitch-community-work/issues/453)
* [User dashboard spec](https://docs.google.com/document/d/10KS93TQ6vaQcVSL0ujUj4__GGl7M5MlS1vimzNqiizU/edit#heading=h.3im6lap0txtw)
* Remove the "Resume Coding" button
* Add the `showEditButton` prop to `<ProjectsList>` and `<ProjectItem>`, which if true, will render a footer with an "Edit Project Button"
* Log in, you should see the "Edit Project" button on your recent projects dashboard on the homepage
* The "Resume Coding" should be gone
* Check out other `<ProjectsList>`s, you should not see the "Edit Project" button on those `<ProjectItem>`s
- Team page recent projects
- User page recent projects
> circular-passionfruit: Remove "Resume Coding" button and add "Edit Project" to recent projects project items

- src/components/buttons/bookmark-button.js
- src/components/collection/collection-item.js
- src/components/collection/collection-item.styl
- src/components/collection/collection-result-item.js
- src/components/collection/collection-result-item.styl
- src/components/private-badge/index.js
- src/components/private-badge/styles.styl
* Remix link: https://ember-spell.glitch.me/
* Issue-tracker link:
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/499
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/500
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/498
* We decided to remove the tooltip from "My Stuff", as it was acting weird on mobile, and we're hoping the button is intuitive enough that we don't need one
* Added a label to the Collection Link items in a collections list on the user page so it would announce via screenreader when a collection is private
* fixed an issue where private collections were not showing with a yellow background …
> Fix bugs for My Stuff and Private Collections, mostly a11y issues

- .circleci/config.yml
* Remix link: https://garnet-novel.glitch.me/
* [we're getting circle ci errors](https://circleci.com/gh/FogCreek/Glitch-Community/1482?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) because [pnpm has a breaking change](https://github.com/pnpm/pnpm/releases/tag/v4.0.0) that is breaking our stuffs. This keeps us on the old version until we can sort it out 
* I just put the code on https://garnet-novel.glitch.me/ but I think the real proof is that circle ci has passed
> Set pnpm to 3.x

- package.json
- Mark utils/sentry as having side effects so that it doesn't get removed from the bundle
- Notice that `window.Sentry` is set here, but not on glitch.com
> Profuse-tea: Call the sentry init code in production builds

- src/components/collection/collection-item.js
- src/components/collection/collection-result-item.js
- src/components/collection/container.js
- src/components/collections-list/index.js
- src/components/collections-list/styles.styl
- src/components/project/add-project-to-collection-pop.js
- src/components/project/featured-project.js
- src/components/project/project-item.js
- src/models/collection.js
- src/presenters/pages/project.js
- src/state/collection.js
- src/state/dev-toggles.js
- src/state/project-options.js
* Remix link: https://broadleaf-yttrium.glitch.me/
* Remove dev toggle for My Stuff and Private Collections, should be available for everyone now. 
* go to https://broadleaf-yttrium.glitch.me/ and make sure you don't have a dev toggle set for My Stuff, in fact you shouldn't even see the My Stuff dev toggle as an option
* you should see My Stuff appear in your collections list
* you should see the My Stuff Button appear on any project item
* you should see My Stuff listed as an option in Add project to Collections dropdown
* you should see a privacy toggle on all collections pages
any last minute thoughts?
> Broadleaf-yttrium: Release My Stuff and Private Collections

- src/state/collection.js
- src/state/project-options.js
* Remix link: https://woozy-damselfly.glitch.me/
When users click on the My Stuff button for the first time they create the collection. If they then toggle it again before a page refresh, we have not refreshed the cached user's collections and so when we try to remove it, it errors out :( 
Sad we didn't find this in QA, but seems like an easy fix to just manually update the current user's collections with the newly created collection. 
* create a new account (or use an account that has never used the My Stuff collection, note you will not be able to recreate this bug with a user account that has already used my stuff in the past)
* use the my stuff button to add a project to the collection
* then use it again to remove it from a collection
* notice you get an error in prod following these …
> woozy-damselfly: fix issue with removing a project from My Stuff after creation

- package.json
- src/components/buttons/bookmark-button.js
- src/components/private-badge/index.js
- test/components/private-badge.js
- test/setup.js
* Remix link
* https://github.com/FogCreek/Glitch-Community-Work/issues/542
no visual changes
* Adds a package called mocha-jsdom which does jsdom setup + teardown 
* This prevents a memory leak which can lead to a timeout of mocha
* Adds a unit test for the PrivateToggle component
* Adds a role to the children of hidden checkbox for greater assistive technology compatability
* makes BookmarkButton's child a span because labels can't semantically contain divs
* Make sure the bookmark button looks/acts the same
> Fix tests & add more & a11y fix

- .circleci/config.yml
Until we finish some other projects to make integration testing a little easier, let's turn them off.
> Cleanup: Remove integration test build step

- shared/sentryHelpers.js
https://github.com/FogCreek/Glitch-Community-Work/issues/544
Add an extra ignore errors entry because it's flooding sentry and sentry isn't merging them on its own
Do a search on sentry and notice that all 'Request error' errors are optimizely. (I've merged 100 or so into the 87k events one, there are probably new errors since then)
> Profuse-tea: Filter optimizely network errors out of sentry

- src/components/collection/container.js
- src/components/project/featured-project.js
- src/components/project/project-actions.js
- src/components/project/project-item.js
- src/presenters/pages/project.js
- src/state/segment-analytics.js
* Remix link: https://ivy-crib.glitch.me
* Issue-tracker link
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/538
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/534
* fix a broken analytics event on the remix this button
* change our analytics calls on the My Stuff and Privacy Toggles, per request of ezra
* open segment's debugger https://app.segment.com/fogcreek/sources/glitch_website/debugger
* search for My Stuff
* open the remix and press the My Stuff button from a variety of places, you should see the events come through (though it is admittedly a bit flakey i find)
* do the same for "Collection Privacy Changed"
Anything I'm missing?
> Ivy crib: Fix/Update Analytics Events

- src/presenters/pages/login/reset-password.js
* Remix link: https://humdrum-triangle.glitch.me/
* Fixes the reset password flow
* Go to the remix with user passwords enabled and a password set, then "forget" your password and get a reset email sent to you
* DO NOT CLICK THE LINK, use "copy link address"
* Edit the domain to be the remix above and then go there
* Reset your password on the remix
- Improvements to passwords/user account dialog in general?
> Humdrum-triangle: Add reset password from email

- src/components/collection/collection-projects-player.js
- src/components/collection/collection-projects-player.styl
- src/components/collection/container.styl
- src/components/text/markdown.styl
* Remix link: https://calm-babcat.glitch.me/@glitch/glitch-team-faves/play
* Edited the UI of the projects player for exploring collections to make it more streamlined and take up less space on the page.
* Check on desktop that you can view the project name, description, counter, and controls on a collection playlist: https://calm-babcat.glitch.me/@glitch/glitch-team-faves/play
* Check when viewing it on mobile that the collection description disappears
* Check that it looks right with dark colored collections: https://calm-babcat.glitch.me/@scientiffic/microbit/play/04e6b592-f7d3-43a4-aab8-7f52e3e34931
- Does the layout look right on all viewport sizes?
> Calm babcat: Updated UI for Exploring Collections (Play Mode)

- src/presenters/pages/about/about.styl
- src/presenters/pages/about/careers.js
- src/presenters/pages/about/careers.styl
- src/presenters/pages/about/index.js
* Remix link: https://lackadaisical-almandine.glitch.me/about/careers/
Before: 
After:
* fixes a safari style bug that was brought to our attention by 👏 glitch user https://glitch.com/@graygilmore 👏 with a potential fix already demoed here:  🆒 https://glitch.com/~deep-curiosity 🆒
* check out the careers page on safari (and other browsers too!) ensure all the images look good
> Lackadaisical almandine: unsmoosh images on about and careers page

- src/components/new-password-input/password-strength.js
- src/components/new-password-input/password-strength.styl
Note - I was running into some CI conflicts in my other PR so I'm seeing whether they're resolved here
* Remix link: https://grandiose-kumquat.glitch.me/
* The password meter styling got reverted at some point, so I'm adding it back.
* Log into https://grandiose-kumquat.glitch.me/
* go to account settings and try typing in a password
* if you have a weak password, the color of the progress bar should be pink (`warning`) - example weak PW: `password`
* if you have an ok password, the color of the progress bar should be purple (`notification`) - example ok password `password2`
* if you have a strong password, the color of the progress bar should be green (`success`)
example ok password `password2N@`
> Edited password meter styling

- src/components/global.styl
- src/presenters/pages/error.js
- views/index.ejs
* Remix link: https://quartz-latency.glitch.me/
* Issue-tracker link: https://github.com/FogCreek/Glitch-Community-Work/issues/504#issuecomment-543247130
* Replaced the Magikarp image with a bonsai tree
* The only way I knew how to do this was to force view the error page is to go into `/views/index.ejs` and to run `showFallback('notbuilt');` to the script a the bottom of the file.
> Quartz latency: Replace Magikarp Image

- server/routes.js
- Changed `Cache-Control` to `no-cache` for all community pages (does not include proxied pages or js)
- Fixed a typo in the js cache time, doesn't actually change anything because the default was milliseconds
- Load up the site, the html should have a `no-cache` header. JS and proxied pages should still be cached
- Pull up glitch.com and see how often you get `Hit from Cloudfront` in the response headers, it seems very rare for me (make sure the dev tools aren't disabling the browser cache)
This is a test for ssr optimizely, so I'll have to be ready to roll back in case this breaks the site
> Nova chance: Disable cloudfront caching of html

- src/presenters/pages/home-v2/index.js
* Remix link: https://glass-mercury.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/1680/mobile-version-of-homepage-is-not-properly-rendering-html
* Fix a bug on the homepage on small width screens where we weren't rendering the Fresh apps descriptions the same way we were on wider screens https://github.com/FogCreek/Glitch-Community/blob/master/src/presenters/pages/home-v2/index.js#L109
* look at the fresh apps section of the homepage on mobile and big screens, make sure we're rendering html where appropriate
> Fix homepage bug

- src/components/related-projects/index.js
- src/state/project.js
https://app.clubhouse.io/glitch/story/2985/project-page-more-by-section-flickers-a-bunch-on-page-load
- The 'more by' section on project pages memoizes args so it doesn't keep reloading every render
- Added a try/catch to handle 404s when loading project members
- Try loading up a project page and make sure there is no flickering
- Pin a project on your user page, refresh, delete it, then refresh again. On glitch.com a 404 will appear in the console, on this remix it won't. The 404 happens because the site ssr caches the deleted project, and the browser makes the request for members before it realizes the project is gone.
> Profuse tea: Fix project page flicker, one path for 404 errors

- src/components/project/project-embed.js
- src/components/project/project-embed.styl
* removed teams from embed profileList (only show users)
* fixed user list styling (avatars should overlap to be consistent with how users are displayed elsewhere)
* edited fullscreen icon to make it lighter and applied secondary button styling
* fullscreen button opens up app in new tab (rather than same window)
* fixed tooltip styling (margins were off)
> Updating project embed styling for exploring collections

- src/components/collection/collection-projects-player.js
- src/components/profile-list/index.js
- src/components/project/embed.js
- src/components/project/embed.styl
- src/components/project/featured-project.js
- src/components/project/project-embed.js
- src/components/project/project-embed.styl
* Remix link: https://glowing-draw.glitch.me/@glitch/glitch-team-faves/play
* Issue-tracker link: https://app.clubhouse.io/glitch/story/1691/create-or-reuse-an-iframe-to-display-current-project-item-in-a-collection
* Specs/doc links: https://fogcreek.slack.com/archives/CNW257T7E/p1571759715050000
before/after
* before we always pointed our embeds to glitch.com/embed/#!/embed/project-name which meant that as you tabbed through the different projects in a collection it was pretty slow, even waking the projects up all in one go on load of the page didn't quite work, as we still had to load the code, not just the project.
* now we optionally let the project embeds point directly to the project at projectname.glitch.me, which means we can wake them all up when we load the component, making …
> Glowing draw: Update Embed to optionally point directly to project

- shrinkwrap.yaml
- src/components/project/project-item.js
- src/components/team-users/team-user-info.js
- src/components/visibility-container/index.js
- src/state/project-options.js
- src/state/project.js
https://fallacious-slice.glitch.me/@Performance-Boost
https://app.clubhouse.io/glitch/story/3199/investigate-why-the-site-is-making-so-many-network-requests
- Team pages only load projects owned by team members once you open their user pop, rather than loading every project owned by every team member right away
- Don't load project item teams/members until they are visible on the page
- Try removing yourself from a team. It should act no different, except that it doesn't load all of your projects until you open your team user pop
- Clicking show all on pages with many projects does load everything eventually, and there are no 429 errors
Team pages with a lot of projects slow down quite a bit as you scroll because every time a project loads the context causes every project to re render
> Fallacious slice: Don't load stuff right away, wait until it's relevant

- src/presenters/pages/router.js
- src/presenters/pages/settings.js
- src/state/api.js
* Remix link: https://evergreen-opossum.glitch.me/
* when we added these conditional routes it looks like <Router/> was rerendering...forever? but only when you were running the exact same code in the same browser window in 2 different tabs (or at least thats what I think is happening!) When I move the conditional logic to within the page component the bugs seem to go away for me
* to recreate the bug, open the same url in two different tabs, in the second tab you should see the /create page gifs flicker or the MoreCollections section flash as it randomly continues to choose different collections to feature
* if you repeat those same steps here, you should not see those bugs!
do you agree with my assessment?
> Fix freaky multi-tab morecollections bug and /create page i think?

- mochapack.opts
- src/hooks/use-window-size.js
- test/ProjectsList/index.js
- test/components/private-badge.js
- test/helpers/models.js
- test/reactA11yHelper.js
- test/server/render.js
- test/setup.js
https://nova-chance.glitch.me/ (nothing to see there)
https://app.clubhouse.io/glitch/story/3112/create-unit-test-for-top-level-page-in-ssr
- Added tests for the home page, create page, and the entity pages (checks that they render without errors and use the api cache data)
- Only setup jsom for tests that use it, so that other tests can test in a node env
- Removed setup.js because the setup it did happens at a fixture level
Change a component to reference window and make sure the tests fail
> Nova chance: Add unit tests for server side rendering

- src/components/collection/collection-options-pop.js
- src/components/popover/index.js
- src/components/project/featured-project-options-pop.js
- src/components/project/project-options-pop.js
* https://app.clubhouse.io/glitch/story/4068/accessible-name-missing-for-project-options-buttons
* trusting-macadamia.glitch.me
* Buttons in HTML don't have a `label` attribute; they have `aria-label`. 
* Make `aria-label` a required prop on PopoverMenuButton since it only displays an icon that has no meaningful alt text. 
* The existing label on one of the buttons wasn't doing string interpolation correctly so it said `project options for {project.domain}` instead of `project options for soulpatch` (etc)
* Run an accessibility checker extension like Axe or Accessibility Insights on pages with a project options pop
Merge https://github.com/FogCreek/Glitch-Community/pull/1062  and make sure it takes precedence over the server changes here
> Trusting-macadamia: fix accessible names on project options pop buttons

- src/components/collection/create-collection-pop.js
- src/components/project/add-project-to-collection-pop.js
- src/models/collection.js
- src/state/collection.js
- src/state/project-options.js
* Remix link: https://gleaming-watercress.glitch.me/
* Issue-tracker link:
- https://app.clubhouse.io/glitch/story/1592/project-missing-id-field-when-removed-from-my-stuff
- https://app.clubhouse.io/glitch/story/1595/createcollection-error-handling-typeerror-cannot-read-property-fullurl-of-null
- https://app.clubhouse.io/glitch/story/1618/create-collection-pop-cannot-read-property-url-of-null
We get several types of sentry errors, that I think all stem from the same issue. We try to create a collection and it fails for some reason (ex the server is down or whatever) and then rather than 
- https://sentry.io/organizations/fog-creek-software/issues/1156993388/?project=1246508&referrer=github_integration
- https://sentry.io/organizations/fog-creek-software/issues/1156993388/?project=1246508&r …
> Fix create collection error handling

- src/components/new-project-pop/index.js
* Remix link: https://hungry-pipe.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/4218/onboarding-banner-doesn-t-fire-segment-events [ch4218]
At some point we added this origin to new project pop: https://github.com/FogCreek/Glitch-Community/blob/master/src/components/new-project-pop/index.js#L51 possibly when we moved to popovers? This however was a mistake. We want the origin to be set by the parent component where that New Project Pop is used and by adding it to the child we lose the parent origin. 
For example, when a user clicks on the a project in new project pop from within the onboarding banner, they will get an origin that says if they're on the onboarding banner on the home page or on their user profile: …
> Hungry-Pipe: Remove bad analytics origin

- src/presenters/pages/settings.js
- src/state/local-storage.js
* Remix link: https://tremendous-handstand.glitch.me/settings
after/before
While working on: https://github.com/FogCreek/Glitch-Community/pull/1069 we noticed that the /settings route kept re-rendering forever. 
This behavior matches up with what we saw back when we made /settings a conditional route and it actually caused `<Router/>` to re-render indefinitely. We made a change to put the conditional inside the Settings page component, but never really got to the bottom of why re-renders were happening in the first place, we just isolated the issue to a page that only glitch devs are using right now.
@GregWeil and @whimsicallyson and I looked at it again today and realized that when we used the dev toggle and when we had 2 versions of glitch open at one time we could see the re-renders …
> Fix rerender bug

- src/state/api.js
* Remix link: https://olive-staircase.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/2523/logging-in-doesn-t-merge-in-anon-user-s-project-s-regression
* do not make any post requests before we have a persistent token
To recreate the bug:
- go to glitch.com and log out
- create a project (remember the name of it!)
- go back to glitch.com
- you should now be an anonymous user
- try logging in with email/magic code and **click on the link** (do not copy paste code you won't recreate the bug)
- search for your project, notice it's still owned by an anoymous user and not yourself!
To see the bug fixed:
- go to glitch.com and log out
- create a project (remember the name of it!)
- go back to glitch.com
- you should now be an anonymous user
- grab your persistent token
- …
> Fix signin bug

- src/components/project/project-user.js
- src/components/project/project-user.styl
* Remix link: https://buttercup-nickel.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/4901/team-section-missing-on-project-pages
[When I deployed the project permissions changes](https://github.com/FogCreek/Glitch-Community/pull/1085), it looks like I forgot or left out teams somehow 🤦‍♀ this brings it back. Sorry about that.
go to a project page where the project belongs to a team, you should be able to see the teams it belongs to. Clicking on them should bring you to the teams page.
One thing I'm thinking is when you own the project its a little weird having tooltips for teams which are links to those team pages AND also having the users be popovers. I wonder if we should make the teams popovers (like add/remove from team or something like that), does that sound …
> Fix missing teams on project page

- src/state/api.js
https://app.clubhouse.io/glitch/story/4471/edge-case-anonymous-account-persists
https://app.clubhouse.io/glitch/story/5076/signing-out-of-the-community-site-gives-me-an-anonymous-user-that-can-sign-out-i-e-there-s-no-sign-in-button-until-i-refresh
The APIContextProvider does not modify the api object returned from getAPIForToken. Its modification stalls requests until the token is ready, once the user is loaded from localStorage or an anon user is created. Since it modified the actual api object, this affected the call to create the anon user, so depending on init order the site would never create an anon user because it was waiting for the anon user to be created.
Sign out (delete `cachedUser` and `community-cachedUser` from localStorage) and make sure the …
> Nova-chance: Fix a regression when creating anon users

- shrinkwrap.yaml
- src/client.js
- src/components/team-analytics/index.js
- src/presenters/pages/secret.js
- src/state/rollouts.js
- src/state/segment-analytics.js
https://app.clubhouse.io/glitch/story/4829/add-an-experiment-viewed-event-for-optimizely-rollouts
https://app.clubhouse.io/glitch/story/2956/error-securityerror-the-operation-is-insecure
- Checking for an optimizely value sends an 'Experiment Viewed' event to segment with info about the feature and status
- Cleaned up team analytics a very small amount so it only reads from optimizely once
- Changed the secret page so it doesn't trigger tracking events
- Block optimizely from sending yet another error message to sentry
Load up a team page you are not a member of and notice that there is no track request. Load up a team page you are a member of, and there should be a request with info about whether analytics are enabled
> Quixotic rocket: Send 'Experiment Viewed' events to segment

- src/components/collection/collection-projects-player.js
* Remix link: https://pickle-suggestion.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/4600/wake-up-projects-a-few-at-a-time
We decided to deploy Exploring Collection without waking up projects since we didn't want to put any additional pressure on infrastructure. That said we looked into the outage on 11-12-19, and we don't think it was related to the exploring collections feature so now that it's out and doing fine, we'd like to deploy a change to wake up some of the projects again so that the embeds transition better from one project to another as you tab through. 
to be extra conservative I've added some logic here to ensure a client only requests to wake up a few projects at a time.
To test you can go to the remix and look at a collection in play mode and open …
> Pickle suggestion: wake up some projects in a collection while in play mode

- src/components/team/delete-team-pop.js
- src/components/team/team-item.js
- src/state/project.js
- src/state/team.js
- src/state/user.js
* https://cookie-ricotta.glitch.me/
* https://app.clubhouse.io/glitch/story/3863/team-ownership-transfer-highlights-and-links-out-to-which-teams-have-multiple-members-but-only-one-admin-step-2a
* https://app.clubhouse.io/glitch/story/3864/project-ownership-transfer-highlights-and-links-out-to-which-projects-have-multiple-members-but-only-one-admin-step-2a
* https://docs.google.com/document/d/1ya5WQraU0OPXf22uCsTGhaNnFU-3XyVLHSqGHzMkTPk/edit#heading=h.3im6lap0txtw (design spec)
* https://docs.google.com/document/d/17O0aLlf0znuCN4-LuVihAkGzsUtdFpv4uV7dQpouvWI/edit#heading=h.c3jzht6x35ee (tech spec)
* In order to have the delete account modal properly know what projects and teams are preventing account deletion, we need to update currentUser when changes happen. Now we do!
* throw some …
> State updates for user deletion

- server/render.js
- server/routes.js
- src/client.js
- src/server.js
- src/state/current-user.js
- src/state/globals.js
- src/state/rollouts.js
- views/index.ejs
https://superb-guide.glitch.me/secret
https://app.clubhouse.io/glitch/story/5135/optimizely-features-that-depend-on-the-user-being-signed-out-and-not-having-projects
- Added a new 'user has projects' cookie to track if the user has projects for server rendering
- Send the hasLogin and hasProjects to optimizely so experiments can be made conditional on them
Reload the secret page and run `window.cookie='optimizely-id='` in an incognito window until the swap test is enabled, then copy your persistent token to glitch.com and create a project. When you refresh the secret page the experiment should not be active.
- Get the hasProjects cookie whitelisted in cloudfront (not needed until the homepage/create test)
> Superb guide: Allow experiments to test against user signed in and project status

- src/components/containers/grid.styl
* Remix link: https://pool-rodent.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/1634/collection-items-overflow-horizontally-while-dragging
before and after: 
What a journey! TLDR: react-sortable-hoc needs the container to have `overflow: auto` set. For a more detailed explanation of what's going on you can check out https://github.com/clauderic/react-sortable-hoc/issues/617 
As far as I can tell the bug only happens when your browser window reaches a width of `1370px` or bigger.
anything!
> Fix bug of projects spilling over out of a collection

- src/state/current-user.js
https://app.clubhouse.io/glitch/story/5179/the-community-site-flickers-when-logged-out-via-editor
Check that the cachedUser matches the sharedUser before using it
Sign into the remix, wait for it to fully load, then run `localStorage.removeItem('cachedUser')` and refresh the page. On glitch.com it will show you as signed in for a moment then correct to signed out. On this remix it won't show the signed out user, but it will still server render the signed in homepage.
> Quixotic-rocket: Ignore the cached user if it doesn't match the signed in user

- src/components/delete-account/delete-account-modal.js
- src/components/team/team-result-item.js
* https://debonair-quokka.glitch.me/
* https://app.clubhouse.io/glitch/story/3863/team-ownership-transfer-highlights-and-links-out-to-which-teams-have-multiple-members-but-only-one-admin-step-2a
* https://docs.google.com/document/d/1ya5WQraU0OPXf22uCsTGhaNnFU-3XyVLHSqGHzMkTPk/edit#heading=h.3im6lap0txtw (design spec)
https://docs.google.com/document/d/17O0aLlf0znuCN4-LuVihAkGzsUtdFpv4uV7dQpouvWI/edit#heading=h.c3jzht6x35ee (tech spec)
* Creates a team-result-item component so that teams can be shown in a ResultsList
* Looks for teams where you're the only admin and there are multiple users, and not letting you continue till they've been fixed (as deleting your account would leave these in a bad state)
* Updates list automatically when project changes are made, no need for a refresh …
> Debonair quokka: Teams modal pane

- src/components/delete-account/delete-account-modal.js
- src/components/project/project-result-item.js
- src/components/project/project-result-item.styl
* https://astonishing-orchestra.glitch.me/
* https://app.clubhouse.io/glitch/story/3864/project-ownership-transfer-highlights-and-links-out-to-which-projects-have-multiple-members-but-only-one-admin-step-2a
* https://docs.google.com/document/d/1ya5WQraU0OPXf22uCsTGhaNnFU-3XyVLHSqGHzMkTPk/edit#heading=h.3im6lap0txtw (design spec)
https://docs.google.com/document/d/17O0aLlf0znuCN4-LuVihAkGzsUtdFpv4uV7dQpouvWI/edit#heading=h.c3jzht6x35ee (tech spec)
* Adds "isALink" prop to project-result-item so that clicking on results will take you to the project for updating
* Looks for projects where you're the only admin and there are multiple users, and not letting you continue till they've been fixed (as deleting your account would leave these in a bad state)
* Updates list automatically when project …
> Astonishing orchestra: Projects modal pane

- src/presenters/pages/router.js
- src/state/current-user.js
https://app.clubhouse.io/glitch/story/5266/the-current-user-is-only-loaded-on-the-first-page-load-and-never-again
- Reloading the user does not depend on location.state.preventScroll being set to false
- Fixed (what I think is) broken logic for scroll prevention, making the default to reset scroll
- Change the PageChangeHandler to a hook for simplicity
- Big indentation change in router.js, no actual changes in that block
Load up the site and notice requests being made to load your user. Click a link to somewhere else and notice that those requests get made again.
> Nova chance: Restore the reload-user-on-navigate behavior

- package.json
- src/components/collection/collection-result-item.js
- src/components/collection/collection-result-item.styl
- src/components/project/project-result-item.js
- src/components/project/project-result-item.styl
- src/state/collection.js
* Remix link: https://honored-cantaloupe.glitch.me/
* Issue-tracker link: 
- https://app.clubhouse.io/glitch/story/5041/dividers-on-results-lists-have-gone-missing
- https://app.clubhouse.io/glitch/story/5469/console-error-when-adding-a-project-to-my-stuff-collection-when-running-locally
* upgrade to latest version of shared components
* use new privacy props: https://github.com/FogCreek/shared-components/pull/69
* fix a console.log error 
* add projects to a collection on the collections page
* add projects to a collection on the project-item pages
* filter a project in a team analytics page
bugz?
> Add project/collection popover fixes

- server/render.js
- views/index.ejs
https://app.clubhouse.io/glitch/story/5246/investigate-ssr-rendering-for-google-crawler
- Static builds use build/server.js instead of src/server.js
- Allow no-js ssr pages when running in the google cache
- Check for network errors loading the js code, and show a unique error if that happens
- Load up the site (it's in a static build right now)
- Join the project and delete build/client.hash.js, notice that the 'your browser does not support js' message does not appear, and instead it says something failed to load
> Superb guide: Expand bootstrap error messages, fix for static builds

- package.json
- server/webpack.js
- src/app.js
- webpack.config.js
https://quixotic-rocket.glitch.me/ (nothing surprising there)
https://app.clubhouse.io/glitch/story/4458/linting-doesn-t-run-locally-on-npm-start-anymore
- Tell the webpack middleware to use the same stats config as the watcher does
- Hide modules from compiler output because it's largely noise
- Lint the aliases file for full coverage
- Type some gibberish into a src/ file and see if webpack prints the error
- Do it again but swapping BUILD_TYPE between watcher/memory
The webpack express middleware ignores the stats field in the webpack config, and has a separate argument to specify it. The stats.children field determines if child modules get printed out, but when using multiple webpack configs it controls the stats object per config. Since children was set to false, it did not print …
> Quixotic rocket: Consistent webpack output in all build modes

- src/components/containers/grid.styl
- src/components/global.styl
* Remix link: https://olive-staircase.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/5783/overflow-auto-breaks-grids-with-one-row-in-it
yuckyuckyuck:
* [not that long ago](https://github.com/FogCreek/Glitch-Community/pull/1114) I added `overflow: auto` to our grid containers to fix an issue with our drag and drop. Unfortunately in doing so I caused another bug see screenshot above ^ you can see that things that overflow from that container are clipped. So I removed it.
* I then realized that if we removed `overflow-x: hidden` from our global styles, the overflow bug we had our with our drag and drop library goes away. If you're interested in why this is I'm happy to walk you through it! I'm debating making a change directly to the lib to handle this situation, but …
> Remove global overflow to fix drag and drop

- src/components/team/add-team-project-pop.js
- src/state/project-options.js
* Remix link: https://glass-mercury.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/5713/only-project-owners-should-be-able-to-add-projects-to-teams
* Only project admins (aka owners) should add a project to a team. I also am proposing that project owners and team admins should be the only ones who can remove a project from a team. I believe @modernserf is working on the backend on this as well, but fixing the ui seems like a great first step.
These scenarios should work as follows I believe:
| User        | Test           | Should work  |
|:------------- |:-------------|:-----|
| Project Owner/Team Admin | add project to team | yes |
| Project Owner/Team Admin | remove project from team | yes |
| Project Owner/Team Member | add project to team | yes |
| Project …
> Only project admins (aka owners) should add a project to a team

- src/components/buttons/responsive-button.js
- src/components/buttons/responsive-button.styl
- src/components/project/add-project-to-collection-pop.js
- src/components/project/project-actions.js
- src/components/project/project-actions.styl
https://app.clubhouse.io/glitch/story/3489/replace-usewindowsize-with-css-media-queries
Added ResponsiveButton, which shows either `children` or `shortText` based on the window width
- Resize the window on a project page and see how it does
> Nova chance: Swap button text using media queries instead of react

- ci/README.md
* updated to match the changes in the [referenced PR](https://github.com/FogCreek/Glitch-Community/pull/1121), primarily the interaction between the various 3rd party services. Linked-to diagram is also correspondingly updated.
* I switched back to Markdown style numbering because GitHub-flavored Markdown (and possibly others) did not like my attempt at numbering it manually. My apologies, but please view the preview (not the diff) for the numbering.
* is this sufficiently clear?
* should any additional guidance or information be included?
* is any of it extraneous?
* I think it might be worthwhile to add some level of tracing to this process in the future
* ~finish production infra (s3 bootstrapping bucket and the like)~ (in https://github.com/FogCreek/Glitch/pull/2444)
* connect …
> docs updated for https://github.com/FogCreek/Glitch-Community/pull/1121

- ci/local-deploy.sh
- ci/publish-build-asset.sh
* move the build assets to a subpath so we can properly expire them
* merging into staging should kick off a build to test the changes
* I'm going to go ahead and merge this into staging - I just wanted a branch to point to
> move build assets to a subpath for better expiration

- src/state/api.js
* Remix link: https://placid-salto.glitch.me
* Issue-tracker link: https://app.clubhouse.io/glitch/story/6315/pinning-projects-no-longer-working
* use v0 routes for user pins, v1 routes for team pins
* log into placid-salto.glitch.me
* visit your user page
* verify you can pin & un-pin your projects
* visit a team page you control
* verify you can pin & un-pin your team's projects
> Placid salto: use v0 routes for user pinned projects

- ci/env
* adds the production S3 bucket and access key ids
* updates the staging access key to one already managed by terraform - this requires some CircleCI changes to match. future deploys will test that the key works as expected.
* merge and deploy
* sanity check
* timeline for getting these changes into prod so Circle can start using them.
- i'll merge this to staging to get the production info and the corrected staging key there. Once this is in staging, when we are ready to start deploys to the prod infra just merging staging to master (and adding the proper env var to CircleCI) should get things running.
> add production settings (prep for merging to master and starting prod deploys)

- src/presenters/pages/project.js
* https://cookie-ricotta.glitch.me
* https://app.clubhouse.io/glitch/story/6637/in-title-tag-for-project-pages-change-format-of-project-names
* Separates words in project domains (by hyphen only), converts them to Title Case
* go to a project page, look at what's in the tab title
all good?
> separate projects into words and Title Case them

- src/components/glitch-pro-cta/index.js
- src/components/glitch-pro-cta/styles.styl
- src/components/header/header.styl
- src/components/header/index.js
- src/presenters/pages/about/pricing.js
* Remix link: https://discovered-seashore.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/6405/add-a-cta-in-the-nav-bar
* add Glitch Pro link/button to nav bar
* use `window.location.origin` for redirect urls, so it redirects to the current remix
- visit https://discovered-seashore.glitch.me/
+ the PRO link should not be visible to logged-out users
- log in with a new Glitch email address (you can add a "+" label to your existing glitch.com email, eg `justin+test1@glitch.com`)
+ the PRO link should not be visible to users not in the feature flag group
- visit https://discovered-seashore.glitch.me/@testing-team and click "Join Team"
- visit https://discovered-seashore.glitch.me/secret and set "Pufferfish" to "Enable"
- go back to https://discovered-seashore.glitch.me …
> Discovered seashore: Glitch PRO link in navigation

- src/state/api.js
- src/state/current-user.js
- src/state/project-options.js
* breezy-ocelot.glitch.me
* https://app.clubhouse.io/glitch/story/6898/join-team-project-from-project-page-doesn-t-work
* changes the API call to a PUT, as needed for the new route
* Go to a project page for a project that is in a team you're on, click the "join team project" button under the embed. You should join the project, not get an error
* is the change in current-user necessary? it seems like we ought to have it
- Not really a TODO, but note that the button doesn't update properly if you're joining a project on the glitch team (see ch6956). Isaac's looking into that further, he thinks its a timeout when we update the search index (but still not sure why it only happens for glitch team projects)
> update API route to PUT for joining team project

- src/components/collection/collection-item.js
- src/components/collection/collection-item.styl
- src/state/collection.js
- test/components/collection/collection-item.js
- test/helpers/mockContext.js
* Remix link: https://sarah-staging.glitch.me/
* Issue-tracker link:
- https://app.clubhouse.io/glitch/story/6407/render-the-extra-memory-collection-in-a-collectionslist-on-user-profile-pages
- https://app.clubhouse.io/glitch/story/7187/extra-memory-should-not-have-delete-menu
* Specs/doc links
* adds a star avatar for to a collections list
* hides delete dropdown if it's a special collection
* join the testing team, enable pufferfish, go pro, check out on your user page, double check that the rest of the collections lists look good
anything!
> Show star in collections list when it's an protected collection

- src/hooks/use-title-formatter.js
- src/presenters/pages/collection.js
- src/presenters/pages/project.js
- src/presenters/pages/team.js
* https://cookie-ricotta.glitch.me
* https://app.clubhouse.io/glitch/story/7676/change-format-of-title-tags-for-team-and-collection-names
* Separates words in team and collection domains (by hyphen only), converts them to Title Case
* go to a team or collection page, see what's in the title bar
we cool?
> separate and Title Case team and collection page titles

- src/components/new-stuff/new-stuff-prompt.js
* none, lazy.
* https://app.clubhouse.io/glitch/story/4077/a11y-new-stuff-pup-should-be-contained-in-a-landmark-aside
* Puts pup into an aside
Is this what we want, or should the _overlay_ be in the aside?
> moves pup into aside

- server/render.js
https://app.clubhouse.io/glitch/story/4531/typeerror-resetstate-is-not-a-function
Any error in the load client function will cause it to clear out the cache so that the next request will start fresh. My hope is that the resetState error happens because the initial require happened while webpack was still writing the file, and the node require cache is keeping it from trying again. This could backfire if the build file is actually broken, in which case the server will reload from scratch on every request.
Set BUILD_TYPE=watcher and try making changes in the src directory and see them appear in the site.  I don't have an actual repro for the resetState error, so we'll just have to see if it stops happening.
> Superb guide: If there's an error loading ssr code, dump the cache and try again on the next request

- src/state/glitch-pro.js
* https://breezy-ocelot.glitch.me
* https://app.clubhouse.io/glitch/story/7727/stripe-module-loading-on-every-page-adding-page-lag
* load a blank script if pufferfish isn't enabled, to save the time and data of loading stripe when we don't need it
* enable/disable pufferfish, see what shows up in your debugger
this feels hacky to me. is there a better way?
> load empty script if pufferfish isn't enabled

- package.json
- server/optimizely.js
- server/routes.js
- shrinkwrap.yaml
- src/client.js
- views/index.ejs
- webpack.config.js
https://quixotic-rocket.glitch.me/questions
https://app.clubhouse.io/glitch/story/7590/syntaxerror-json-parse-unexpected-character-at-line-1-column-1-of-the-json-data
- Send the optimizely key to the client rather than using process.env, which gets written into the bundle (so you don't have to wait for a rebuild after changing it)
- Removed the lodash module replacement plugin. It's supposed to cut file size by replacing unused lodash functions with identity/noop versions, but you have to specify which functions are preserved and it was breaking optimizely because it was replacing cloneDeep with an identity function.
Check out the site and see if anything broke
The bundle doesn't seem substantially larger, the difference is < 10kb. Am I looking at the wrong numbers? I think a slightly …
> Quixotic rocket: Get rid of the lodash module replacement plugin to fix an optimizely error
