CONTRIBUTING.md
src/templates/pages/index.jade

trying out git contrib workflow. this fixes a typo in contrib doc but also for some reason it is picking up another typo fixed by someone else, i'm assuming @judeallred :)

Fix contrib typo

---

public/styles/projects.styl
src/presenters/pages/index.js

on desktop (mac ff): 
on mobile (ios safari):

Add hello-sqlite to starter apps

---

.gitignore
package.json
shrinkwrap.yaml
src/.eslintrc.js
src/presenters/includes/starter-apps.jsx
src/presenters/pages/search.js
src/presenters/pop-overs/sign-in-pop.jsx
src/presenters/pop-overs/user-options-pop.jsx
src/presenters/what-is-glitch.jsx
src/templates/includes/footer.jade
views/index.ejs
webpack.config.js

Jenn -- just adding this to the linter while our .jsx surface is low.  This overall seem right to you?

enable eslint-jsx-A11y and fix up existing .jsx templates

---

FAQ.md
README.md
public/styles/emoji.styl
public/styles/markdown.styl
public/styles/overlays.styl
src/curated/embed.js
src/curated/featured.js
src/models/project.js
src/presenters/new-stuff-log.js
src/presenters/pop-overs/user-options-pop.jsx
src/presenters/project-item.js
src/templates/layout.jade

doing a live site update merge before merging community PR

🎰☕️ live site updates

---

CONTRIBUTING.md
public/styles/projects.styl

Reverts FogCreek/Glitch-Community#18

Revert "💿💆 contributing update for live editing"

---

CONTRIBUTING.md

only updating the contributing live edit step to make sure mistakes i have made are not repeated lol :santa:

🐝🚉 update contributing live edit step

---

server/routes.js
views/index.ejs

this gives us better grouping and environment controls in sentry.io

Thundering way -- mark 'environment' and 'serverName' for sentry.io

---

src/presenters/entity-page-projects.jsx
src/presenters/includes/profile.jsx

- prevent an 'undefined' from rendering in as css class
- if all of a user/team's projects are pinned, hide the 'recent projects' section https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=131c150b5bc8473ba084cab5f93a7473

Faint tennis -- two tiny bug fixes

---

src/presenters/includes/profile.jsx
src/presenters/pop-overs/create-team-pop.jsx
src/utils/assets.js

this PR does a little merge work for https://github.com/FogCreek/Glitch-Community/pull/85 
..and also fixes a lint error that I caused moments ago.  🥇

Hazel liquid

---

server/proxy.js
server/redirects.js
server/server.js
shrinkwrap.yaml
src/presenters/footer.jsx
src/presenters/includes/team-elements.jsx

https://glitch.manuscript.com/f/cases/3323312/Serve-about-and-legal-from-about-glitch-project

proxy about.glitch.me and about-glitch.glitch.me -- case 3323312, case 3317554

---

src/presenters/header.jsx
src/presenters/pop-overs/user-options-pop.jsx

./src/presenters/pop-overs/user-options-pop.jsx:8/1663
./src/presenters/header.jsx:8/3

ebony-dinosaur -- bugfix for https://www.notion.so/glitch/Anonymous-User-Sign-out-5941dca5ecaa43b8b5ffe7fb73b64f30 

---

src/presenters/current-user.jsx

./src/presenters/current-user.jsx:8/82

remove use of user.email in favor of user.emails, case 3323347

---

server/routes.js
src/presenters/includes/team-users.jsx
src/presenters/pages/index.jsx
src/presenters/pages/search.jsx
views/index.ejs

glitch.com/search searches for 'undefined', and going there in dev breaks the page entirely. Now it just shows the 'no results' page.
I also made it so if the manifest files are missing for whatever reason (probably a first time build or after a `git clean` before webpack finishes) it shows the noscript site with a 'the site is not ready yet' message where the 'glitch requires js' message would be.

Nova chance: Fix empty query search page, improve first time build

---

src/presenters/header.jsx
src/presenters/pages/index.jsx
src/presenters/pages/user.jsx

https://www.notion.so/glitch/anon-user-with-no-projects-should-be-treated-as-a-new-user-0fa8ec94674c441a9123c10f62900d91
I also removed the ability to upload an avatar or cover image as an anon user

Superb guide: Hide recent projects and resume coding if you have no projects

---

src/presenters/pages/login.jsx
src/presenters/pages/router.jsx
src/presenters/pop-overs/create-team-pop.jsx
src/presenters/pop-overs/sign-in-pop.jsx
src/presenters/pop-overs/user-options-pop.jsx
styles/buttons.styl
styles/globals.styl
styles/pop-overs.styl

If you are signed out, the create team pop instead shows a sign in prompt
After you sign in it'll open the create team pop as if you were signed in to begin with
The anon user pop also has a sign in button in the teams section when the dev toggle is enabled

Profuse tea: Proper handling of anon users in the create team pop

---

src/curated/sample-analytics.js
src/presenters/includes/team-analytics-activity.jsx
src/presenters/includes/team-analytics-referrers.jsx
src/presenters/includes/team-analytics.jsx
src/presenters/pop-overs/team-analytics-project-pop.jsx
src/presenters/pop-overs/team-analytics-time-pop.jsx
styles/includes/inline-banners.styl
styles/includes/team-analytics.styl

Superb guide: Cleaner analytics prompt when no projects

---

CONTRIBUTING.md

Just a few minor changes.
- Spelling mistake
- Neatening up some markdown.

Neatening to CONTRIBUTION.md

---

shrinkwrap.yaml
src/presenters/includes/team-users.jsx
styles/pages/team.styl

Placeholder avatars after you've invited someone to a team (https://www.notion.so/glitch/Show-placeholder-avatars-for-people-after-inviting-them-88fdccd9e24e4172ae9d261e83e6dc2c)

Lovely edger: Placeholder avatars

---

src/client.jsx

https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=803a5d4b233847bb826a42c740d9c228

spiky-juice -- Test for the presence of the URLSearchParams api (so that Edge v<=16 doesn't try to use it and fail.)

---

src/presenters/pop-overs/user-options-pop.jsx
styles/buttons.styl
styles/globals.styl
styles/pop-overs.styl

Updated styling of user-options-pop for teams:
• teams listed alphabetically
• create team button placed on button, with slightly muted cta styling to differentiate between team links
• button wrap to ensure each team link is on a new line
https://teams-dropdown-update.glitch.me

Teams dropdown update

---

src/presenters/project-item.jsx
src/presenters/users-list.jsx

https://www.notion.so/glitch/teams-lets-you-remove-all-users-from-a-project-causing-an-odd-tile-display-deb09260c45e4b70b556c6531f12aed6
https://brave-fall.glitch.me

Brave fall: show team avatar if project has no users

---

src/presenters/includes/loader.jsx
src/presenters/pages/category.jsx
src/presenters/pages/project.jsx
src/presenters/pages/search.jsx

more quirks of the 'null' case of our currentUser consumer

Mercury saw -- fix null-user crashers on project, search, and category pages

---

server/proxy.js
server/redirects.js

./server/proxy.js:242011/71
fixes https://fogcreek.slack.com/archives/C3U9U59NE/p1541710318041500 (mostly just stretching my legs). https://raincoder-community.glitch.me/careers/ in action.

🏬⭐️ raincoder-community — make `/careers` work

---

src/presenters/pop-overs/add-team-user-pop.jsx

https://glitch.com/~freemail for the freemail service

Nova chance: Hide the domain whitlisting button for free email domains

---

src/presenters/pages/team.jsx
styles/pages/team.styl

https://puzzled-thorn.glitch.me
https://www.notion.so/glitch/refinements-on-teams-beta-flag-2b94a2b4d4db4836b220930fc993fba8

Puzzled thorn: further updates to teams beta flag

---

src/curated/sample-analytics.js
src/presenters/includes/team-analytics-referrers.jsx
src/presenters/pages/team.jsx

https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=fa625f0fccc84fd294511b16a55eff8e

Spiky juice -- fix NaN in analytics

---

src/presenters/pages/team.jsx
styles/pages/team.styl

https://www.notion.so/glitch/EDGE-display-quirk-in-team-beta-sticker-ccb00c02173f41a68edb2a6ca947cbc3
^ what it looks like in Edge now.
Also fixes a 'no-unused-vars' linting error

Puzzled thorn: fix Edge display bug for teams flag

---

styles/results-list.styl

https://steadfast-caption.glitch.me
small CSS change

Fixed issue with avatar styles in search results pop-overs

---

views/index.ejs

this ended up being useless, but oh well.
No rush; can just glom on to the next real push.

removing norton meta tag

---

src/presenters/includes/not-found.jsx
src/presenters/overlays/new-stuff.jsx
src/presenters/pages/router.jsx
src/presenters/pop-overs/new-project-pop.jsx

https://www.notion.so/glitch/87bda09f85184c1d81e1659aa62e4392?v=9f7963becc9341ed9af502682c6e9eef&p=a2f20aac17af492cb80cd304505bbec9
@garethx  FYI

Natural ceramic -- track page transitions & pupdates in segment.io/google analytics

---

src/presenters/pages/login.jsx

I'm not sure why this didn't get auto flagged in a pr. Maybe a bug in the checker or a bad merge?

Superb guide: Fix a warning from eslint

---

src/presenters/pages/user.jsx
src/presenters/user-editor.jsx

https://profuse-tea.glitch.me
It needs to reload the collections, but I moved where that happened and broke it. This brings it back to how it used to be. Team pages are unchanged because the add to collection pop doesn't list team collections.

Fix add to collection from your user page

---

src/curated/featured-embed.js
src/presenters/featured-embed.jsx
src/presenters/featured.jsx

https://inquisitive-whippet.glitch.me/
Updated prop type checking for `featured-embed.jsx` to remove console errors

Inquisitive whippet

---

src/app.jsx
src/presenters/current-user.jsx
src/presenters/pages/category.jsx
src/presenters/pages/collection.jsx
src/presenters/pages/index.jsx
src/presenters/pages/project.jsx
src/presenters/pages/router.jsx
src/presenters/pages/team.jsx
src/presenters/pages/user.jsx
views/index.ejs

@garethx 
https://glitch.manuscript.com/f/cases/3327656/
https://glitch.manuscript.com/f/cases/3327657/

Quixotic rocket: Include groupId in all analytics requests, send as a string

---

src/presenters/pop-overs/sign-in-pop.jsx

This is, at the very least, the UI for signing in with the code provided in an email. currently I'm seeing CORS errors when trying to actually use a code... not sure if the issue is me, or the fact that its a remix.
https://glitch.manuscript.com/f/cases/3326594/login-update-email-sign-in-with-manual-sign-in-code-support-and-ui-to-match-editor
https://astonishing-orchestra.glitch.me/

Astonishing orchestra: use code to sign in

---

src/presenters/pages/error.jsx
src/presenters/pages/project-not-found.jsx
src/presenters/pages/router.jsx

https://quixotic-rocket.glitch.me/~glitch-stats-bot/404
https://glitch.manuscript.com/f/cases/3327658/Project-not-found-page
If you're signed out you'll get an error page similar to the normal /~project page. Once you sign in with a user that can see the project (it's on the glitch team) it will redirect you to the glitch.me url.
@TimKingtonFC

Quixotic rocket: Project 404 page for glitch.me urls

---

public/api-auth.html
server/routes.js
views/api-auth.ejs

This is for private apps.  We need a page hosted at glitch.com that uses the user's token to generate a private app token.

Beneficial moose

---

src/presenters/pages/index.jsx
webpack.config.js

See https://legend-ermine.glitch.me/
Rebuilding seems to be working fast enough that we can just use this as-is (no need to modify how we build CSS in dev).

Modify source map type to get these back in development

---

src/presenters/notifications.jsx
src/presenters/pages/team.jsx
src/presenters/pages/user.jsx
src/presenters/pop-overs/add-collection-project-pop.jsx
src/presenters/pop-overs/add-team-project-pop.jsx
src/presenters/pop-overs/project-options-pop.jsx
src/presenters/team-editor.jsx
styles/pages/user-and-team-page.styl

reverting team feature project because of bug with pinned projects

Revert "Team feature project"

---

server/proxy.js
server/server.js

I'm giving up on trying to pull the url from the request, and am going to use the hardcoded config url. That means it'll be broken on anything other than glitch.com.
https://quixotic-rocket.glitch.me/culture/sitemap.xml

Quixotic rocket: Fix for proxied sitemaps v2-final

---

src/presenters/includes/collection-result-item.jsx
src/presenters/pages/category.jsx

https://profuse-tea.glitch.me/hello-worlds

Profuse tea: Fix styling on category pages

---

src/presenters/current-user.jsx
src/presenters/layout.jsx
src/presenters/pages/error.jsx

https://quixotic-rocket.glitch.me/~delicate-technician/404
Projects with a private glitch.me can still be public on the community site, which confused the check and caused a redirect loop. This checks if you can get a token to see the project.

Quixotic rocket: Fix the private frontend page

---

src/presenters/includes/dev-toggles.js
src/presenters/pages/secret.js
src/presenters/pop-overs/add-team-user-pop.js

I meant to do this in the original pr but forgot

Superb guide: hooks for dev toggles

---

src/presenters/pages/router.js
src/presenters/pages/sign-in.js

**First PR attempt:** https://github.com/FogCreek/Glitch-Community/pull/273 failed when merged into stage. Has all previous details.
**What happened next**
I remixed Community again, then copy/pasted my code and noticed a React error when attempting to view the new page. I cross-checked my code against the sign-in popover code I had copy/pasted the code from and noticed some changes. When I tried changing my `SigninPropWithoutRouter` to be like the one in the popover, I received an error that said hooks cannot be used in non-function components. I had, in fact, changed `SigninPropWithoutRouter` to a class so I could give it state.
Ultimately, I just removed the local storage parts since I wasn't using them. After re-testing things, I also found another small bug that occurs after logging …

Glitch OAuth Sign In (attempt 2)

---

CONTRIBUTING.md

This adds a condensed version of the deploy process to [`CONTRIBUTING.md`](https://github.com/FogCreek/Glitch-Community/compare/ink-lizard?expand=1#diff-6a3371457528722a734f3c51d9238c13).
The thorough descriptions were really helpful as I was learning how to deploy, but now that I'm comfortable with our deploy process, I thought a short, scannable checklist would be nice to have!

~ink-lizard: deploy checklist

---

src/presenters/includes/local-storage.js

I added a  basic feature detect. I bumped it up to a sentry error if we detect storage support then fail to write/read it later on.

Superb guide: Don't break the site when localstorage is disabled

---

src/curated/featured-embed.js
src/curated/featured.js
src/presenters/overlays/new-stuff.js
src/presenters/pop-overs/add-project-to-collection-pop.js

Fixes https://glitch.manuscript.com/f/cases/3328029/new-tooltip-on-HP-display-error

Fix new stuff tooltip bug

---

server/api.js
shared/api.js
src/presenters/pages/team-or-user.js
src/presenters/pages/team.js
src/presenters/team-editor.js
webpack.config.js

https://superb-guide.glitch.me/@glitch ⚡
This is a big improvement for performance, but there's a few odd bits that I'll point out in comments.
There's also a new shared/api.js file. This has a few (but probably more as time goes on) utility functions for working with the api.

Superb guide: Use the rest api for teams pages

---

src/presenters/pages/project.js

- use REST API for projects page
- add PropTypes check for projects data
- prettify

Relic hemisphere: use REST API for projects page

---

shrinkwrap.yaml
src/utils/abuse-reporting.js

for case [3327788](https://glitch.manuscript.com/f/cases/3327788/Abuse-reports-reporting-anonymous-users-should-say-User-Name-Anonymous-and-Abuse-Report-for-Anonymous-user)
@cori wants to see "Anonymous user" instead of "null" and the id of the anon user in the subject of discourse posts.
built/tested with reporting this anon user https://encouraging-gosling.glitch.me/user/3028957 - i closed the other PR for this because it got too borked post-prettier conflicts lol sorry
Here's the before:
And the after:
🎅

Encouraging gosling

---

src/curated/collections.js
src/curated/featured.js
src/presenters/user-editor.js

the REST API uses `id` instead of `projectId`

Woozy quicksand: fix bug in pin/un-pin

---

src/presenters/collection-item.js
src/presenters/includes/included-in-collections.js
src/presenters/pages/project.js
styles/collections.styl
styles/pages/project.styl

Show up to three random collections this project is included in, as well as the curator of those collections.
See https://glitch.manuscript.com/f/cases/3326600/

Intelligent bubbler: Add "included in collections" to project pages

---

src/models/collection.js
src/presenters/includes/included-in-collections.js

https://quixotic-rocket.glitch.me/~face-the-music

Quixotic rocket: Filter out collections without an owner

---

webpack.config.js

Remove caching from .styl files 😭

Resolve webpack caching of .styl files

---

src/presenters/includes/add-collection-project.js
src/presenters/includes/add-project-to-collection.js
src/presenters/includes/add-team-project.js
src/presenters/includes/delete-team.js
src/presenters/includes/edit-collection-color.js
src/presenters/includes/team-users.js
src/presenters/pop-overs/collection-options-pop.js
src/presenters/pop-overs/new-project-pop.js
src/presenters/pop-overs/popover-with-button.js
src/presenters/pop-overs/project-options-pop.js
src/presenters/pop-overs/report-abuse-pop.js
src/presenters/pop-overs/sign-in-pop.js
src/presenters/pop-overs/team-analytics-project-pop.js
src/presenters/pop-overs/team-analytics-time-pop.js

see discussion https://fogcreek.slack.com/archives/CB4EHAJ2J/p1553096926655300

Halved quartz: PopoverWithButton passes togglePopover explicitly

---

server/routes.js

Quick fix of team collection metadata

Rough trout

---

server/redirects.js

[support-redirect.glitch.me/support](https://support-redirect.glitch.me/support)

Redirect glitch.com/support to support.glitch.com

---

src/curated/featured.js
src/presenters/includes/description-field.js

Saw this in sentry: https://sentry.io/organizations/fog-creek-software/issues/947251341/?project=1246508&query=is%3Aunresolved&statsPeriod=14d&utc=false
Interesting that it hasn't more obviously broken things haha, anyway my bad. 
https://bow-kite.glitch.me/

Bow kite: fix sentry bug

---

src/presenters/header.js
src/presenters/includes/name-conflict.js
src/presenters/pages/category.js
src/presenters/pages/collection.js
src/presenters/pages/index.js
src/presenters/pages/project.js
src/presenters/pages/router.js
src/presenters/pages/team.js
src/presenters/pages/user.js
src/presenters/pop-overs/create-team-pop.js
src/presenters/pop-overs/project-options-pop.js
src/presenters/pop-overs/report-abuse-pop.js
src/presenters/projects-loader.js
src/presenters/recent-projects.js
src/state/current-user.js

Replace all uses of `<CurrentUserConsumer>` in preparation for redux.

Wiggly snap: all current user handled via hooks

---

src/presenters/note.js
styles/note.styl
styles/pages/collection.styl

Test at: https://notes-markdown.glitch.me/@empty-team/markdown-overflow-testing
Changes: 
• removed character limit altogether (anything that goes over a max-height becomes scrollable)
• allow embedding of images
• increased spacing between rows to make it easier to see what project an annotation is linked to

Updated Notes UI for accommodating markdown

---

server/routes.js

A recent PR accidentally reintroduced this logging; removing again.

Removed HTTP console logging, which was reintroduced

---

src/presenters/includes/description-field.js

Rigorous Colon: hookify editable description field

---

server/webpack.js
src/presenters/deleted-projects.js

Bronzed icon: hookify deleted projects

---

src/presenters/includes/editable-wrapping-field.js

Available purple: hookify editable wrapping field

---

src/components/badges/badge.js
src/components/buttons/segmented-buttons.js
src/presenters/pages/search.js
src/presenters/recent-projects.js

Testable by entering a search query that doesn't have a result in a particular category, e.g. 
https://glacier-fiction.glitch.me/search?q=scientiffic
On glacier-fiction:
On production (bug):

Glacier-fiction: fixed bug with showing 0 project count in search filters

---

src/presenters/includes/add-collection-project.js
src/presenters/includes/included-in-collections.js
src/presenters/pages/collection.js
src/state/api.js

- use hooks/function component for AddCollectionProject
- use new REST API for team project lookup
- move `useAsync` hook to state/api

Coordinated justice: hookify AddCollectionProject

---

src/curated/collections.js
src/presenters/pages/search.js
src/state/search.js
styles/collections.styl
styles/pages/search.styl

- handle collections in algolia and 'legacy' search APIs (but legacy collections search is disabled)
- show collections on the search pag
- refactor the handling of filter options
- fix some CSS on the search page

Spurious attack: add collections to search (algolia only)

---

src/components/search/search-results.js
src/components/user/users-list.js
src/curated/collections.js
src/curated/featured-embed.js

Manuscript case: https://glitch.manuscript.com/f/cases/3328292/
turn on algolia search with https://stitch-close.glitch.me/secret
try the search page https://stitch-close.glitch.me/search?q=react

Stitch close: no, actually fix the search page under algolia

---

shared/sentryHelpers.js

https://superb-guide.glitch.me/ (but there isn't anything interesting there)
https://glitch.fogbugz.com/f/cases/3328255/
* Stop sending email addresses to sentry
* Also stop sending googleToken and slackToken to sentry
* Try to stop any future tokens from being sent to sentry
* I also removed `.glitch_track_file_changes` since it doesn't do anything now
* Copy filterSecrets into the console and try running it against `localStorage['community-cachedUser']`

Superb guide: Better sentry token filtering

---

src/state/current-user.js

https://glitch.fogbugz.com/f/cases/3328447/Homepage-recent-projects-are-in-the-wrong-order
Sign in and check the recent projects area on the homepage, it should match your activity rather than showing some random old projects.

Superb guide: Fix ordering of projects on the homepage

---

src/components/profile-list/profile-list.styl
src/curated/featured.js
styles/includes/projects-collections-teams-users-container.styl

* Remix link: https://tame-whippet.glitch.me/
There has been some weird resizing / jumpiness when projects transition from the loading placeholder to loaded user list.
^ On prod
^ With min-height
* added min-height to profile-list container

Tame whippet: Fixed jumpiness of loading user avatars on projects

---

package.json
shared/api.js
shrinkwrap.yaml

https://superb-guide.glitch.me/ (but there's nothing to see there)
The other option is to silently log it and just return whatever we've downloaded so far, but now we're throwing around incomplete data.

Superb guide: Throw an error instead of going into an api request loop

---

src/components/header/header.styl
src/components/header/index.js
src/presenters/pop-overs/featured-project-options-pop.js
src/presenters/pop-overs/new-project-pop.js
styles/pop-overs.styl
styles/results-list.styl

* https://miniature-ferry.glitch.me/
* https://glitch.manuscript.com/f/cases/3328426/
* https://glitch.manuscript.com/f/cases/3328468/
* https://glitch.manuscript.com/f/cases/3328464/
* fixes view -> bug
* fixes dropdown behavior for new project pop over (arrow where it should be, popover under the button, popover opens from right/left depending on if you're signed in so it doesn't float off the page):
* fixes dropdown placement in general
* to test view -> bug try to add a project to a collection on safari
* look at glitch on a mobile phone or mimic it with the dev tools try to create a new project when signed in/not signed in see if things look right
* test dropdowns on user/team/collection/search pages
anything I'm missing? See better ways to do what I'm doing that I didn't think …

Miniature ferry: lots of style fixes

---

server/routes.js
src/presenters/pages/router.js

* Remix link https://furry-record.glitch.me
* replace punycode with encodeURIComponent for user & teams
* visit https://furry-record.glitch.me/@ΑποστολοςΚοτσιρας
* the page should load
* there should be no "UNESCAPED CHARACTERS" errors in the server logs

Furry record: only projects are punycoded, not usernames

---

src/presenters/pop-overs/add-project-to-collection-pop.js

https://glitch.fogbugz.com/f/cases/3328497/Add-project-to-collection-pop-should-use-new-API-endpoint
https://nova-chance.glitch.me/~nova-sail-1
- It uses the new api, and loads in about a quarter of the time
- It's all functional components using hooks, which is cool
- It uses memoization to make typing in filters slightly faster
Try adding it to different collections and see how it does

Nova chance: Big refactor of the add project to collection pop

---

src/components/buttons/checkbox-button.js
src/components/buttons/checkbox-button.styl
src/presenters/overlays/new-stuff.js
stories/index.js
styles/buttons.styl

https://profuse-tea.glitch.me/storybook/index.html?path=/story/button--checkbox
https://glitch.fogbugz.com/f/cases/3328491/Build-the-CheckboxButton-component
Added a component for checkboxes that are styled like buttons. I put it in the buttons folder since it pulls a lot of styling from other buttons and doesn't share anything with other inputs.
- Check out the storybook and see how it looks
- Try checking and unchecking the new stuff box

Profuse tea: Create a checkbox button component

---

webpack.config.js

##
Editor: https://glitch.com/edit/#!/helix-tyrannosaurus?path=webpack.config.js:120:11
Link: https://helix-tyrannosaurus.glitch.me
Verbose output of what files are being removed. Does not remove stats.json
Make changes and watch webpack rebuild
Are there any glitches or errors? Make changes in the project and watch webpack rebuild and access the site while it's happening.

Helix tyrannosaurus: Webpack space issues

---

src/models/team.js
src/presenters/includes/add-team-project.js
src/presenters/includes/delete-team.js
src/presenters/includes/team-users.js
src/presenters/pages/team.js
src/presenters/pop-overs/delete-team-pop.js
src/presenters/pop-overs/team-user-info-pop.js
src/presenters/pop-overs/team-user-remove-pop.js

* Remix link: https://adhesive-mascara.glitch.me
removing other user as admin
removing self
removing other user from projects
deleting the team
janky css that will be fixed later
* replace `{...props}` spreads with explicit props
* combine team users presenters into single presenter
* move invitees state into team users
* hookify DeleteTeamPop
* hookify TeamUserRemovePop
* log into https://adhesive-mascara.glitch.me
* create a new team
* add a user to the team (the CSS for pending users is janky, but that's also the case on prod; that's gonna be fixed in the next PR)
* add a project to the team
* have the other user join that project
* remove the user from the team
* delete the team

Adhesive mascara: refactor team users + popovers

---

src/presenters/projects-loader.js

* Remix link: https://pricey-countess.glitch.me/user/414500
* Manuscript link: https://glitch.manuscript.com/f/cases/3328527/Error-on-user-pages-calling-users-by-id-with-more-than-100-ids
* batch requests for users in project loader
* visit https://pricey-countess.glitch.me/user/414500
* each project's users should load

Pricey countess: batch user fetching in project loader

---

src/presenters/pages/collection.js
src/presenters/pages/team.js
src/presenters/pages/user.js
src/presenters/pop-overs/project-options-pop.js
src/presenters/user-editor.js

* https://coconut-restaurant.glitch.me
* https://glitch.manuscript.com/f/cases/3328445/
* This has all the changes of [this pr](https://github.com/FogCreek/Glitch-Community/pull/508) (that we had to revert due to a bug after fixing a merge conflict)
* PLUS a fix for the bad merge conflict, basically I wasn't passing along all the necessary props 😭 : https://github.com/FogCreek/Glitch-Community/commit/eb17cd3c334386713c18d4f28689dd92d2da705c
* When anonymous:
* On your own user page: 
* On someone else's user page: 
* On some team page:
* On search page:
* When logged in:
* On your own user page: 
* on some other user page that is not your own
* Team Pages
* On your own team page: 
* On team pages you are not a member of:
* Collection Pages
* On your own collection: 
* On someone else's …

Coconut restaurant (yet again): fixing project popovers

---

src/components/deleted-projects/index.js
src/presenters/pages/user.js

* https://stupendous-cannon.glitch.me/
* https://glitch.manuscript.com/f/cases/3328513/
* use the new api to ping for deleted projects
* create a view-only version of deleted projects that viewable only by support folks
* go to https://stupendous-cannon.glitch.me/@test-sarah with super_user enabled, click show deleted projects, notice you can't click on the projects, but you can see the titles. 
* anything I'm missing?

Stupendous cannon: Super users can view deleted projects

---

sh/setup.sh

https://support.glitch.com/t/updates-to-git-repo-urls/10711
* Updates endpoint to one that will permanently work
* Run setup.sh from sh/

Update git endpoint in sh/

---

src/components/sign-in-pop/index.js

* Remix link
* Manuscript link
* ...
* ...

goofy volleyball 1: correct signature for useAPI

---

src/components/containers/projects-list.js
src/components/tooltips/tooltip-container.js
src/presenters/pop-overs/add-team-project-pop.js
src/presenters/pop-overs/team-analytics-project-pop.js

* https://cassey-community.glitch.me
* Manuscript link
* [Case 3328621 - tooltip duplicate ids](https://glitch.manuscript.com/f/cases/3328621/)
* [Case 3328619 - pagination buttons missing alt text](https://glitch.manuscript.com/f/cases/3328619/)
* [Case 3328628 - #team-project-search input is missing a label](https://glitch.manuscript.com/f/cases/3328628/team-project-search-input-is-missing-a-label) 
* [Case 3328629 - On team page, #analytics-project-filter is missing a label](https://glitch.manuscript.com/f/cases/3328629/On-team-page-analytics-project-filter-is-missing-a-label)
* [Case 3328627 - bento box emoji missing alt text (though it shouldn't have any because it's just decoration](https://glitch.manuscript.com/f/cases/3328627/Bento-box-emoji-on-team-add-project-pop-is-using-role-im …

Cassey-community: small accessibility fixes

---

src/components/project/project-item.js
src/components/search-results/index.js
src/components/team/team-item.js
src/presenters/pop-overs/project-options-pop.js

* https://silken-bandicoot.glitch.me
* https://sentry.io/organizations/fog-creek-software/issues/1035005423/events/5c4946d1391b4fb2958c39ce255591d5/?project=1246508&query=is%3Aunresolved
* check something is an array before we map over it. For whatever reason we sometimes have project.users = an error (when we get rate limited or when we throw a 404 what have you), which we then try to map 😭 which then throws an even more noticeable error. I think we need better error handling in general, but my sense is that is already being worked on (correct me if I'm wrong and I can try to take that on!) but for now it seemed like this would be a good bandaid for this particular situation.
* you could try rate limiting yourself lol, but something I did was overwriting the response back from one of our …

Silken bandicoot

---

src/presenters/pop-overs/add-team-user-pop.js
src/presenters/pop-overs/featured-project-options-pop.js

* [Remix link](https://cassey-community.glitch.me)
* Case 3328636/case 3328631
No visual change 
* Give the button for project options on a featured project some text!
* Also the input for searching a user to add to a team - should have a label, not just placeholder
* View the accessible name in the accessibility tools of Chrome or Firefox's dev tools, or pop open your screenreader to hear the name announced

Case 3328636 featured project button & team user search need alt text

---

src/components/collection/add-collection-project-pop.js
src/components/containers/results-list.js
src/components/project/project-result-item.js

* Remix link: https://curse-pantry.glitch.me
* move arrow navigation from add-collection-project-pop to results-list
* move scrollIntoView on active from project-result-item to results-list
* log into https://curse-pantry.glitch.me
* create a collection
* verify that arrow navigation works when adding projects to the collection

Curse pantry: move arrow navigation to ResultsList

---

shared/aliases.js
src/components/fields/use-optimistic-value.js
src/components/inputs/text-area.js
src/components/inputs/text-input.js
src/components/tooltips/tooltip-container.js
src/presenters/pop-overs/add-project-to-collection-pop.js

* [colossal-child.glitch.me](https://colossal-child.glitch.me/)
Add a Hooks alias
Do these still work?

colossal-child: Add Hooks alias

---

src/state/api.js

* Remix link: https://hyper-flyingfish.glitch.me/
This is extracted from #562. This short cache is mostly for deduplicating multiple identical requests in flight. We currently mostly do this with something like ProjectsLoader, but this is conceptually a lot simpler.

Hyper flyingfish: add caching to API requests

---

src/components/sign-in-pop/index.js

* [momentous-chance.glitch.me](https://momentous-chance.glitch.me)
Autofocus the email sign-in and the sign-in code input in the login pop
- Do we actually want to autofocus these inputs? @ttseng
- Are there are any a11y downsides to autofocusing? @clottman

momentous-chance: autofocus email and sign-in code input in login

---

src/components/images/emoji.js

* Remix link: https://mountainous-catamaran.glitch.me/

Mountainous catamaran: set default alt for emoji as empty string

---

src/presenters/includes/team-analytics.js
src/presenters/pages/team.js
src/presenters/pop-overs/add-team-project-pop.js
src/presenters/pop-overs/add-team-user-pop.js
src/presenters/pop-overs/create-collection-pop.js
src/presenters/pop-overs/create-team-pop.js

Fixes some PropTypes errors introduced by the API caching PR.

Amber ophthalmologist: api PropTypes.func -> any

---

src/components/popover/dialog.js
src/components/profile-list/index.js
src/curated/collections.js

* https://different-character.glitch.me/
* https://glitch.manuscript.com/f/cases/3328654/
* verify we have a ref before we try to getBoundingClientRect
* verify we get meaningful data from getBoundingClientRect before we try to align our popovers from them. 
* verify when you resize the window stuff aligns or resizes as it used to (new project dialog for example)

Different character: sentry error

---

src/presenters/pop-overs/user-options-pop.js

[aback-thread.glitch.me](aback-thread.glitch.me)
Small refactor of `checkForCreateTeamHash`
Open [aback-thread.glitch.me/#create-team](aback-thread.glitch.me/#create-team). the create team pop should be open
Look good?

aback-thread: refactor checkForCreateTeamHash

---

src/components/team/add-team-project-pop.js
src/components/team/delete-team-pop.js
src/presenters/pop-overs/project-options-pop.js

[sprinkle-rook.glitch.me](sprinkle-rook.glitch.me)
Add `hasEmoji` prop to add project to team button
Log in and look at a team you're an admin on. The add project button should not be janky.

sprinkle-rook: add `hasEmoji` prop to add project to team button

---

src/components/sign-in-pop/index.js
src/presenters/includes/uploader.js

* [cat-aura.glitch.me](https://cat-aura.glitch.me/@taravancil)
Add a loader to the email login flow.
Log in via email. You should see the loader.

cat-aura: add loader to email login flow

---

src/components/team-users/team-user-info.js

* [sequoia-click.glitch.me/](https://sequoia-click.glitch.me/)
Update leave team button from "Remove from Team" to "Leave Team" if user is the current user
* Click your avatar from a team page, the leave team button should say "Leave Team"
* Go to a team you're an admin of, click someone else's avatar. The button should say "Remove from Team"

sequoia-click: "Remove from Team" to "Leave Team" if is the current user

---

src/components/team-users/index.js
src/components/team-users/team-user-info.js

* [fourth-crate.glitch.me](https://fourth-crate.glitch.me)
@modernserf caught a missing import in team-users, this is a quick fix to update buttons in team-users
* Team user popovers should work

fourth-crate: quick fix to buttons in team-users

---

src/presenters/pages/user.js
src/presenters/user-editor.js
src/state/user.js
src/state/user/index.js

* Remix link: https://loud-roadrunner.glitch.me/
* convert UserEditor component into hook
* log into https://loud-roadrunner.glitch.me/
* visit your user profile page
* verify that user actions (updaing profile, pinning projects) work like they do on prod

Loud roadrunner: hookify user editor

---

src/presenters/pages/team.js
src/presenters/projects-loader.js
src/presenters/team-editor.js
src/state/team.js

* Remix link: https://petalite-pot.glitch.me
* convert TeamPage to function component
* convert TeamEditor to hook
* clean up redundant methods
* log into https://petalite-pot.glitch.me
* create a team
* interact with the team page (e.g. add a project) -- it should work the same as before

Petalite pot: hookify teams page

---

src/components/popover/container.js
src/components/search-form/index.js
src/presenters/overlays/overlay-video.js

* Remix link: https://encouraging-girdle.glitch.me/
* add an `openPopover` method to PopoverContainer passed props
* use openPopover, not togglePopover, on search input focus
* verify that search bar results work with both keyboard and click navigation
* verify that the "how it works" video works with both keyboard and click navigation

Encouraging girdle: fix bug in search bar results

---

src/components/containers/projects-list.js

* https://melted-scorpion.glitch.me/@sarahzinger
* fixes an issue with the show all button I introduced in trying to fix a different bug
* click the "Show all" button on a user page
- any other bugs I made lol :sob:

Melted scorpion: fix show all bug

---

src/components/create-team-pop/index.js
src/components/popover/index.js
src/components/popover/styles.styl
src/components/sign-in-pop/index.js
src/components/team-users/styles.styl
src/components/team-users/team-user-info.js
src/hooks/use-unique-id.js

- https://nova-chance.glitch.me/
- Show the bottom border on multi popover titles, and fixed the alignment of the back button
- When removing someone from a team, unchecking one project would uncheck every project
- Reduced the amount of space before the add user to team button when there are no pending requests

Nova chance: Some misc styling and bug fixes

---

src/components/create-team-pop/index.js

* Remix link: https://mewing-owner.glitch.me
* make Create Team button a submit button
* fix setState bugs in create team pop
* log into https://mewing-owner.glitch.me
* click on the user menu
* click "create team"
* enter a team name
* click "create team"
* you should be redirected to the new team page

Mewing owner: clicking 'Create Team' should ... create team

---

src/components/account-settings-overlay/styles.styl
src/components/account-settings-overlay/two-factor-settings.js
src/components/sign-in/two-factor-form.js

- https://nova-chance.glitch.me/
- Adds a list of backup codes to the tfa menu with a button to generate a new set
- Remove the input length limit on tfa login inputs, and added an 'or a backup code' to the prompt
Turn on the user passwords dev toggle and enable tfa, then try signing in with a backup code and verify that it is removed form the list

Nova chance: Two factor auth backup codes

---

src/components/collection/container.js

* Remix link: https://ninth-berry.glitch.me/
* store sampled collections instead of re-sampling on every render
* visit https://ninth-berry.glitch.me/
* verify that featured collection projects do not constantly re-render

Ninth berry: fix preview projects

---

src/components/deleted-projects/index.js
src/state/user.js

* Remix link: https://vagabond-racer.glitch.me
* add project permissions to deleted project response
* log into https://vagabond-racer.glitch.me/@modernserf
* visit your profile page
* open the deleted projects section
* delete a project
* you should be able to undelete the projectt

Vagabond racer: include project permissions in freshly deleted projects

---

FAQ.md
server/routes.js
src/presenters/pages/index.js

https://glitch.manuscript.com/f/cases/3327795/
Is this:
- accurate?
- clear and understandable?
- enough detail? too much detail?
- missing things you have questions about?
- covering things you already know and find this useless?

Twisty citrus: caching documentation

---

src/components/popover/container.js
src/components/sign-in-pop/index.js
src/components/user-options-pop/index.js

* https://github.com/FogCreek/Glitch-Community-Work/issues/178
* Missed a pop! Now when you close the user options pop by pressing escape, focus returns to the pop button instead of body.

Foregoing-spell: also add focus management to user options pop

---

src/components/collection/collection-item-small.js
src/components/link/index.js
src/components/search-form/autocomplete.js
src/components/search/starter-kit-result.js
src/models/collection.js
src/presenters/pages/home-v2/collection-container.js
src/presenters/pages/home-v2/index.js
src/presenters/pages/team.js

https://superb-guide.glitch.me
A bunch of `<a href>` became `<Link to>`, which enables single page app transitions and makes the site a bit faster.
Try clicking the links that changed, they should all still work

Superb guide: Replace a bunch of anchor tags with link components

---

src/state/dev-toggles.js

* https://woozy-shoemaker.glitch.me/secret
* adds a dev toggle for the new `My Stuff` project
* since we're a bigger team now, I'm recommending we bump our dev toggle limit to 4. 
*  https://woozy-shoemaker.glitch.me/secret try toggling stuff, you should see the toggles in localstorage

woozy-shoemaker: 4 dev toggles :P

---

src/state/api.js

https://nova-chance.glitch.me/search?q=asdf
Uses function args when adding/removing pending requests so they actually get resolved properly
Try opening the new projects pop on your user page, try refreshing on the search results page

Nova-chance: Fix race condition with requests made on initial page load

---

src/components/collection/collection-item.js
src/components/collections-list/index.js

* [fern-street.glitch.me](https://fern-street.glitch.me)
This fixes a typo on the `showLoader` prop

fern-street: fix small typo so paginated items load smoothly

---

.circleci/config.yml

n/a
* Adds CircleCI/config.yml file, which I will probably need to update at least once
* Merge and let CircleCI build it
* Is anything obviously wrong before I merge this?
It should be...
- Ensuring a directory for artifacts
- Using a CircleCI docker image (same as Editor uses)
- Updating npm
- Restoring and checking cache of packages
- Doing integration tests (using our cypress script and NPX, we still can't put cypress in our package.json)
- Storing artifacts
It is very similar to Editor except it doesn't deploy or run other tests

tundra-beat: Add .circleci/config.yml

---

server/render.js
server/routes.js
src/app.js
src/components/video/index.js
src/hooks/use-unique-id.js
src/hooks/use-window-size.js
src/presenters/pages/create.js
src/presenters/pages/create.styl
src/server.js

- https://nova-chance.glitch.me/
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/228
- https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/216
- Added useWindowSize which monitors the window innerWidth and innerHeight
- Reset the useUniqueId counter and call react-tabs.resetIdCounter before server rendering
- Expanded a class name because the server and client treat single digit number classes differently
- Treat /index.html like / for ssr and wistia preload
Try loading /, /create, and /index.html. They should all have wistia tags in the body, html content in the network response, and there shouldn't be any react warnings about mismatches

Nova chance: Fix issues that were causing ssr not to apply

---

package.json
server/render.js
server/routes.js
server/server.js
shrinkwrap.yaml
src/client.js
src/components/header/index.js
src/components/user-options-pop/index.js
src/presenters/pages/home-v2/index.js
src/server.js
src/state/current-user.js
src/state/globals.js
views/index.ejs

- https://superb-guide.glitch.me/
- https://github.com/FogCreek/Glitch-Community-Work/issues/232
Added a hasLogin cookie set whenever the user is signed in, which is used when the current user id is unset (aka on initial page render and just after signout before an anon user is generated)
Try loading the page with your cache disabled and see if it flickers at all, both while signed in and out

Superb guide: Let the server render the page as if it is signed in

---

.circleci/config.yml

Limits branches that things run on until done

circleci: Update config.yml

---

src/utils/constants.js

https://github.com/FogCreek/Glitch-Community-Work/issues/256
Change window.origin references to window.location.origin
Try loading up the site in vivaldi v1.6.689.40

Nova-chance: Fix the site in the vivaldi browser

---

src/components/search-results/search-results.styl
src/state/search.js

* Remix link: https://rustic-bat-1.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/252
* add `starterKit` to default filters
* visit https://rustic-bat-1.glitch.me/search?q=react
* the react starter kit should be in the search results

Rustic bat 1: add starterKit to filters

---

src/components/search-results/index.js

* Remix link: http://celestial-can.glitch.me/
* Issue-tracker link: https://sentry.io/organizations/fog-creek-software/issues/1156459159/?project=1246508&query=is%3Aunresolved&statsPeriod=14d
* don't try to get projects if search results don't contain projects
* visit https://glitch.com/search?q=react&activeFilter=collection
* there will be a network error in the console for the url https://api.glitch.com/v1/projects/by/id?&limit=100 (though no errors visible to user)
* visit https://celestial-can.glitch.me/search?q=react&activeFilter=collection
* there will be no errors in the console

Celestial can: fix bug i just introduced

---

src/state/collection.js

* Remix link: https://mulberry-morocco.glitch.me
* when we first create a mystuff collection the collection returned does not have "fullurl" so we have to make ourselves so that the  "take me there" links takes folks to the right place
* enable mystuff
* create a new account
* go to a project and try to add it to your My Stuff collection
* click on the notification, make sure it takes you to the collection

Mulberry morocco: fix take me there link on mystuff creation

---

server/api.js
server/routes.js

https://fallacious-slice.glitch.me/
- Commented out the requests for project members and teams
- Removed the 'should render page' flag from projects

Fallacious-slice: Disable ssr for project pages and remove the extra data loading

---

server/cache.js

Superb-guide: Remove logging from the server cache

---

src/components/collection/add-collection-project-pop.js

* Remix link: https://nasal-harmony.glitch.me
* fixes bug that broke adding a project by url to a collection
* go to a collection you own and click "add project"
* paste in url from a project page or from an app page ex: `glitch.com/~projectname` or `projectname.glitch.me`

Nasal harmony: fix add project to collection by url

---

src/components/project/featured-project.js
src/presenters/pages/project.js
src/state/collection.js

* Remix link: https://judicious-vase.glitch.me/
* create `useToggleBookmark` hook that wraps all of the state & context that toggleBookmark needs
* replace direct calls to `toggleBookmark` with hook
* log into https://judicious-vase.glitch.me/
* enable My Stuff on https://judicious-vase.glitch.me/secret
* ensure that "My Stuff" updates correctly when you toggle the bookmark flag on a featured project
* ensure that it updates correctly when you toggle the bookmark flag on a project's page

Judicious vase: replace toggleBookmark with a hook

---

src/components/project/featured-project.js
src/presenters/pages/project.js
src/state/collection.js

Reverts FogCreek/Glitch-Community#881

Revert "Judicious vase: replace toggleBookmark with a hook"

---

src/components/collection/container.js
src/components/collections-list/more-collections.js
src/components/related-projects/index.js
src/hooks/use-sample.js
src/presenters/pages/create.js

* Remix link: https://caterwauling-freighter.glitch.me
* replace uses of sampleSize + useState with a useSample hook
the following groups of items should be in a random order that is stable while you interact with the page:
* the "Remix any app to get started" examples on https://caterwauling-freighter.glitch.me/create
* the "More from Glitch" examples on https://caterwauling-freighter.glitch.me/@glitch/css-magic
* the "Included in collections" examples on https://caterwauling-freighter.glitch.me/~community
* the "More by <user/team>" examples on https://caterwauling-freighter.glitch.me/~community

Caterwauling freighter: useSample hook

---

README.md
server/render.js
shrinkwrap.yaml

https://github.com/FogCreek/Glitch-Community-Work/issues/393
- Run a transpile right after server startup (in a setImmediate so webpack has a chance to start)
- Print 'Retranspiling' if this isn't the first transpile after server start
- Slight readme change to include a full file path
1. Join the  project and run `refresh`, the project will transpile without loading a page
2. Edit something in the src/ directory (you don't have to wait for webpack)
3. Try loading the homepage, it should print 'retranspiling'

Quixotic rocket: SSR transpile on startup, indicate initial vs retranspile

---

src/components/buttons/sign-in-button.js
src/components/layout/sign-in-layout.js
src/components/sign-in-pop/index.js
src/presenters/pages/login.js
src/presenters/pages/router.js
src/state/dev-toggles.js

* Remix link: https://ash-straw.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/194
* remove Slack login code & dev toggle
* visit https://ash-straw.glitch.me/secret
* there should be no feature flag for slack login
* https://ash-straw.glitch.me/login/slack should 404

Ash straw: remove slack login

---

src/components/collection/create-collection-pop.styl
src/components/header/new-project-pop.js
src/components/images/avatar.js
src/components/images/avatar.styl
src/components/profile-list/index.js

* https://sudsy-balance.glitch.me
* https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/361
* uses Avatar component inside _our_ Avatar component (since we generally wrap it in a tooltip, etc, there are very few places to directly substitute the component)
* Look around for any broken/missized/misshapen avatars

Sudsy balance: Avatar component

---

.babelrc
package.json
server/render.js
server/routes.js
shrinkwrap.yaml
src/components/arrow/index.js
src/presenters/pages/home-v2/banner.js
src/presenters/pages/home-v2/banner.styl
views/index.ejs

Reverts FogCreek/Glitch-Community#892

Revert "Sumptuous rainbow: styled components SSR, render '→' as icon"

---

views/index.ejs

https://repeated-snapper.glitch.me/
Remove norton verification metatag (Cori says verification is complete)

repeated-snapper: Remove norton verification metatag

---

src/models/project.js
src/presenters/pages/project.js
src/state/project-options.js

* Remix link: https://decisive-kilometer.glitch.me/@test-sarah/joining-and-leaving
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/116
* subscribe to useProjectMembers hook so that when the project members updates, our button text updates. I had originally thought it was strange we don't have success messages which is why I opened the ticket, but it looks like that's how the functionality works on the site in general. Figured I'd just fix the button text, which also helps inform that you've successfully joined or left a project.
* join a project (either a team project or just as a reg user)
* add it to a collection
* try to leave the project from that collection
* if it's a team project you should be able to …

Decisive kilometer: fix button text on join/leave 

---

src/presenters/pages/home-v2/banner.js

* https://vaulted-mirror.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/411
* Changed mark text color for homepage banner

Fixed Homepage Banner Text COlors

---

src/client.js
src/presenters/pages/secret.js
src/presenters/pages/secret.styl
src/server.js
src/state/ab-tests.js
src/state/globals.js

https://quixotic-rocket.glitch.me/secret
https://github.com/FogCreek/Glitch-Community-Work/issues/416
- Added state to ab tests and pulled them out of globals
- Replaced the reset button with a dropdown of the available groups
Try going to the secret page and setting your group. The text should update, and refreshing should keep your chosen group

Quixotic rocket: Change your ab test group from the secret page

---

src/curated/starter-kits.js

Already added as priority on Algolia but for now I believe it's still using this file so I added it here too.
Let me know if these are needed
Let me know if these are needed
Added new object with Discord starter kit values
Search for "discord" or "bot" on the site
This is my first PR on the community site so let me know if anything is needed

Adding Discord Starter to Curated Search

---

src/components/text/markdown.js

* Remix link: https://jasper-reward.glitch.me/
* Issue-tracker link: https://app.zenhub.com/workspaces/community-5d07d1359dee6059a9688176/issues/fogcreek/glitch-community-work/398
* wrap Markdown component in React.memo
* visit https://jasper-reward.glitch.me/@developit
* click `Show all [45]` on recent projects
* it should display all recent projects
* your computer should not attempt liftoff

Jasper reward: React.memo Markdown component

---

src/components/layout/sign-in-layout.js
src/components/layout/sign-in-layout.styl

* Remix link: https://kindly-titanoceratops.glitch.me/
* Issue-tracker link: not sure if there's a ticket for this?
* Specs/doc links: https://gallery.io/projects/MCHbtQVoQ2HCZZpaEieUFqhj/files/MCEJu8Y2hyDScckl30Wc2y4V2c6qLxWO8h0
* adds a create account page to the `green-impatiens` branch
* go to https://kindly-titanoceratops.glitch.me/login
Mostly looking for @oliviacpu 's feedback here since I put this off of her pr!

Create account page

---

.glitch-assets
src/presenters/pages/about/about-layout.js
src/presenters/pages/about/index.js

The about/index.js videos weren't quite the same height, so I re-exported the video:
Before
After:

Grandiose kumquat

---

src/presenters/pages/team-or-user.js

* Remix link: https://proximal-yarn.glitch.me
* Issue-tracker link: https://sentry.io/organizations/fog-creek-software/issues/1254717124/?project=1246508&query=is%3Aunresolved
* show Not Found page if user by ID lookup fails
* visit https://proximal-yarn.glitch.me/user/12345635530535
* you should get a 404 page (instead of an error)

Proximal yarn: handle 404 for /user/:id routes

---

src/components/layout/sign-in-layout.js
src/components/layout/sign-in-layout.styl
src/components/sign-in-pop/index.js
src/components/sign-in/forgot-password.js
src/components/sign-in/sign-in-with-password.js
src/components/sign-in/styles.styl
src/components/sign-in/use-magic-code.js

* Remix link: https://occipital-point.glitch.me/
* Specs/doc links: https://gallery.io/projects/MCHbtQVoQ2HCZZpaEieUFqhj/files/MCEJu8Y2hyDScckl30Wc2y4V2c6qLxWO8h0
There's now a password button (that you'll only see if user passwords is enabled)
It takes you here!
You can show your password if you want!
If the user doesn't exist it'll throw an error!
If the user types something that's not an email it'll throw an error
If you forgot your password you can go here:
It'll show you this screen and email you a magic link (although we should probably fix that magic link to also automatically open your account settings, which I don't think is a thing yet?)
* Adds a sign in with password and forgot password workflow for /login
* enable user passwords
* make sure you have a password under account …

Occipital point: Signin with User Passwords, add Forgot Password

---

package.json

Add a file to side effects in package.json so that the lever styles work

Add lever.styl to side effects

---

src/components/collection/edit-collection-color-pop.js
src/components/collection/edit-collection-color-pop.styl
src/components/filter-controller/index.js
src/components/filter-controller/styles.styl
src/components/popover/search.js
src/components/popover/styles.styl
src/components/search-form/index.js
src/components/search-form/search-form.styl

* various-dart.glitch.me
* https://github.com/FogCreek/Glitch-Community-Work/issues/495
* Updated styling for filters on user page
* Also updated search in add-to-collection, and hex input for collections
* Check out user page, add-to-collection pop, and collection color pop, make sure they look correct
* Are there any additional I missed?

Various dart: search styling fix

---

shrinkwrap.yaml
src/components/buttons/bookmark-button.styl

* Remix link: http://understood-constrictor.glitch.me
https://recordit.co/tHglBqRjuD
* today when https://github.com/FogCreek/Glitch-Community/pull/984/files#diff-325ca00b0ace128adcb0ab7292d1f95aR160 was deployed we broke the my stuff button checkmark, we can keep it a span if that's helpful for a11y purposes but we have to add display block to fix it. 
* bookmark something, make sure the check looks good

Understood constrictor: fix my stuff button

---

shrinkwrap.yaml

From https://github.com/FogCreek/Glitch-Community/pull/984

shrinkwrap.yaml changes

---

src/components/account-settings-overlay/index.js
src/components/account-settings-overlay/password-settings.js
src/components/account-settings-overlay/styles.styl
src/state/dev-toggles.js

* Remix link: [https://humdrum-triangle.glitch.me](https://humdrum-triangle.glitch.me)
* Adds a 2FA dev toggle separate from user passwords
* When "User Passwords is enabled and "Two Factor Auth" is not enabled
* There should be an option to sign in with passwords
* There should be a user settings option when signed in
* Set/reset password should be the only option in user settings
* When both are enabled
* There should be an extra page in the user settings dialog
* Enable/disable 2FA and backup codes should be visible

Humdrum-triangle: Add 2fa toggle

---

src/components/questions/index.js
src/components/questions/item.js

* Remix link: https://airy-ranunculus.glitch.me/
* use v1 API for questions
* ask for help from the glitch editor
* log into https://airy-ranunculus.glitch.me/
* you should see your question (and possibly others) on the home page

Airy ranunculus: port questions to use v1 API

---

src/components/header/index.js
src/presenters/pages/login/reset-password.js

* Remix link: https://green-impatiens.glitch.me/
* Adds the "Resume Coding" button back, using the diff from this PR https://github.com/FogCreek/Glitch-Community/pull/955
* When you're signed in and have projects you should see the resume coding button, and clicking it should take you to the editor

Add "resume coding" to home page

---

src/client.js
src/presenters/pages/router.js
src/state/ab-tests.js
src/state/current-user.js

https://fallacious-slice.glitch.me/
- Grab `location` before sending it to the join team page. This fixes an ssr error on it, the client just got a key of `undefined`
- Set cookies at the root path rather than on the current page
Check your cookies on the site, try accepting a team join request (and check the server logs)

Fallacious slice: fix two small bugs I found

---

src/components/collection/collection-projects-player.js
src/components/collection/collection-projects-player.styl
src/components/collection/container.js
src/components/collection/container.styl
src/components/project/embed.styl
src/components/project/featured-project.js
src/components/project/featured-project.styl
src/components/project/project-embed.styl
src/presenters/pages/project.styl

* Remix link: https://admitted-fly.glitch.me/@glitch/vr/play
* Made embeds larger for large viewports.  Makes the Collection Play mode better!
* This affects any project embed (on project pages, collection play mode, featured embeds on collection, profile, and team pages)

Admitted fly: Make Embeds Larger on Desktop

---

src/components/header/logo.js

* https://various-dart.glitch.me
* Change the header logo back to normal after spooky dead Halloween fish!

Bring the fish back to life!

---

src/components/create-team-pop/index.js

Reverts FogCreek/Glitch-Community#1020
Reverting while I debug what is wrong

Revert "api-updates/1: Use v1 routes for create team pop"

---

shrinkwrap.yaml

* Remix link
* Issue-tracker link
* Specs/doc links
* ...
* ...

shrinkwrap got messed up

---

src/components/header/header.styl
src/components/header/index.js
views/index.ejs

* Remix link: https://laser-bow.glitch.me
* Issue-tracker link: https://app.clubhouse.io/glitch/story/3806/sign-in-buttons-are-not-consistently-styled
before/after
So this is admittedly a hack, but I've spent a few days on these buttons and I think an isolated hack is the fastest way to resolve this for now.
The bug:
sign in buttons are not styled properly on certain pages (404 pages and search pages) because the css for the classes that are styling them are getting loaded in the wrong order. 
why is this happening?
honestly after a few days of trying to dig into this, I'm not entirely sure. I can tell you that this does not happen on shared-components@0.11.0 which is interesting. I can tell you this bug does not happen if we stop using ssr. I can tell you that this bug does not happen if …

Laser bow: hack to fix signin buttons

---

shared/ab-tests.js
src/components/onboarding-banner/index.js

https://app.clubhouse.io/glitch/story/3929/end-onboarding-a-b-test
- Removed the onboarding a/b test
- Made the onboarding banner visible to everyone
Load up a user with no projects and check out the banner

Nova chance: Remove the onboarding test and make it available to everyone

---

src/components/layout/sign-in-layout.styl

* Remix link: https://sign-in-updates.glitch.me/login
* I was asked to remove the background design on the /login page until the animation is finalized.

removed background from sign in page

---

src/presenters/pages/delete.js
src/presenters/pages/delete.styl
src/presenters/pages/router.js
src/state/segment-analytics.js

* Remix link: https://humane-clam.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/3229/create-a-delete-token-token-route-in-community
Error view:
Success view:
Adds a success and error state for when users click the link in their email to delete their account. Right now those backend endpoints don't exist but eventually they'll be able to:
- click a button in community to delete their account
- this sends them an email
- this email contains a link to glitch.com/delete?token=sometoken
- we then use that token to delete their account
- if the token is valid we show them a success page, with a form to explain why they are leaving glitch
- if the token is invalid we show them an error page
Since the backend is not complete I've just worked on the visual aspects.
* …

Create /delete route in community

---

server/api.js

The server makes requests again to ssr pages don't show up as loaders
Try loading up user/team/project/collection pages

Superb guide: Restore ssr api requests

---

src/components/project/project-user.js

no remix link did this locally
before:
after:

Fix random zero issue

---

package.json
shrinkwrap.yaml
src/presenters/pages/create.js
src/presenters/pages/create.styl

* Remix link: https://low-nebula.glitch.me/create
* Issue-tracker link: https://app.clubhouse.io/glitch/story/5372/remove-ember-and-data-dashboard-from-create
* removed the ember framework starter
* removed the data-dashboard starter app
* also updated some of the styling for consistency: 
* All content underneath headers are indented
* H3s are smaller text size than H2
* added background to help center links to help separate them better
* check out the changes at https://low-nebula.glitch.me/create

Low nebula: Updated Create Page Content

---

src/models/collection.js
src/state/api.js

* Remix link: 
https://empty-gallon.glitch.me/
* Issue-tracker link:
https://app.clubhouse.io/glitch/story/5157/client-update-collections-on-community
* Collections routes now use the v1 endpoints
* Create a collection, delete a collection, modify a collection, reorder collections, add a project to a collection, basically anything collection
Error handling is covered.

Update collections routes to use v1 routes

---

src/state/current-user.js

Make sure the user exists before putting it in state, also fix the bad merge while I'm here

💺❄️ Checkpoint: Probably a better fix for that issue

---

src/components/create-team-pop/index.js
src/presenters/pages/join-team.js
src/state/api.js
src/state/team.js

https://empty-gallon.glitch.me/
https://app.clubhouse.io/glitch/story/5551/client-update-teams-on-community
Updated the calls to the api to use the new v1 routes
All things teams related should work as expected: creation, deletion, updates, add users, remove users, add collections, remove collections, add projects, pin projects, etc
Anything that breaks or seems to be wrong.  Hopefully this will be boring and you won't notice anything :)
I'm waiting on a PR to get merged into master (https://github.com/FogCreek/Glitch/pull/2329) - until this happens avatar and cover images can't be modified.

Update api to use v1 for teams routes

---

src/components/header/header.styl
src/components/header/logo.js

https://app.clubhouse.io/glitch/story/3308/change-night-logo-to-turn-off-earlier-in-the-morning-than-9am
- Refactored the logo a bit so it only rerenders when the logo actually changes
- Bumped the morning transition from 9am to 7am
- Auto switch to the fishbones logo on halloween
- The skip to content button doesn't indent the logo
Load up the site and see how it looks. You can also try setting your pc date to halloween, or just modify the target date to see how it works
Holiday fish? New years fish?

Superb guide: Update fish time, auto halloween

---

shrinkwrap.yaml
src/components/create-team-pop/index.js

* Remix link: https://gossamer-maize.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/6038/getting-a-team-already-exists-error-when-trying-to-create-a-team-with-any-custom-name
* fix checks for existing teams/users with the given name
* remove isVerified flag from create team payload
* log into https://gossamer-maize.glitch.me/
* trying to create a team called "jungle-order" should show an error
* trying to create a team with an unused name should work
* trying to create a team with the default name should work

Gossamer maize: fix 'create team'

---

src/components/create-team-pop/index.js
src/presenters/pages/join-team.js
src/state/api.js
src/state/team.js

* Remix link: https://gossamer-maize.glitch.me/
* Issue-tracker link: https://app.clubhouse.io/glitch/story/6038/getting-a-team-already-exists-error-when-trying-to-create-a-team-with-any-custom-name
* fix checks for existing teams/users with the given name
* remove isVerified flag from create team payload
* log into https://gossamer-maize.glitch.me/
* trying to create a team called "jungle-order" should show an error
* trying to create a team with an unused name should work
* trying to create a team with the default name should work

Gossamer maize: use v1 routes for team (fixed)

---

README.md
shared/constants.js

https://app.clubhouse.io/glitch/story/6033/clarify-shared-constants-environments
https://nova-chance.glitch.me/ (nothing interesting there)
- Rewrote the comment in shared/constants.js to explain the relevance
- Added RUNNING_LOCALLY to the table in the readme
- Read the stuff and see if it either matches or improves your understanding of he two vars

Nova chance: Add some extra documentation on RUNNING_ON vs RUNNING_LOCALLY

---

src/state/api.js

* Remix link - https://empty-gallon.glitch.me/
* Issue-tracker link - https://app.clubhouse.io/glitch/story/5553/client-update-project-on-community
* Updated the api routes to the v1 routes
* Try creating, modifying, deleting, un-deleting, adding/removing users, etc to see if there is any broken functionality.

Update project api routes to v1

---

src/presenters/pages/about/company.js

* Remix: https://keith-community.glitch.me/about/company

remove them
